export type Phrase = {
  phrase: string;
  translation: string;
  example: string;
  exampleTranslation: string;
};

export const phrases: Phrase[] = [
  // Greetings / small talk
  {
    phrase: "Good morning!",
    translation: "Доброе утро!",
    example: "Good morning! How are you?",
    exampleTranslation: "Доброе утро! Как дела?",
  },
  {
    phrase: "Good afternoon!",
    translation: "Добрый день!",
    example: "Good afternoon! Nice to see you.",
    exampleTranslation: "Добрый день! Рад тебя видеть.",
  },
  {
    phrase: "Good evening!",
    translation: "Добрый вечер!",
    example: "Good evening! How was your day?",
    exampleTranslation: "Добрый вечер! Как прошёл день?",
  },
  {
    phrase: "How are you?",
    translation: "Как дела?",
    example: "Hi! How are you today?",
    exampleTranslation: "Привет! Как дела сегодня?",
  },
  {
    phrase: "I'm fine, thanks.",
    translation: "Нормально, спасибо.",
    example: "I'm fine, thanks. And you?",
    exampleTranslation: "Нормально, спасибо. А ты?",
  },
  {
    phrase: "And you?",
    translation: "А ты / а вы?",
    example: "I'm good, thanks. And you?",
    exampleTranslation: "У меня хорошо, спасибо. А у тебя?",
  },
  {
    phrase: "Nice to meet you.",
    translation: "Приятно познакомиться.",
    example: "Hi, nice to meet you.",
    exampleTranslation: "Привет, приятно познакомиться.",
  },
  {
    phrase: "Nice to see you.",
    translation: "Рад тебя видеть.",
    example: "Nice to see you again!",
    exampleTranslation: "Рад снова тебя видеть!",
  },
  {
    phrase: "How did you sleep?",
    translation: "Как ты спал?",
    example: "How did you sleep today?",
    exampleTranslation: "Как ты спал сегодня?",
  },
  {
    phrase: "Have a nice day.",
    translation: "Хорошего дня.",
    example: "Bye! Have a nice day.",
    exampleTranslation: "Пока! Хорошего дня.",
  },
  {
    phrase: "See you later.",
    translation: "Увидимся позже.",
    example: "I have to go. See you later!",
    exampleTranslation: "Мне пора. Увидимся позже!",
  },
  {
    phrase: "See you tomorrow.",
    translation: "Увидимся завтра.",
    example: "Okay, see you tomorrow.",
    exampleTranslation: "Ок, увидимся завтра.",
  },
  {
    phrase: "What's your name?",
    translation: "Как тебя зовут?",
    example: "Hi! What's your name?",
    exampleTranslation: "Привет! Как тебя зовут?",
  },
  {
    phrase: "My name is...",
    translation: "Меня зовут...",
    example: "My name is Den. Nice to meet you.",
    exampleTranslation: "Меня зовут Den. Приятно познакомиться.",
  },
  {
    phrase: "How was your day?",
    translation: "Как прошёл день?",
    example: "Hey! How was your day?",
    exampleTranslation: "Эй! Как прошёл день?",
  },
  {
    phrase: "What are you doing?",
    translation: "Что ты делаешь?",
    example: "Hey, what are you doing now?",
    exampleTranslation: "Эй, что ты сейчас делаешь?",
  },

  // Yes / no / simple replies
  {
    phrase: "Yes.",
    translation: "Да.",
    example: "Do you need help? Yes.",
    exampleTranslation: "Нужна помощь? Да.",
  },
  {
    phrase: "No.",
    translation: "Нет.",
    example: "Is this yours? No.",
    exampleTranslation: "Это твоё? Нет.",
  },
  {
    phrase: "Okay.",
    translation: "Хорошо / ок.",
    example: "See you at six. Okay.",
    exampleTranslation: "Увидимся в шесть. Ок.",
  },
  {
    phrase: "Please.",
    translation: "Пожалуйста.",
    example: "Water, please.",
    exampleTranslation: "Воды, пожалуйста.",
  },
  {
    phrase: "Thanks.",
    translation: "Спасибо.",
    example: "Here you go. Thanks.",
    exampleTranslation: "Вот. Спасибо.",
  },
  {
    phrase: "Thank you so much.",
    translation: "Большое спасибо.",
    example: "Thank you so much for your help.",
    exampleTranslation: "Большое спасибо за помощь.",
  },
  {
    phrase: "You're welcome.",
    translation: "Пожалуйста / не за что.",
    example: "Thank you! You're welcome.",
    exampleTranslation: "Спасибо! Не за что.",
  },
  {
    phrase: "Sorry.",
    translation: "Извини / извините.",
    example: "Sorry. My mistake.",
    exampleTranslation: "Извини. Моя ошибка.",
  },
  {
    phrase: "No problem.",
    translation: "Без проблем.",
    example: "Thanks for waiting. No problem!",
    exampleTranslation: "Спасибо, что подождал. Без проблем!",
  },
  {
    phrase: "No worries.",
    translation: "Не переживай / без проблем.",
    example: "Sorry I'm late. No worries.",
    exampleTranslation: "Извини, что опоздал. Без проблем.",
  },
  {
    phrase: "I got it.",
    translation: "Понял / ясно.",
    example: "Turn left. Okay, I got it.",
    exampleTranslation: "Налево. Ок, понял.",
  },
  {
    phrase: "I understand.",
    translation: "Я понимаю.",
    example: "Okay, I understand.",
    exampleTranslation: "Ок, я понимаю.",
  },
  {
    phrase: "I don't know.",
    translation: "Я не знаю.",
    example: "Where is it? I don't know.",
    exampleTranslation: "Где это? Я не знаю.",
  },
  {
    phrase: "I think so.",
    translation: "Думаю, да.",
    example: "Is this the right street? I think so.",
    exampleTranslation: "Это та улица? Думаю, да.",
  },
  {
    phrase: "I don't think so.",
    translation: "Думаю, нет.",
    example: "Is the store open? I don't think so.",
    exampleTranslation: "Магазин открыт? Думаю, нет.",
  },
  {
    phrase: "Maybe later.",
    translation: "Может, позже.",
    example: "Coffee now? Maybe later.",
    exampleTranslation: "Кофе сейчас? Может, позже.",
  },
  {
    phrase: "Sounds good.",
    translation: "Звучит хорошо.",
    example: "Let's meet at five. Sounds good.",
    exampleTranslation: "Давай встретимся в пять. Звучит хорошо.",
  },
  {
    phrase: "That's it.",
    translation: "Вот так / всё.",
    example: "Yes. That's it.",
    exampleTranslation: "Да. Вот так.",
  },
  {
    phrase: "All good.",
    translation: "Всё хорошо.",
    example: "All good. Thanks.",
    exampleTranslation: "Всё хорошо. Спасибо.",
  },

  // Clarifying / help
  {
    phrase: "Sorry, I don't understand.",
    translation: "Извините, я не понимаю.",
    example: "Sorry, I don't understand. Can you repeat?",
    exampleTranslation: "Извините, я не понимаю. Можете повторить?",
  },
  {
    phrase: "Can you repeat that?",
    translation: "Можете повторить?",
    example: "Can you repeat that, please?",
    exampleTranslation: "Можете повторить, пожалуйста?",
  },
  {
    phrase: "Say it again, please.",
    translation: "Скажи ещё раз, пожалуйста.",
    example: "I didn't hear. Say it again, please.",
    exampleTranslation: "Не услышал. Скажи ещё раз, пожалуйста.",
  },
  {
    phrase: "Please speak slowly.",
    translation: "Говорите, пожалуйста, медленно.",
    example: "Please speak slowly. I'm still learning.",
    exampleTranslation: "Говорите медленно. Я ещё учусь.",
  },
  {
    phrase: "What does that mean?",
    translation: "Что это значит?",
    example: "Sorry, what does that mean?",
    exampleTranslation: "Прости, что это значит?",
  },
  {
    phrase: "I didn't hear you.",
    translation: "Я не расслышал.",
    example: "Sorry, I didn't hear you.",
    exampleTranslation: "Извини, я не расслышал.",
  },
  {
    phrase: "Can you help me?",
    translation: "Можете мне помочь?",
    example: "Excuse me, can you help me?",
    exampleTranslation: "Извините, можете мне помочь?",
  },
  {
    phrase: "I need help.",
    translation: "Мне нужна помощь.",
    example: "Excuse me, I need help.",
    exampleTranslation: "Извините, мне нужна помощь.",
  },
  {
    phrase: "Do you speak English?",
    translation: "Вы говорите по-английски?",
    example: "Excuse me, do you speak English?",
    exampleTranslation: "Извините, вы говорите по-английски?",
  },
  {
    phrase: "I speak a little English.",
    translation: "Я говорю по-английски немного.",
    example: "I speak a little English. Please speak slowly.",
    exampleTranslation: "Я говорю по-английски немного. Говорите медленно.",
  },
  {
    phrase: "I'm learning English.",
    translation: "Я учу английский.",
    example: "I'm learning English, so speak slowly.",
    exampleTranslation: "Я учу английский, так что говорите медленно.",
  },

  // Here / there / this / that
  {
    phrase: "Here.",
    translation: "Здесь / вот.",
    example: "Put it here.",
    exampleTranslation: "Положи здесь.",
  },
  {
    phrase: "There.",
    translation: "Там.",
    example: "It's there.",
    exampleTranslation: "Оно там.",
  },
  {
    phrase: "This way.",
    translation: "Сюда.",
    example: "This way. Follow me.",
    exampleTranslation: "Сюда. Иди за мной.",
  },
  {
    phrase: "That way.",
    translation: "Туда.",
    example: "Not here. That way.",
    exampleTranslation: "Не сюда. Туда.",
  },
  {
    phrase: "It's over there.",
    translation: "Оно вон там.",
    example: "The bathroom? It's over there.",
    exampleTranslation: "Туалет? Вон там.",
  },
  {
    phrase: "It's right here.",
    translation: "Вот оно / прямо здесь.",
    example: "Looking for your keys? They're right here.",
    exampleTranslation: "Ищешь ключи? Они вот здесь.",
  },
  {
    phrase: "This one, please.",
    translation: "Вот этот, пожалуйста.",
    example: "This one, please — the blue one.",
    exampleTranslation: "Вот этот, пожалуйста — синий.",
  },
  {
    phrase: "Not that one.",
    translation: "Не тот.",
    example: "Not that one. The other one.",
    exampleTranslation: "Не тот. Другой.",
  },
  {
    phrase: "Which one?",
    translation: "Какой / который?",
    example: "There are two. Which one?",
    exampleTranslation: "Тут два. Какой?",
  },
  {
    phrase: "Is this yours?",
    translation: "Это ваше / твоё?",
    example: "Excuse me, is this yours?",
    exampleTranslation: "Извините, это ваше?",
  },
  {
    phrase: "That's not mine.",
    translation: "Это не моё.",
    example: "That's not mine. Mine is blue.",
    exampleTranslation: "Это не моё. Моё — синее.",
  },
  {
    phrase: "This is for me.",
    translation: "Это мне.",
    example: "This is for me. Thank you.",
    exampleTranslation: "Это мне. Спасибо.",
  },
  {
    phrase: "I need this.",
    translation: "Мне это нужно.",
    example: "I need this bag.",
    exampleTranslation: "Мне нужна эта сумка.",
  },
  {
    phrase: "I don't need this.",
    translation: "Мне это не нужно.",
    example: "I don't need this. Take it back.",
    exampleTranslation: "Мне это не нужно. Заберите.",
  },

  // Directions / location
  {
    phrase: "Where is the bathroom?",
    translation: "Где туалет?",
    example: "Excuse me, where is the bathroom?",
    exampleTranslation: "Извините, где туалет?",
  },
  {
    phrase: "Where is the metro?",
    translation: "Где метро?",
    example: "Excuse me, where is the metro?",
    exampleTranslation: "Извините, где метро?",
  },
  {
    phrase: "How do I get there?",
    translation: "Как туда добраться?",
    example: "How do I get there from here?",
    exampleTranslation: "Как туда добраться отсюда?",
  },
  {
    phrase: "Is it far?",
    translation: "Это далеко?",
    example: "Is it far from here?",
    exampleTranslation: "Это далеко отсюда?",
  },
  {
    phrase: "I'm a bit lost.",
    translation: "Я немного заблудился.",
    example: "Excuse me, I'm a bit lost.",
    exampleTranslation: "Извините, я немного заблудился.",
  },
  {
    phrase: "Turn left.",
    translation: "Поверните налево.",
    example: "Turn left here.",
    exampleTranslation: "Поверните здесь налево.",
  },
  {
    phrase: "Turn right.",
    translation: "Поверните направо.",
    example: "Turn right at the light.",
    exampleTranslation: "Поверните направо на светофоре.",
  },
  {
    phrase: "Go straight.",
    translation: "Идите прямо.",
    example: "Go straight for two blocks.",
    exampleTranslation: "Идите прямо два квартала.",
  },
  {
    phrase: "I'm almost there.",
    translation: "Я почти на месте.",
    example: "I'm almost there. Five minutes.",
    exampleTranslation: "Я почти на месте. Пять минут.",
  },
  {
    phrase: "I'm on my way.",
    translation: "Я уже еду / иду.",
    example: "I'm on my way. Ten minutes.",
    exampleTranslation: "Я уже еду. Десять минут.",
  },
  {
    phrase: "Where are you?",
    translation: "Ты где?",
    example: "Where are you? I can't see you.",
    exampleTranslation: "Ты где? Я тебя не вижу.",
  },
  {
    phrase: "I'm here.",
    translation: "Я здесь.",
    example: "I'm here. Where are you?",
    exampleTranslation: "Я здесь. Ты где?",
  },
  {
    phrase: "I'm outside.",
    translation: "Я снаружи.",
    example: "I'm outside. Can you open the door?",
    exampleTranslation: "Я снаружи. Можешь открыть дверь?",
  },
  {
    phrase: "I'm near the door.",
    translation: "Я у двери.",
    example: "I'm near the door. Come out.",
    exampleTranslation: "Я у двери. Выходи.",
  },
  {
    phrase: "I'm at the entrance.",
    translation: "Я у подъезда.",
    example: "I'm at the entrance. Come down.",
    exampleTranslation: "Я у подъезда. Спускайся.",
  },
  {
    phrase: "Come in.",
    translation: "Заходи.",
    example: "The door is open. Come in.",
    exampleTranslation: "Дверь открыта. Заходи.",
  },
  {
    phrase: "Come down, please.",
    translation: "Спустись, пожалуйста.",
    example: "I'm outside. Come down, please.",
    exampleTranslation: "Я снаружи. Спустись, пожалуйста.",
  },
  {
    phrase: "Wait here.",
    translation: "Подожди здесь.",
    example: "Wait here. I'll be back.",
    exampleTranslation: "Подожди здесь. Я скоро вернусь.",
  },
  {
    phrase: "Follow me.",
    translation: "Иди за мной.",
    example: "Follow me. It's close.",
    exampleTranslation: "Иди за мной. Это рядом.",
  },
  {
    phrase: "Where should we meet?",
    translation: "Где встретимся?",
    example: "Where should we meet — at the door?",
    exampleTranslation: "Где встретимся — у двери?",
  },
  {
    phrase: "I'll meet you there.",
    translation: "Встретимся там.",
    example: "I can't pick you up. I'll meet you there.",
    exampleTranslation: "Не смогу заехать. Встретимся там.",
  },
  {
    phrase: "I live near here.",
    translation: "Я живу рядом.",
    example: "I live near here, so I walk a lot.",
    exampleTranslation: "Я живу рядом, поэтому часто хожу пешком.",
  },

  // Time / plans
  {
    phrase: "What time is it?",
    translation: "Который час?",
    example: "Excuse me, what time is it?",
    exampleTranslation: "Извините, который час?",
  },
  {
    phrase: "Today.",
    translation: "Сегодня.",
    example: "Can we meet today?",
    exampleTranslation: "Можем встретиться сегодня?",
  },
  {
    phrase: "Tomorrow.",
    translation: "Завтра.",
    example: "See you tomorrow.",
    exampleTranslation: "Увидимся завтра.",
  },
  {
    phrase: "Later.",
    translation: "Потом / позже.",
    example: "Not now. Later.",
    exampleTranslation: "Не сейчас. Потом.",
  },
  {
    phrase: "Now.",
    translation: "Сейчас.",
    example: "Come now.",
    exampleTranslation: "Иди сейчас.",
  },
  {
    phrase: "One minute.",
    translation: "Минуту.",
    example: "One minute. I'm almost ready.",
    exampleTranslation: "Минуту. Я почти готов.",
  },
  {
    phrase: "Just a second.",
    translation: "Секунду.",
    example: "Just a second, let me check.",
    exampleTranslation: "Секунду, сейчас проверю.",
  },
  {
    phrase: "I'm free after six.",
    translation: "Я свободен после шести.",
    example: "I'm free after six if that works.",
    exampleTranslation: "Я свободен после шести, если удобно.",
  },
  {
    phrase: "Does that work for you?",
    translation: "Тебе так удобно?",
    example: "Saturday at noon — does that work for you?",
    exampleTranslation: "Суббота в полдень — тебе так удобно?",
  },
  {
    phrase: "I'll be there in ten.",
    translation: "Буду через десять минут.",
    example: "I'll be there in ten. Wait for me.",
    exampleTranslation: "Буду через десять. Подожди меня.",
  },
  {
    phrase: "It's getting late.",
    translation: "Уже поздно становится.",
    example: "It's getting late. I should go home.",
    exampleTranslation: "Уже поздно. Мне пора домой.",
  },
  {
    phrase: "I should get going.",
    translation: "Мне пора идти.",
    example: "I should get going. See you!",
    exampleTranslation: "Мне пора идти. Увидимся!",
  },
  {
    phrase: "What are you up to?",
    translation: "Какие планы?",
    example: "Hey, what are you up to today?",
    exampleTranslation: "Эй, какие планы на сегодня?",
  },
  {
    phrase: "I'm busy.",
    translation: "Я занят.",
    example: "Sorry, I'm busy now.",
    exampleTranslation: "Извини, я сейчас занят.",
  },
  {
    phrase: "I'm free.",
    translation: "Я свободен.",
    example: "I'm free after lunch.",
    exampleTranslation: "Я свободен после обеда.",
  },
  {
    phrase: "I'm ready.",
    translation: "Я готов.",
    example: "I'm ready. Let's go.",
    exampleTranslation: "Я готов. Пойдём.",
  },
  {
    phrase: "I'm not ready.",
    translation: "Я не готов.",
    example: "Wait. I'm not ready.",
    exampleTranslation: "Подожди. Я не готов.",
  },
  {
    phrase: "Let's go.",
    translation: "Пойдём.",
    example: "Ready? Let's go.",
    exampleTranslation: "Готов? Пойдём.",
  },
  {
    phrase: "Let's start.",
    translation: "Начнём.",
    example: "Okay. Let's start.",
    exampleTranslation: "Ок. Начнём.",
  },

  // Cafe / food / shopping
  {
    phrase: "A table for two, please.",
    translation: "Столик на двоих, пожалуйста.",
    example: "Hi, a table for two, please.",
    exampleTranslation: "Здравствуйте, столик на двоих, пожалуйста.",
  },
  {
    phrase: "Could I get a menu?",
    translation: "Можно меню?",
    example: "Hi, could I get a menu, please?",
    exampleTranslation: "Здравствуйте, можно меню, пожалуйста?",
  },
  {
    phrase: "Water, please.",
    translation: "Воды, пожалуйста.",
    example: "Water, please. No ice.",
    exampleTranslation: "Воды, пожалуйста. Без льда.",
  },
  {
    phrase: "I'll have the same.",
    translation: "Мне то же самое.",
    example: "That looks good — I'll have the same.",
    exampleTranslation: "Выглядит вкусно — мне то же самое.",
  },
  {
    phrase: "The bill, please.",
    translation: "Счёт, пожалуйста.",
    example: "The bill, please. Thank you.",
    exampleTranslation: "Счёт, пожалуйста. Спасибо.",
  },
  {
    phrase: "Can I pay by card?",
    translation: "Можно оплатить картой?",
    example: "Can I pay by card, please?",
    exampleTranslation: "Можно оплатить картой, пожалуйста?",
  },
  {
    phrase: "Do you take card?",
    translation: "Картой можно?",
    example: "Do you take card, or cash only?",
    exampleTranslation: "Картой можно, или только наличные?",
  },
  {
    phrase: "For here or to go?",
    translation: "Здесь или с собой?",
    example: "For here or to go? To go, please.",
    exampleTranslation: "Здесь или с собой? С собой, пожалуйста.",
  },
  {
    phrase: "How much is this?",
    translation: "Сколько это стоит?",
    example: "Excuse me, how much is this?",
    exampleTranslation: "Извините, сколько это стоит?",
  },
  {
    phrase: "I'd like this, please.",
    translation: "Мне вот это, пожалуйста.",
    example: "I'd like this, please. And water.",
    exampleTranslation: "Мне вот это, пожалуйста. И воды.",
  },
  {
    phrase: "I'm just looking, thanks.",
    translation: "Я просто смотрю, спасибо.",
    example: "Need help? I'm just looking, thanks.",
    exampleTranslation: "Помочь? Я просто смотрю, спасибо.",
  },
  {
    phrase: "Can I return this?",
    translation: "Можно это вернуть?",
    example: "Can I return this if it doesn't fit?",
    exampleTranslation: "Можно это вернуть, если не подойдёт?",
  },
  {
    phrase: "I need a bag, please.",
    translation: "Мне нужен пакет, пожалуйста.",
    example: "I need a bag, please. A small one.",
    exampleTranslation: "Мне нужен пакет, пожалуйста. Маленький.",
  },
  {
    phrase: "Where can I buy water?",
    translation: "Где можно купить воду?",
    example: "Excuse me, where can I buy water?",
    exampleTranslation: "Извините, где можно купить воду?",
  },
  {
    phrase: "Is this seat taken?",
    translation: "Это место занято?",
    example: "Excuse me, is this seat taken?",
    exampleTranslation: "Извините, это место занято?",
  },
  {
    phrase: "Can I sit here?",
    translation: "Можно здесь сесть?",
    example: "Excuse me, can I sit here?",
    exampleTranslation: "Извините, можно здесь сесть?",
  },
  {
    phrase: "Open or closed?",
    translation: "Открыто или закрыто?",
    example: "Excuse me — open or closed?",
    exampleTranslation: "Извините — открыто или закрыто?",
  },
  {
    phrase: "What time do you close?",
    translation: "Во сколько вы закрываетесь?",
    example: "What time do you close today?",
    exampleTranslation: "Во сколько вы закрываетесь сегодня?",
  },

  // Delivery / door / home
  {
    phrase: "I have a delivery for you.",
    translation: "У меня для вас доставка.",
    example: "Hi, I have a delivery for you.",
    exampleTranslation: "Здравствуйте, у меня для вас доставка.",
  },
  {
    phrase: "I'll be right down.",
    translation: "Сейчас спущусь.",
    example: "I'm on the third floor. I'll be right down.",
    exampleTranslation: "Я на третьем этаже. Сейчас спущусь.",
  },
  {
    phrase: "Leave it at the door.",
    translation: "Оставьте у двери.",
    example: "I'm busy. Leave it at the door.",
    exampleTranslation: "Я занят. Оставьте у двери.",
  },
  {
    phrase: "Can you ring the doorbell?",
    translation: "Можете позвонить в звонок?",
    example: "I'm home. Can you ring the doorbell?",
    exampleTranslation: "Я дома. Можете позвонить в звонок?",
  },
  {
    phrase: "Is this the right address?",
    translation: "Это правильный адрес?",
    example: "Just checking — is this the right address?",
    exampleTranslation: "Просто уточняю — это правильный адрес?",
  },
  {
    phrase: "Open the door, please.",
    translation: "Открой дверь, пожалуйста.",
    example: "I'm here. Open the door, please.",
    exampleTranslation: "Я здесь. Открой дверь, пожалуйста.",
  },
  {
    phrase: "Close the door, please.",
    translation: "Закрой дверь, пожалуйста.",
    example: "It's cold. Close the door, please.",
    exampleTranslation: "Холодно. Закрой дверь, пожалуйста.",
  },
  {
    phrase: "What's the code?",
    translation: "Какой код?",
    example: "What's the code for the door?",
    exampleTranslation: "Какой код от двери?",
  },
  {
    phrase: "Which floor?",
    translation: "Какой этаж?",
    example: "Which floor? Third floor, please.",
    exampleTranslation: "Какой этаж? Третий, пожалуйста.",
  },
  {
    phrase: "Which apartment?",
    translation: "Какая квартира?",
    example: "Which apartment? 12?",
    exampleTranslation: "Какая квартира? 12?",
  },
  {
    phrase: "Put it here.",
    translation: "Поставь / положи сюда.",
    example: "Put it here, please.",
    exampleTranslation: "Положи сюда, пожалуйста.",
  },
  {
    phrase: "Put it there.",
    translation: "Поставь / положи туда.",
    example: "Put it there, by the wall.",
    exampleTranslation: "Поставь туда, у стены.",
  },
  {
    phrase: "Take this.",
    translation: "Возьми это.",
    example: "Take this. It's for you.",
    exampleTranslation: "Возьми это. Это тебе.",
  },
  {
    phrase: "The Wi-Fi isn't working.",
    translation: "Вайфай не работает.",
    example: "The Wi-Fi isn't working. Can you check?",
    exampleTranslation: "Вайфай не работает. Можешь проверить?",
  },
  {
    phrase: "What's the Wi-Fi password?",
    translation: "Какой пароль от вайфая?",
    example: "What's the Wi-Fi password?",
    exampleTranslation: "Какой пароль от вайфая?",
  },
  {
    phrase: "Is there Wi-Fi here?",
    translation: "Здесь есть вайфай?",
    example: "Is there Wi-Fi here? What's the password?",
    exampleTranslation: "Здесь есть вайфай? Какой пароль?",
  },

  // Phone / messages
  {
    phrase: "Call me.",
    translation: "Позвони мне.",
    example: "Call me when you're here.",
    exampleTranslation: "Позвони, когда будешь здесь.",
  },
  {
    phrase: "Text me.",
    translation: "Напиши мне.",
    example: "Text me the address.",
    exampleTranslation: "Напиши мне адрес.",
  },
  {
    phrase: "Send me the address.",
    translation: "Пришли адрес.",
    example: "Send me the address, please.",
    exampleTranslation: "Пришли адрес, пожалуйста.",
  },
  {
    phrase: "Did you get my message?",
    translation: "Ты получил моё сообщение?",
    example: "Did you get my message about tomorrow?",
    exampleTranslation: "Ты получил сообщение про завтра?",
  },
  {
    phrase: "Sorry, I missed your call.",
    translation: "Извини, пропустил твой звонок.",
    example: "Sorry, I missed your call — what's up?",
    exampleTranslation: "Извини, пропустил звонок — что случилось?",
  },
  {
    phrase: "Can you hear me?",
    translation: "Меня слышно?",
    example: "The connection is bad — can you hear me?",
    exampleTranslation: "Связь плохая — меня слышно?",
  },
  {
    phrase: "Can I get your number?",
    translation: "Можно твой номер?",
    example: "Can I get your number? I'll text you.",
    exampleTranslation: "Можно твой номер? Напишу тебе.",
  },

  // Feelings / soft daily
  {
    phrase: "I'm tired.",
    translation: "Я устал.",
    example: "I'm tired. Let's rest.",
    exampleTranslation: "Я устал. Давай отдохнём.",
  },
  {
    phrase: "I'm hungry.",
    translation: "Я голодный.",
    example: "I'm hungry. Let's eat.",
    exampleTranslation: "Я голодный. Давай поедим.",
  },
  {
    phrase: "I'm thirsty.",
    translation: "Я хочу пить.",
    example: "I'm thirsty. Water, please.",
    exampleTranslation: "Я хочу пить. Воды, пожалуйста.",
  },
  {
    phrase: "I'm cold.",
    translation: "Мне холодно.",
    example: "I'm cold. Close the window.",
    exampleTranslation: "Мне холодно. Закрой окно.",
  },
  {
    phrase: "I'm hot.",
    translation: "Мне жарко.",
    example: "I'm hot. Open the window.",
    exampleTranslation: "Мне жарко. Открой окно.",
  },
  {
    phrase: "I'm not in the mood.",
    translation: "У меня нет настроения.",
    example: "Want to go out? I'm not in the mood.",
    exampleTranslation: "Хочешь пойти? У меня нет настроения.",
  },
  {
    phrase: "Is everything okay?",
    translation: "Всё в порядке?",
    example: "You look worried — is everything okay?",
    exampleTranslation: "Ты выглядишь обеспокоенным — всё в порядке?",
  },
  {
    phrase: "I appreciate it.",
    translation: "Я это ценю.",
    example: "Thanks for waiting. I appreciate it.",
    exampleTranslation: "Спасибо, что подождал. Я это ценю.",
  },
  {
    phrase: "It slipped my mind.",
    translation: "Я забыл.",
    example: "I was supposed to call, but it slipped my mind.",
    exampleTranslation: "Я должен был позвонить, но забыл.",
  },
  {
    phrase: "I'm running late.",
    translation: "Я опаздываю.",
    example: "I'm running late. Ten more minutes.",
    exampleTranslation: "Я опаздываю. Ещё десять минут.",
  },
  {
    phrase: "Sorry I'm late.",
    translation: "Извините, что опоздал.",
    example: "Sorry I'm late. The bus was slow.",
    exampleTranslation: "Извините, что опоздал. Автобус ехал медленно.",
  },
  {
    phrase: "No rush.",
    translation: "Не торопись.",
    example: "Take your time, no rush.",
    exampleTranslation: "Не торопись, времени достаточно.",
  },
  {
    phrase: "Take your time.",
    translation: "Не торопись.",
    example: "Take your time. I'm in no rush.",
    exampleTranslation: "Не торопись. Я никуда не спешу.",
  },
  {
    phrase: "It's up to you.",
    translation: "Решать тебе.",
    example: "We can stay in or go out. It's up to you.",
    exampleTranslation: "Можем остаться дома или пойти. Решать тебе.",
  },
  {
    phrase: "That sounds good to me.",
    translation: "Меня это устраивает.",
    example: "We can meet at six. That sounds good to me.",
    exampleTranslation: "Можем встретиться в шесть. Меня устраивает.",
  },
  {
    phrase: "Let's give it a shot.",
    translation: "Давай попробуем.",
    example: "I've never tried this, but let's give it a shot.",
    exampleTranslation: "Я никогда это не пробовал, но давай попробуем.",
  },
  {
    phrase: "It's worth a try.",
    translation: "Стоит попробовать.",
    example: "I'm not sure, but it's worth a try.",
    exampleTranslation: "Не уверен, но стоит попробовать.",
  },
  {
    phrase: "Let's see how it goes.",
    translation: "Посмотрим, как пойдёт.",
    example: "We'll start small and see how it goes.",
    exampleTranslation: "Начнём с малого и посмотрим, как пойдёт.",
  },
  {
    phrase: "I'll keep that in mind.",
    translation: "Я это учту.",
    example: "You prefer window seats? I'll keep that in mind.",
    exampleTranslation: "Ты предпочитаешь места у окна? Я это учту.",
  },
  {
    phrase: "That makes sense.",
    translation: "Это логично / понятно.",
    example: "Ah, that makes sense.",
    exampleTranslation: "А, понятно.",
  },
  {
    phrase: "I'm on it.",
    translation: "Уже занимаюсь этим.",
    example: "Can you send it today? I'm on it.",
    exampleTranslation: "Сможешь отправить сегодня? Уже занимаюсь.",
  },
  {
    phrase: "I'll figure it out.",
    translation: "Я разберусь.",
    example: "I don't know yet, but I'll figure it out.",
    exampleTranslation: "Пока не знаю, но разберусь.",
  },
  {
    phrase: "It is what it is.",
    translation: "Что есть, то есть.",
    example: "We missed the bus, but it is what it is.",
    exampleTranslation: "Мы опоздали на автобус, но что уж поделаешь.",
  },
  {
    phrase: "I just moved here.",
    translation: "Я недавно сюда переехал.",
    example: "I just moved here last month.",
    exampleTranslation: "Я переехал сюда только в прошлом месяце.",
  },
  {
    phrase: "I'm still getting used to it.",
    translation: "Я ещё привыкаю.",
    example: "The city is big. I'm still getting used to it.",
    exampleTranslation: "Город большой. Я ещё привыкаю.",
  },
  {
    phrase: "I'm originally from Russia.",
    translation: "Я из России.",
    example: "I'm originally from Russia, but I live here now.",
    exampleTranslation: "Я из России, но сейчас живу здесь.",
  },
  {
    phrase: "I work remotely.",
    translation: "Я работаю удалённо.",
    example: "Most days I work remotely from home.",
    exampleTranslation: "В большинстве дней я работаю удалённо из дома.",
  },
  {
    phrase: "I'm here for work.",
    translation: "Я здесь по работе.",
    example: "I'm here for work for a few months.",
    exampleTranslation: "Я здесь по работе на несколько месяцев.",
  },
  {
    phrase: "Let's grab a coffee.",
    translation: "Давай выпьем кофе.",
    example: "Let's grab a coffee sometime.",
    exampleTranslation: "Давай как-нибудь выпьем кофе.",
  },
  {
    phrase: "I'd love to stay in touch.",
    translation: "Давай останемся на связи.",
    example: "It was great talking. I'd love to stay in touch.",
    exampleTranslation: "Было здорово поговорить. Давай останемся на связи.",
  },
  {
    phrase: "What brings you here?",
    translation: "Что тебя сюда привело?",
    example: "So what brings you here tonight?",
    exampleTranslation: "Так что привело тебя сюда сегодня?",
  },
  {
    phrase: "Have we met before?",
    translation: "Мы раньше встречались?",
    example: "Sorry, have we met before?",
    exampleTranslation: "Извини, мы раньше встречались?",
  },
  {
    phrase: "It was great meeting you.",
    translation: "Было здорово познакомиться.",
    example: "I have to run, but it was great meeting you.",
    exampleTranslation: "Мне пора, но было здорово познакомиться.",
  },
  {
    phrase: "After you.",
    translation: "После вас / проходите.",
    example: "After you — go ahead.",
    exampleTranslation: "После вас — проходите.",
  },
  {
    phrase: "Here you go.",
    translation: "Вот, пожалуйста.",
    example: "Here you go. Have a nice day!",
    exampleTranslation: "Вот, пожалуйста. Хорошего дня!",
  },
  {
    phrase: "Look.",
    translation: "Смотри.",
    example: "Look. It's here.",
    exampleTranslation: "Смотри. Вот оно.",
  },
  {
    phrase: "Listen.",
    translation: "Слушай.",
    example: "Listen. This is important.",
    exampleTranslation: "Слушай. Это важно.",
  },
  {
    phrase: "Stop.",
    translation: "Стоп / остановись.",
    example: "Stop. Wait.",
    exampleTranslation: "Стоп. Подожди.",
  },
  {
    phrase: "Slow down.",
    translation: "Медленнее.",
    example: "Slow down, please.",
    exampleTranslation: "Медленнее, пожалуйста.",
  },
  {
    phrase: "Come closer.",
    translation: "Подойди ближе.",
    example: "Come closer. Look here.",
    exampleTranslation: "Подойди ближе. Смотри сюда.",
  },
  {
    phrase: "Sit down, please.",
    translation: "Садись, пожалуйста.",
    example: "Sit down, please. Rest.",
    exampleTranslation: "Садись, пожалуйста. Отдохни.",
  },
  {
    phrase: "Stand up, please.",
    translation: "Встань, пожалуйста.",
    example: "Stand up, please. Let's go.",
    exampleTranslation: "Встань, пожалуйста. Пойдём.",
  },
  {
    phrase: "We're done.",
    translation: "Мы закончили.",
    example: "We're done. Good job.",
    exampleTranslation: "Мы закончили. Молодец.",
  },
  {
    phrase: "It looks like rain.",
    translation: "Похоже, будет дождь.",
    example: "It looks like rain — grab an umbrella.",
    exampleTranslation: "Похоже, будет дождь — возьми зонт.",
  },
  {
    phrase: "Drink some water.",
    translation: "Выпей воды.",
    example: "Drink some water before we go.",
    exampleTranslation: "Выпей воды, прежде чем идём.",
  },
];
