export type Phrase = {
  phrase: string;
  translation: string;
  example: string;
  exampleTranslation: string;
};

export const phrases: Phrase[] = [
  {
    phrase: "I'll figure it out.",
    translation: "Я разберусь / что-нибудь придумаю.",
    example: "I don't know how to fix it yet, but I'll figure it out.",
    exampleTranslation: "Я пока не знаю, как это исправить, но разберусь.",
  },
  {
    phrase: "It is what it is.",
    translation: "Что есть, то есть.",
    example: "We missed the flight, but it is what it is.",
    exampleTranslation: "Мы опоздали на рейс, но что уж поделаешь.",
  },
  {
    phrase: "Let's play it by ear.",
    translation: "Решим по ситуации.",
    example: "We don't have a plan yet, let's play it by ear.",
    exampleTranslation: "У нас пока нет плана, решим по ситуации.",
  },
  {
    phrase: "I'm on it.",
    translation: "Уже занимаюсь этим.",
    example: "Can you send the report today? I'm on it.",
    exampleTranslation: "Сможешь отправить отчёт сегодня? Уже занимаюсь.",
  },
  {
    phrase: "That makes sense.",
    translation: "Это логично / понятно.",
    example: "So the train was delayed because of the storm. That makes sense.",
    exampleTranslation: "Значит, поезд задержали из-за шторма. Понятно.",
  },
  {
    phrase: "I'm not sure that's a good idea.",
    translation: "Не уверен, что это хорошая идея.",
    example: "I'm not sure that's a good idea, it's pretty late already.",
    exampleTranslation: "Не уверен, что это хорошая идея, уже довольно поздно.",
  },
  {
    phrase: "Let me get back to you on that.",
    translation: "Дай мне подумать и ответить позже.",
    example: "I need to check my calendar, let me get back to you on that.",
    exampleTranslation: "Мне нужно проверить календарь, отвечу позже.",
  },
  {
    phrase: "No worries.",
    translation: "Не переживай / без проблем.",
    example: "Sorry I'm a bit late. No worries, we just started.",
    exampleTranslation: "Извини, я немного опоздал. Без проблем, мы только начали.",
  },
  {
    phrase: "I could use some help.",
    translation: "Мне бы не помешала помощь.",
    example: "This box is heavy, I could use some help.",
    exampleTranslation: "Эта коробка тяжёлая, мне бы не помешала помощь.",
  },
  {
    phrase: "Let's take it one step at a time.",
    translation: "Давай двигаться шаг за шагом.",
    example: "This project feels huge, let's take it one step at a time.",
    exampleTranslation: "Этот проект кажется огромным, давай шаг за шагом.",
  },
  {
    phrase: "I appreciate it.",
    translation: "Я это ценю.",
    example: "Thanks for waiting for me, I appreciate it.",
    exampleTranslation: "Спасибо, что подождал меня, я это ценю.",
  },
  {
    phrase: "It slipped my mind.",
    translation: "Я забыл (это вылетело из головы).",
    example: "I was supposed to call her back, but it slipped my mind.",
    exampleTranslation: "Я должен был перезвонить ей, но забыл.",
  },
  {
    phrase: "Let's cut to the chase.",
    translation: "Давай ближе к делу.",
    example: "We don't have much time, let's cut to the chase.",
    exampleTranslation: "У нас мало времени, давай ближе к делу.",
  },
  {
    phrase: "I'm running a bit late.",
    translation: "Я немного опаздываю.",
    example: "I'm running a bit late, I'll be there in ten minutes.",
    exampleTranslation: "Я немного опаздываю, буду через десять минут.",
  },
  {
    phrase: "That sounds good to me.",
    translation: "Меня это устраивает.",
    example: "We can meet at six. That sounds good to me.",
    exampleTranslation: "Можем встретиться в шесть. Меня устраивает.",
  },
  {
    phrase: "I wasn't expecting that.",
    translation: "Я этого не ожидал.",
    example: "She agreed right away, I wasn't expecting that.",
    exampleTranslation: "Она сразу согласилась, я этого не ожидал.",
  },
  {
    phrase: "Let's give it a shot.",
    translation: "Давай попробуем.",
    example: "I've never made this dish before, but let's give it a shot.",
    exampleTranslation: "Я никогда не готовил это блюдо, но давай попробуем.",
  },
  {
    phrase: "I'll keep that in mind.",
    translation: "Я это учту.",
    example: "You prefer window seats? I'll keep that in mind.",
    exampleTranslation: "Ты предпочитаешь места у окна? Я это учту.",
  },
  {
    phrase: "It's up to you.",
    translation: "Решать тебе.",
    example: "We can stay in or go out, it's up to you.",
    exampleTranslation: "Можем остаться дома или пойти куда-то, решать тебе.",
  },
  {
    phrase: "I'm having second thoughts.",
    translation: "У меня появились сомнения.",
    example: "I signed up for the course, but now I'm having second thoughts.",
    exampleTranslation: "Я записался на курс, но теперь сомневаюсь.",
  },
  {
    phrase: "Let's not jump to conclusions.",
    translation: "Не будем спешить с выводами.",
    example: "We don't know the full story yet, let's not jump to conclusions.",
    exampleTranslation: "Мы ещё не знаем всей истории, не будем спешить с выводами.",
  },
  {
    phrase: "I'm all ears.",
    translation: "Я весь внимание.",
    example: "You have an idea for the trip? I'm all ears.",
    exampleTranslation: "У тебя есть идея насчёт поездки? Я весь внимание.",
  },
  {
    phrase: "That's easier said than done.",
    translation: "Легче сказать, чем сделать.",
    example: "Just relax, she said. That's easier said than done.",
    exampleTranslation: "«Просто расслабься», — сказала она. Легче сказать, чем сделать.",
  },
  {
    phrase: "I'm in no rush.",
    translation: "Я никуда не спешу.",
    example: "Take your time, I'm in no rush.",
    exampleTranslation: "Не торопись, я никуда не спешу.",
  },
  {
    phrase: "Let's touch base later.",
    translation: "Давай созвонимся / свяжемся позже.",
    example: "I'm in a meeting now, let's touch base later.",
    exampleTranslation: "Я сейчас на встрече, давай свяжемся позже.",
  },
  {
    phrase: "I didn't mean it that way.",
    translation: "Я не это имел в виду.",
    example: "Sorry if that sounded rude, I didn't mean it that way.",
    exampleTranslation: "Извини, если это прозвучало грубо, я не это имел в виду.",
  },
  {
    phrase: "It's worth a try.",
    translation: "Стоит попробовать.",
    example: "I'm not sure it will work, but it's worth a try.",
    exampleTranslation: "Не уверен, что сработает, но стоит попробовать.",
  },
  {
    phrase: "I'll take your word for it.",
    translation: "Поверю тебе на слово.",
    example: "You say the road is closed? I'll take your word for it.",
    exampleTranslation: "Говоришь, дорога закрыта? Поверю тебе на слово.",
  },
  {
    phrase: "Let's see how it goes.",
    translation: "Посмотрим, как пойдёт.",
    example: "We'll start with a small budget and see how it goes.",
    exampleTranslation: "Начнём с небольшого бюджета и посмотрим, как пойдёт.",
  },
  {
    phrase: "I'm not in the mood.",
    translation: "У меня нет настроения.",
    example: "Do you want to go out tonight? I'm not in the mood.",
    exampleTranslation: "Хочешь пойти куда-нибудь вечером? У меня нет настроения.",
  },
  {
    phrase: "That's a fair point.",
    translation: "Справедливое замечание.",
    example: "You said it might rain, that's a fair point, let's bring umbrellas.",
    exampleTranslation: "Ты сказал, может пойти дождь, справедливо, возьмём зонты.",
  },
  {
    phrase: "I'll leave it up to you.",
    translation: "Оставлю это на твоё усмотрение.",
    example: "Choose the restaurant, I'll leave it up to you.",
    exampleTranslation: "Выбери ресторан, оставлю это на твоё усмотрение.",
  },

  // Delivery / courier
  {
    phrase: "I have a delivery for you.",
    translation: "У меня для вас доставка.",
    example: "Hi, I have a delivery for you. Can you sign here?",
    exampleTranslation: "Здравствуйте, у меня для вас доставка. Можете расписаться здесь?",
  },
  {
    phrase: "Could you leave it at the door?",
    translation: "Можете оставить у двери?",
    example: "I'm in a meeting, could you leave it at the door?",
    exampleTranslation: "Я на встрече, можете оставить у двери?",
  },
  {
    phrase: "I'll be right down.",
    translation: "Сейчас спущусь.",
    example: "I'm on the third floor, I'll be right down.",
    exampleTranslation: "Я на третьем этаже, сейчас спущусь.",
  },
  {
    phrase: "Where should I leave the package?",
    translation: "Куда мне оставить посылку?",
    example: "You're not home — where should I leave the package?",
    exampleTranslation: "Вас нет дома — куда мне оставить посылку?",
  },
  {
    phrase: "Can you ring the doorbell?",
    translation: "Можете позвонить в звонок?",
    example: "I'm home, can you ring the doorbell?",
    exampleTranslation: "Я дома, можете позвонить в звонок?",
  },
  {
    phrase: "The order is under my name.",
    translation: "Заказ оформлен на моё имя.",
    example: "The order is under my name, Den Mar.",
    exampleTranslation: "Заказ оформлен на моё имя, Den Mar.",
  },
  {
    phrase: "Is this the right address?",
    translation: "Это правильный адрес?",
    example: "Just checking — is this the right address?",
    exampleTranslation: "Просто уточняю — это правильный адрес?",
  },
  {
    phrase: "I didn't get a notification.",
    translation: "Мне не пришло уведомление.",
    example: "I didn't get a notification that it was delivered.",
    exampleTranslation: "Мне не пришло уведомление, что заказ доставлен.",
  },
  {
    phrase: "Can you deliver it later today?",
    translation: "Можете доставить позже сегодня?",
    example: "I won't be home until six. Can you deliver it later today?",
    exampleTranslation: "Меня не будет дома до шести. Можете доставить позже сегодня?",
  },
  {
    phrase: "Please leave it with the front desk.",
    translation: "Пожалуйста, оставьте на ресепшене.",
    example: "If I'm not there, please leave it with the front desk.",
    exampleTranslation: "Если меня не будет, пожалуйста, оставьте на ресепшене.",
  },

  // About yourself
  {
    phrase: "I just moved here.",
    translation: "Я недавно сюда переехал.",
    example: "I just moved here last month.",
    exampleTranslation: "Я переехал сюда только в прошлом месяце.",
  },
  {
    phrase: "I'm still getting used to it.",
    translation: "Я ещё привыкаю.",
    example: "The city is big, I'm still getting used to it.",
    exampleTranslation: "Город большой, я ещё привыкаю.",
  },
  {
    phrase: "I work remotely.",
    translation: "Я работаю удалённо.",
    example: "Most days I work remotely from home.",
    exampleTranslation: "В большинстве дней я работаю удалённо из дома.",
  },
  {
    phrase: "I'm here for work.",
    translation: "Я здесь по работе.",
    example: "I'm here for work for a few months.",
    exampleTranslation: "Я здесь по работе на несколько месяцев.",
  },
  {
    phrase: "I'm learning English.",
    translation: "Я учу английский.",
    example: "I'm learning English, so feel free to correct me.",
    exampleTranslation: "Я учу английский, так что смело поправляй меня.",
  },
  {
    phrase: "I'm originally from Russia.",
    translation: "Я из России.",
    example: "I'm originally from Russia, but I live here now.",
    exampleTranslation: "Я из России, но сейчас живу здесь.",
  },
  {
    phrase: "I don't mind either way.",
    translation: "Мне всё равно / любой вариант ок.",
    example: "Coffee or tea? I don't mind either way.",
    exampleTranslation: "Кофе или чай? Мне всё равно.",
  },
  {
    phrase: "I'm pretty flexible.",
    translation: "Я довольно гибкий в этом.",
    example: "About the time, I'm pretty flexible.",
    exampleTranslation: "По времени я довольно гибкий.",
  },
  {
    phrase: "That's not really my thing.",
    translation: "Это не совсем моё.",
    example: "Clubbing isn't really my thing.",
    exampleTranslation: "Клубы — это не совсем моё.",
  },
  {
    phrase: "I'm more of a morning person.",
    translation: "Я скорее «жаворонок».",
    example: "I'm more of a morning person, so early meetings work for me.",
    exampleTranslation: "Я скорее «жаворонок», так что ранние встречи мне подходят.",
  },

  // Meeting people / small talk
  {
    phrase: "Nice to meet you.",
    translation: "Приятно познакомиться.",
    example: "Nice to meet you, I've heard a lot about you.",
    exampleTranslation: "Приятно познакомиться, много о тебе слышал.",
  },
  {
    phrase: "Have we met before?",
    translation: "Мы раньше встречались?",
    example: "Sorry, have we met before?",
    exampleTranslation: "Извини, мы раньше встречались?",
  },
  {
    phrase: "What brings you here?",
    translation: "Что тебя / вас сюда привело?",
    example: "So what brings you here tonight?",
    exampleTranslation: "Так что привело тебя сюда сегодня вечером?",
  },
  {
    phrase: "How do you know each other?",
    translation: "Как вы знакомы?",
    example: "How do you know each other? Through work?",
    exampleTranslation: "Как вы знакомы? По работе?",
  },
  {
    phrase: "I'd love to stay in touch.",
    translation: "Было бы здорово оставаться на связи.",
    example: "It was great talking — I'd love to stay in touch.",
    exampleTranslation: "Было здорово поговорить — давай останемся на связи.",
  },
  {
    phrase: "Can I get your number?",
    translation: "Можно твой номер?",
    example: "Can I get your number? I'll text you the details.",
    exampleTranslation: "Можно твой номер? Напишу детали в сообщении.",
  },
  {
    phrase: "Sorry, I didn't catch your name.",
    translation: "Извини, не расслышал имя.",
    example: "Sorry, I didn't catch your name. Could you say it again?",
    exampleTranslation: "Извини, не расслышал имя. Можешь повторить?",
  },
  {
    phrase: "What do you do for work?",
    translation: "Чем ты занимаешься / где работаешь?",
    example: "What do you do for work, if you don't mind me asking?",
    exampleTranslation: "Чем ты занимаешься, если не секрет?",
  },
  {
    phrase: "It was great meeting you.",
    translation: "Было здорово с тобой познакомиться.",
    example: "I have to run, but it was great meeting you.",
    exampleTranslation: "Мне пора бежать, но было здорово познакомиться.",
  },
  {
    phrase: "Let's grab a coffee sometime.",
    translation: "Давай как-нибудь выпьем кофе.",
    example: "Let's grab a coffee sometime next week.",
    exampleTranslation: "Давай как-нибудь на следующей неделе выпьем кофе.",
  },

  // This / that / pointing / what needs doing
  {
    phrase: "Is it this one or that one?",
    translation: "Это вот этот или тот?",
    example: "Is it this one or that one on the shelf?",
    exampleTranslation: "Это вот этот или тот на полке?",
  },
  {
    phrase: "Do you mean this or that?",
    translation: "Ты имеешь в виду это или то?",
    example: "Sorry, do you mean this or that?",
    exampleTranslation: "Прости, ты имеешь в виду это или то?",
  },
  {
    phrase: "It's over there.",
    translation: "Оно вон там.",
    example: "The bathroom? It's over there on the left.",
    exampleTranslation: "Туалет? Вон там слева.",
  },
  {
    phrase: "It's right here.",
    translation: "Вот оно / прямо здесь.",
    example: "Looking for your keys? They're right here.",
    exampleTranslation: "Ищешь ключи? Они вот здесь.",
  },
  {
    phrase: "Which one do you need?",
    translation: "Какой тебе нужен?",
    example: "There are two bags — which one do you need?",
    exampleTranslation: "Тут две сумки — какая тебе нужна?",
  },
  {
    phrase: "This one, please.",
    translation: "Вот этот, пожалуйста.",
    example: "This one, please — the blue one.",
    exampleTranslation: "Вот этот, пожалуйста — синий.",
  },
  {
    phrase: "Not that one, the other one.",
    translation: "Не тот, а другой.",
    example: "Not that one, the other one next to it.",
    exampleTranslation: "Не тот, а другой рядом с ним.",
  },
  {
    phrase: "What needs to be done?",
    translation: "Что нужно сделать?",
    example: "Okay, what needs to be done before we leave?",
    exampleTranslation: "Ок, что нужно сделать перед тем, как уйти?",
  },
  {
    phrase: "I'll take care of this.",
    translation: "Я займусь этим.",
    example: "Don't worry about the dishes, I'll take care of this.",
    exampleTranslation: "Не переживай из-за посуды, я займусь этим.",
  },
  {
    phrase: "Can you handle that?",
    translation: "Можешь этим заняться?",
    example: "I need to run — can you handle that?",
    exampleTranslation: "Мне надо бежать — можешь этим заняться?",
  },
  {
    phrase: "Put it over there.",
    translation: "Поставь / положи вон туда.",
    example: "Put it over there by the door.",
    exampleTranslation: "Поставь вон туда у двери.",
  },
  {
    phrase: "Bring it over here.",
    translation: "Принеси сюда.",
    example: "Bring it over here so I can take a look.",
    exampleTranslation: "Принеси сюда, я посмотрю.",
  },
  {
    phrase: "That's the one.",
    translation: "Вот именно этот / то самое.",
    example: "Yes, that's the one I was talking about.",
    exampleTranslation: "Да, вот именно тот, о котором я говорил.",
  },
  {
    phrase: "We're all set.",
    translation: "Мы готовы / всё сделано.",
    example: "Bags packed, tickets ready — we're all set.",
    exampleTranslation: "Сумки собраны, билеты на месте — мы готовы.",
  },
  {
    phrase: "What's left to do?",
    translation: "Что ещё осталось сделать?",
    example: "We've packed most things. What's left to do?",
    exampleTranslation: "Большую часть собрали. Что ещё осталось?",
  },

  // Directions / getting around
  {
    phrase: "How do I get there?",
    translation: "Как туда добраться?",
    example: "How do I get there from the station?",
    exampleTranslation: "Как туда добраться от станции?",
  },
  {
    phrase: "Is it within walking distance?",
    translation: "Это в пешей доступности?",
    example: "Is the cafe within walking distance?",
    exampleTranslation: "Кафе в пешей доступности?",
  },
  {
    phrase: "I'm a bit lost.",
    translation: "Я немного заблудился.",
    example: "Excuse me, I'm a bit lost. Is this the way to the park?",
    exampleTranslation: "Извините, я немного заблудился. Это путь к парку?",
  },
  {
    phrase: "Could you point me in the right direction?",
    translation: "Не подскажете, куда идти?",
    example: "Could you point me in the right direction for the metro?",
    exampleTranslation: "Не подскажете, как пройти к метро?",
  },
  {
    phrase: "Is this the right stop?",
    translation: "Это нужная остановка?",
    example: "Excuse me, is this the right stop for downtown?",
    exampleTranslation: "Извините, это нужная остановка до центра?",
  },
  {
    phrase: "I'll meet you there.",
    translation: "Встретимся там.",
    example: "I can't pick you up, I'll meet you there.",
    exampleTranslation: "Не смогу заехать за тобой, встретимся там.",
  },
  {
    phrase: "I'm almost there.",
    translation: "Я почти на месте.",
    example: "I'm almost there, five more minutes.",
    exampleTranslation: "Я почти на месте, ещё минут пять.",
  },
  {
    phrase: "Where should we meet?",
    translation: "Где встретимся?",
    example: "Where should we meet — at the entrance or inside?",
    exampleTranslation: "Где встретимся — у входа или внутри?",
  },

  // Cafe / restaurant / ordering
  {
    phrase: "Could I get a menu, please?",
    translation: "Можно меню, пожалуйста?",
    example: "Hi, could I get a menu, please?",
    exampleTranslation: "Здравствуйте, можно меню, пожалуйста?",
  },
  {
    phrase: "I'll have the same.",
    translation: "Мне то же самое.",
    example: "That looks good — I'll have the same.",
    exampleTranslation: "Выглядит вкусно — мне то же самое.",
  },
  {
    phrase: "Could we get the check?",
    translation: "Можно счёт?",
    example: "We're ready to go — could we get the check?",
    exampleTranslation: "Мы готовы идти — можно счёт?",
  },
  {
    phrase: "Is this seat taken?",
    translation: "Это место занято?",
    example: "Excuse me, is this seat taken?",
    exampleTranslation: "Извините, это место занято?",
  },
  {
    phrase: "For here or to go?",
    translation: "Здесь или с собой?",
    example: "For here or to go? To go, please.",
    exampleTranslation: "Здесь или с собой? С собой, пожалуйста.",
  },
  {
    phrase: "I'm allergic to nuts.",
    translation: "У меня аллергия на орехи.",
    example: "Just so you know, I'm allergic to nuts.",
    exampleTranslation: "Просто чтобы вы знали: у меня аллергия на орехи.",
  },
  {
    phrase: "Could you make it less spicy?",
    translation: "Можно менее острым?",
    example: "Could you make it less spicy, please?",
    exampleTranslation: "Можно менее острым, пожалуйста?",
  },

  // Shopping / payments
  {
    phrase: "Do you take card?",
    translation: "Картой можно?",
    example: "Do you take card, or is it cash only?",
    exampleTranslation: "Картой можно, или только наличные?",
  },
  {
    phrase: "Do you have this in a different size?",
    translation: "Есть это в другом размере?",
    example: "Do you have this in a different size? Medium, maybe?",
    exampleTranslation: "Есть это в другом размере? Может, medium?",
  },
  {
    phrase: "I'm just looking, thanks.",
    translation: "Я просто смотрю, спасибо.",
    example: "Need help? I'm just looking, thanks.",
    exampleTranslation: "Помочь? Я просто смотрю, спасибо.",
  },
  {
    phrase: "Where can I find...?",
    translation: "Где найти...?",
    example: "Excuse me, where can I find toothpaste?",
    exampleTranslation: "Извините, где найти зубную пасту?",
  },
  {
    phrase: "Can I return this?",
    translation: "Можно это вернуть?",
    example: "Can I return this if it doesn't fit?",
    exampleTranslation: "Можно это вернуть, если не подойдёт?",
  },
  {
    phrase: "I paid already.",
    translation: "Я уже заплатил.",
    example: "It's okay, I paid already.",
    exampleTranslation: "Всё нормально, я уже заплатил.",
  },
  {
    phrase: "Can we split the bill?",
    translation: "Можем разделить счёт?",
    example: "Can we split the bill fifty-fifty?",
    exampleTranslation: "Можем разделить счёт пополам?",
  },

  // Appointments / services / phone
  {
    phrase: "I'd like to make an appointment.",
    translation: "Хочу записаться.",
    example: "I'd like to make an appointment for Thursday.",
    exampleTranslation: "Хочу записаться на четверг.",
  },
  {
    phrase: "Can we reschedule?",
    translation: "Можем перенести?",
    example: "Something came up — can we reschedule?",
    exampleTranslation: "Всплыло дело — можем перенести?",
  },
  {
    phrase: "I'm calling about my order.",
    translation: "Звоню по поводу своего заказа.",
    example: "Hi, I'm calling about my order from yesterday.",
    exampleTranslation: "Здравствуйте, звоню по поводу вчерашнего заказа.",
  },
  {
    phrase: "Can you hear me okay?",
    translation: "Меня нормально слышно?",
    example: "The connection is bad — can you hear me okay?",
    exampleTranslation: "Связь плохая — меня нормально слышно?",
  },
  {
    phrase: "I'll text you the address.",
    translation: "Скину адрес в сообщении.",
    example: "I don't remember the street name, I'll text you the address.",
    exampleTranslation: "Не помню название улицы, скину адрес в сообщении.",
  },
  {
    phrase: "Did you get my message?",
    translation: "Ты получил моё сообщение?",
    example: "Did you get my message about tomorrow?",
    exampleTranslation: "Ты получил моё сообщение про завтра?",
  },
  {
    phrase: "Sorry, I missed your call.",
    translation: "Извини, пропустил твой звонок.",
    example: "Sorry, I missed your call — what's up?",
    exampleTranslation: "Извини, пропустил звонок — что случилось?",
  },

  // Home / neighbors / daily chores
  {
    phrase: "The Wi-Fi isn't working.",
    translation: "Вайфай не работает.",
    example: "The Wi-Fi isn't working — can you check the router?",
    exampleTranslation: "Вайфай не работает — можешь проверить роутер?",
  },
  {
    phrase: "What's the Wi-Fi password?",
    translation: "Какой пароль от вайфая?",
    example: "What's the Wi-Fi password? I need to send a file.",
    exampleTranslation: "Какой пароль от вайфая? Нужно отправить файл.",
  },
  {
    phrase: "Is the trash day today?",
    translation: "Сегодня день выноса мусора?",
    example: "Is the trash day today or tomorrow?",
    exampleTranslation: "Сегодня день выноса мусора или завтра?",
  },
  {
    phrase: "I'll take the trash out.",
    translation: "Я вынесу мусор.",
    example: "Don't worry, I'll take the trash out.",
    exampleTranslation: "Не переживай, я вынесу мусор.",
  },
  {
    phrase: "Something's wrong with the sink.",
    translation: "С раковиной что-то не так.",
    example: "Something's wrong with the sink — it's not draining.",
    exampleTranslation: "С раковиной что-то не так — вода не уходит.",
  },
  {
    phrase: "Do you have a spare key?",
    translation: "Есть запасной ключ?",
    example: "I locked myself out. Do you have a spare key?",
    exampleTranslation: "Я заперся снаружи. Есть запасной ключ?",
  },

  // Asking for help / clarifying
  {
    phrase: "Could you help me with this?",
    translation: "Можешь помочь с этим?",
    example: "Could you help me with this bag? It's heavy.",
    exampleTranslation: "Можешь помочь с этой сумкой? Она тяжёлая.",
  },
  {
    phrase: "What does that mean?",
    translation: "Что это значит?",
    example: "Sorry, what does that mean?",
    exampleTranslation: "Прости, что это значит?",
  },
  {
    phrase: "Could you say that again?",
    translation: "Можешь повторить?",
    example: "It was a bit loud — could you say that again?",
    exampleTranslation: "Было шумно — можешь повторить?",
  },
  {
    phrase: "Could you slow down a bit?",
    translation: "Можешь чуть помедленнее?",
    example: "I'm still learning — could you slow down a bit?",
    exampleTranslation: "Я ещё учусь — можешь чуть помедленнее?",
  },
  {
    phrase: "I didn't quite get that.",
    translation: "Я не совсем понял.",
    example: "Sorry, I didn't quite get that. One more time?",
    exampleTranslation: "Прости, я не совсем понял. Ещё раз?",
  },
  {
    phrase: "In other words...?",
    translation: "Другими словами...?",
    example: "In other words, we need to leave by five?",
    exampleTranslation: "Другими словами, нам нужно уйти к пяти?",
  },
  {
    phrase: "Just to confirm...",
    translation: "Просто чтобы уточнить...",
    example: "Just to confirm, we're meeting at seven, right?",
    exampleTranslation: "Просто чтобы уточнить: встречаемся в семь, верно?",
  },

  // Plans / time / weather daily
  {
    phrase: "What are you up to today?",
    translation: "Какие планы на сегодня?",
    example: "Hey, what are you up to today?",
    exampleTranslation: "Эй, какие планы на сегодня?",
  },
  {
    phrase: "I'm free after six.",
    translation: "Я свободен после шести.",
    example: "I'm free after six if that works for you.",
    exampleTranslation: "Я свободен после шести, если тебе удобно.",
  },
  {
    phrase: "Does that work for you?",
    translation: "Тебе так удобно?",
    example: "How about Saturday at noon — does that work for you?",
    exampleTranslation: "Как насчёт субботы в полдень — тебе так удобно?",
  },
  {
    phrase: "I'll be there in ten.",
    translation: "Буду через десять минут.",
    example: "Traffic is light, I'll be there in ten.",
    exampleTranslation: "Пробки небольшие, буду через десять.",
  },
  {
    phrase: "It looks like rain.",
    translation: "Похоже, будет дождь.",
    example: "It looks like rain — grab an umbrella.",
    exampleTranslation: "Похоже, будет дождь — возьми зонт.",
  },
  {
    phrase: "It's getting late.",
    translation: "Уже поздно становится.",
    example: "It's getting late, I should head home.",
    exampleTranslation: "Уже поздно, мне пора домой.",
  },
  {
    phrase: "I should get going.",
    translation: "Мне пора идти.",
    example: "I should get going if I want to catch the bus.",
    exampleTranslation: "Мне пора идти, если хочу успеть на автобус.",
  },

  // Politeness / soft conflicts
  {
    phrase: "No rush.",
    translation: "Не торопись.",
    example: "Take your time, no rush.",
    exampleTranslation: "Не торопись, времени достаточно.",
  },
  {
    phrase: "After you.",
    translation: "После вас / проходите.",
    example: "After you — go ahead.",
    exampleTranslation: "После вас — проходите.",
  },
  {
    phrase: "I think there's been a mistake.",
    translation: "Кажется, произошла ошибка.",
    example: "I think there's been a mistake with my order.",
    exampleTranslation: "Кажется, ошибка с моим заказом.",
  },
  {
    phrase: "That's not what I ordered.",
    translation: "Это не то, что я заказывал.",
    example: "Excuse me, that's not what I ordered.",
    exampleTranslation: "Извините, это не то, что я заказывал.",
  },
  {
    phrase: "I'd rather not.",
    translation: "Лучше не надо / я бы предпочёл не.",
    example: "Want to stay out late? I'd rather not.",
    exampleTranslation: "Хочешь задержаться допоздна? Лучше не надо.",
  },
  {
    phrase: "Let's leave it for now.",
    translation: "Давай пока оставим это.",
    example: "We're both tired — let's leave it for now.",
    exampleTranslation: "Мы оба устали — давай пока оставим это.",
  },
  {
    phrase: "Thanks for letting me know.",
    translation: "Спасибо, что сказал.",
    example: "Thanks for letting me know about the delay.",
    exampleTranslation: "Спасибо, что сказал про задержку.",
  },
  {
    phrase: "I appreciate your patience.",
    translation: "Спасибо за терпение.",
    example: "Sorry for the wait — I appreciate your patience.",
    exampleTranslation: "Извините за ожидание — спасибо за терпение.",
  },
  {
    phrase: "Is everything okay?",
    translation: "Всё в порядке?",
    example: "You look worried — is everything okay?",
    exampleTranslation: "Ты выглядишь обеспокоенным — всё в порядке?",
  },
  {
    phrase: "Let me know if you need anything.",
    translation: "Дай знать, если что-то понадобится.",
    example: "I'm around all day — let me know if you need anything.",
    exampleTranslation: "Я весь день рядом — дай знать, если что-то понадобится.",
  },

  // Simple beginner phrases
  {
    phrase: "Excuse me, can you help me?",
    translation: "Извините, вы можете мне помочь?",
    example: "Excuse me, can you help me? I'm looking for the station.",
    exampleTranslation: "Извините, вы можете мне помочь? Я ищу станцию.",
  },
  {
    phrase: "Sorry, I don't understand.",
    translation: "Извините, я не понимаю.",
    example: "Sorry, I don't understand. Can you say it again?",
    exampleTranslation: "Извините, я не понимаю. Можете повторить?",
  },
  {
    phrase: "Can you repeat that, please?",
    translation: "Можете повторить, пожалуйста?",
    example: "Can you repeat that, please? I didn't hear you.",
    exampleTranslation: "Можете повторить, пожалуйста? Я не расслышал.",
  },
  {
    phrase: "How much is this?",
    translation: "Сколько это стоит?",
    example: "Excuse me, how much is this?",
    exampleTranslation: "Извините, сколько это стоит?",
  },
  {
    phrase: "Where is the bathroom?",
    translation: "Где туалет?",
    example: "Excuse me, where is the bathroom?",
    exampleTranslation: "Извините, где туалет?",
  },
  {
    phrase: "I'd like this, please.",
    translation: "Мне вот это, пожалуйста.",
    example: "I'd like this, please. And a bottle of water.",
    exampleTranslation: "Мне вот это, пожалуйста. И бутылку воды.",
  },
  {
    phrase: "Thank you so much.",
    translation: "Большое спасибо.",
    example: "Thank you so much for your help.",
    exampleTranslation: "Большое спасибо за помощь.",
  },
  {
    phrase: "You're welcome.",
    translation: "Пожалуйста / не за что.",
    example: "Thank you! You're welcome.",
    exampleTranslation: "Спасибо! Не за что.",
  },
  {
    phrase: "Sorry I'm late.",
    translation: "Извините, что опоздал.",
    example: "Sorry I'm late. The bus was slow.",
    exampleTranslation: "Извините, что опоздал. Автобус ехал медленно.",
  },
  {
    phrase: "Can I sit here?",
    translation: "Можно здесь сесть?",
    example: "Excuse me, can I sit here?",
    exampleTranslation: "Извините, можно здесь сесть?",
  },
  {
    phrase: "I need a bag, please.",
    translation: "Мне нужен пакет, пожалуйста.",
    example: "I need a bag, please. A small one is fine.",
    exampleTranslation: "Мне нужен пакет, пожалуйста. Маленький подойдёт.",
  },
  {
    phrase: "Do you speak English?",
    translation: "Вы говорите по-английски?",
    example: "Excuse me, do you speak English?",
    exampleTranslation: "Извините, вы говорите по-английски?",
  },
  {
    phrase: "I only speak a little English.",
    translation: "Я говорю по-английски совсем немного.",
    example: "I only speak a little English. Please speak slowly.",
    exampleTranslation: "Я говорю по-английски совсем немного. Говорите, пожалуйста, медленно.",
  },
  {
    phrase: "Please speak slowly.",
    translation: "Говорите, пожалуйста, медленно.",
    example: "Please speak slowly. I'm still learning.",
    exampleTranslation: "Говорите, пожалуйста, медленно. Я ещё учусь.",
  },
  {
    phrase: "What time is it?",
    translation: "Который час?",
    example: "Excuse me, what time is it?",
    exampleTranslation: "Извините, который час?",
  },
  {
    phrase: "Where is the nearest metro?",
    translation: "Где ближайшее метро?",
    example: "Excuse me, where is the nearest metro?",
    exampleTranslation: "Извините, где ближайшее метро?",
  },
  {
    phrase: "I'm looking for this address.",
    translation: "Я ищу этот адрес.",
    example: "I'm looking for this address. Can you help me?",
    exampleTranslation: "Я ищу этот адрес. Вы можете помочь?",
  },
  {
    phrase: "Is it far from here?",
    translation: "Это далеко отсюда?",
    example: "Is it far from here? Or can I walk?",
    exampleTranslation: "Это далеко отсюда? Или можно дойти пешком?",
  },
  {
    phrase: "Turn left here.",
    translation: "Поверните здесь налево.",
    example: "Turn left here, then go straight.",
    exampleTranslation: "Поверните здесь налево, потом идите прямо.",
  },
  {
    phrase: "Go straight ahead.",
    translation: "Идите прямо.",
    example: "Go straight ahead for two blocks.",
    exampleTranslation: "Идите прямо два квартала.",
  },
  {
    phrase: "A table for two, please.",
    translation: "Столик на двоих, пожалуйста.",
    example: "Hi, a table for two, please.",
    exampleTranslation: "Здравствуйте, столик на двоих, пожалуйста.",
  },
  {
    phrase: "Water, please.",
    translation: "Воды, пожалуйста.",
    example: "Water, please. No ice.",
    exampleTranslation: "Воды, пожалуйста. Без льда.",
  },
  {
    phrase: "The bill, please.",
    translation: "Счёт, пожалуйста.",
    example: "The bill, please. Thank you.",
    exampleTranslation: "Счёт, пожалуйста. Спасибо.",
  },
  {
    phrase: "Can I pay by card?",
    translation: "Можно оплатить картой?",
    example: "Can I pay by card, please?",
    exampleTranslation: "Можно оплатить картой, пожалуйста?",
  },
  {
    phrase: "I don't need a receipt.",
    translation: "Чек не нужен.",
    example: "I don't need a receipt, thanks.",
    exampleTranslation: "Чек не нужен, спасибо.",
  },
  {
    phrase: "Can I have a receipt, please?",
    translation: "Можно чек, пожалуйста?",
    example: "Can I have a receipt, please? For work.",
    exampleTranslation: "Можно чек, пожалуйста? Для работы.",
  },
  {
    phrase: "Open or closed?",
    translation: "Открыто или закрыто?",
    example: "Excuse me — open or closed?",
    exampleTranslation: "Извините — открыто или закрыто?",
  },
  {
    phrase: "What time do you close?",
    translation: "Во сколько вы закрываетесь?",
    example: "What time do you close today?",
    exampleTranslation: "Во сколько вы закрываетесь сегодня?",
  },
  {
    phrase: "I'm waiting for someone.",
    translation: "Я кого-то жду.",
    example: "I'm waiting for someone. Is it okay if I sit here?",
    exampleTranslation: "Я кого-то жду. Можно здесь посидеть?",
  },
  {
    phrase: "My name is...",
    translation: "Меня зовут...",
    example: "Hi, my name is Den. Nice to meet you.",
    exampleTranslation: "Привет, меня зовут Den. Приятно познакомиться.",
  },
  {
    phrase: "Nice to see you.",
    translation: "Рад тебя видеть.",
    example: "Nice to see you again!",
    exampleTranslation: "Рад снова тебя видеть!",
  },
  {
    phrase: "How are you?",
    translation: "Как дела?",
    example: "Hi! How are you?",
    exampleTranslation: "Привет! Как дела?",
  },
  {
    phrase: "I'm fine, thanks.",
    translation: "Нормально, спасибо.",
    example: "I'm fine, thanks. And you?",
    exampleTranslation: "Нормально, спасибо. А ты?",
  },
  {
    phrase: "And you?",
    translation: "А ты / а вы?",
    example: "I'm good, thanks. And you?",
    exampleTranslation: "У меня хорошо, спасибо. А у тебя?",
  },
  {
    phrase: "See you later.",
    translation: "Увидимся позже.",
    example: "I have to go. See you later!",
    exampleTranslation: "Мне пора. Увидимся позже!",
  },
  {
    phrase: "Have a nice day.",
    translation: "Хорошего дня.",
    example: "Thanks for your help. Have a nice day!",
    exampleTranslation: "Спасибо за помощь. Хорошего дня!",
  },
  {
    phrase: "I live near here.",
    translation: "Я живу рядом.",
    example: "I live near here, so I walk a lot.",
    exampleTranslation: "Я живу рядом, поэтому часто хожу пешком.",
  },
  {
    phrase: "I work nearby.",
    translation: "Я работаю рядом.",
    example: "I work nearby, just five minutes away.",
    exampleTranslation: "Я работаю рядом, всего в пяти минутах.",
  },
  {
    phrase: "This is for me.",
    translation: "Это мне.",
    example: "This is for me. Thank you.",
    exampleTranslation: "Это мне. Спасибо.",
  },
  {
    phrase: "That's not mine.",
    translation: "Это не моё.",
    example: "That's not mine. Mine is the blue one.",
    exampleTranslation: "Это не моё. Моё — синее.",
  },
  {
    phrase: "Is this yours?",
    translation: "Это ваше / твоё?",
    example: "Excuse me, is this yours?",
    exampleTranslation: "Извините, это ваше?",
  },
  {
    phrase: "I need this one.",
    translation: "Мне нужен вот этот.",
    example: "I need this one, please. Not that one.",
    exampleTranslation: "Мне нужен вот этот, пожалуйста. Не тот.",
  },
  {
    phrase: "Over there, please.",
    translation: "Вон туда, пожалуйста.",
    example: "You can leave it over there, please.",
    exampleTranslation: "Можете оставить вон там, пожалуйста.",
  },
  {
    phrase: "Here you go.",
    translation: "Вот, пожалуйста.",
    example: "Here you go. Have a nice day!",
    exampleTranslation: "Вот, пожалуйста. Хорошего дня!",
  },
  {
    phrase: "One moment, please.",
    translation: "Одну минуту, пожалуйста.",
    example: "One moment, please. I'm almost ready.",
    exampleTranslation: "Одну минуту, пожалуйста. Я почти готов.",
  },
  {
    phrase: "Just a second.",
    translation: "Секунду.",
    example: "Just a second, let me check.",
    exampleTranslation: "Секунду, сейчас проверю.",
  },
  {
    phrase: "I think so.",
    translation: "Думаю, да.",
    example: "Is this the right street? I think so.",
    exampleTranslation: "Это та улица? Думаю, да.",
  },
  {
    phrase: "I don't think so.",
    translation: "Думаю, нет.",
    example: "Is the store open now? I don't think so.",
    exampleTranslation: "Магазин сейчас открыт? Думаю, нет.",
  },
  {
    phrase: "Maybe later.",
    translation: "Может, позже.",
    example: "Do you want coffee now? Maybe later.",
    exampleTranslation: "Хочешь кофе сейчас? Может, позже.",
  },
  {
    phrase: "Sounds good.",
    translation: "Звучит хорошо.",
    example: "Let's meet at five. Sounds good.",
    exampleTranslation: "Давай встретимся в пять. Звучит хорошо.",
  },
  {
    phrase: "No problem.",
    translation: "Без проблем.",
    example: "Thanks for waiting. No problem!",
    exampleTranslation: "Спасибо, что подождал. Без проблем!",
  },
  {
    phrase: "I got it.",
    translation: "Понял / ясно.",
    example: "Turn left, then right. Okay, I got it.",
    exampleTranslation: "Налево, потом направо. Ок, понял.",
  },
  {
    phrase: "Same for me.",
    translation: "Мне то же самое.",
    example: "I'll have coffee. Same for me, please.",
    exampleTranslation: "Мне кофе. Мне то же самое, пожалуйста.",
  },
  {
    phrase: "Can you show me?",
    translation: "Можете показать?",
    example: "Can you show me on the map?",
    exampleTranslation: "Можете показать на карте?",
  },
  {
    phrase: "I need help with this.",
    translation: "Мне нужна помощь с этим.",
    example: "Excuse me, I need help with this form.",
    exampleTranslation: "Извините, мне нужна помощь с этой формой.",
  },
  {
    phrase: "Where can I buy water?",
    translation: "Где можно купить воду?",
    example: "Excuse me, where can I buy water?",
    exampleTranslation: "Извините, где можно купить воду?",
  },
  {
    phrase: "Is there Wi-Fi here?",
    translation: "Здесь есть вайфай?",
    example: "Is there Wi-Fi here? What's the password?",
    exampleTranslation: "Здесь есть вайфай? Какой пароль?",
  },
  {
    phrase: "The elevator isn't working.",
    translation: "Лифт не работает.",
    example: "The elevator isn't working. Use the stairs.",
    exampleTranslation: "Лифт не работает. Идите по лестнице.",
  },
  {
    phrase: "Which floor?",
    translation: "Какой этаж?",
    example: "Which floor? Third floor, please.",
    exampleTranslation: "Какой этаж? Третий, пожалуйста.",
  },

  // Personal trainer / gym intro
  {
    phrase: "Hi, my name is Daniil. I'm your personal trainer.",
    translation: "Привет, меня зовут Даниил. Я твой персональный тренер.",
    example: "Hi, my name is Daniil. I'm your personal trainer. Nice to meet you.",
    exampleTranslation: "Привет, меня зовут Даниил. Я твой персональный тренер. Приятно познакомиться.",
  },
  {
    phrase: "How should I address you — informally or formally?",
    translation: "Как я могу к тебе обращаться — на «ты» или на «вы»?",
    example: "How should I address you — informally or formally? Whatever you're comfortable with.",
    exampleTranslation: "Как к тебе обращаться — на «ты» или на «вы»? Как тебе удобнее.",
  },
  {
    phrase: "Let's get to know each other.",
    translation: "Давай приступим к знакомству.",
    example: "Before we start, let's get to know each other a bit.",
    exampleTranslation: "Перед началом давай немного познакомимся.",
  },
  {
    phrase: "Could you tell me about any health issues or limitations?",
    translation: "Подскажите, пожалуйста, есть ли особенности организма?",
    example: "Could you tell me about any health issues or limitations before we train?",
    exampleTranslation: "Подскажите, пожалуйста, есть ли особенности организма перед тренировкой?",
  },
  {
    phrase: "By that I mean past injuries, joint or back pain, or anything that bothers you in daily life.",
    translation: "Под особенностями я понимаю перенесённые травмы, боль в суставах или спине, либо что-то, что беспокоит в быту.",
    example: "By that I mean past injuries, joint or back pain, or anything that bothers you in daily life.",
    exampleTranslation: "Под этим я имею в виду прошлые травмы, боль в суставах или спине, либо то, что беспокоит в быту.",
  },
  {
    phrase: "Do you have any past injuries I should know about?",
    translation: "Есть ли перенесённые травмы, о которых мне стоит знать?",
    example: "Do you have any past injuries I should know about before we start?",
    exampleTranslation: "Есть ли перенесённые травмы, о которых мне стоит знать перед началом?",
  },
  {
    phrase: "Do you have any joint or back pain?",
    translation: "Есть ли боль в суставах или спине?",
    example: "Do you have any joint or back pain right now?",
    exampleTranslation: "Есть ли сейчас боль в суставах или спине?",
  },
  {
    phrase: "Is there anything that bothers you in everyday life?",
    translation: "Есть ли что-то, что беспокоит в бытовой жизни?",
    example: "Is there anything that bothers you in everyday life — stairs, sitting, lifting?",
    exampleTranslation: "Есть ли что-то, что беспокоит в быту — лестницы, сидение, подъём тяжестей?",
  },
  {
    phrase: "We'll start with a cardio warm-up to prepare your cardiovascular system.",
    translation: "Начнём с кардио-разминки, чтобы подготовить сердечно-сосудистую систему.",
    example: "We'll start with a cardio warm-up to prepare your cardiovascular system.",
    exampleTranslation: "Начнём с кардио-разминки, чтобы подготовить сердечно-сосудистую систему.",
  },
  {
    phrase: "Then we'll do a warm-up, and after that we'll start the workout.",
    translation: "Далее сделаем разминку, и после этого приступим к тренировке.",
    example: "Then we'll do a warm-up, and after that we'll start the workout.",
    exampleTranslation: "Потом сделаем разминку, и после этого приступим к тренировке.",
  },
  {
    phrase: "What would you like to focus on in the workout?",
    translation: "На что хотелось бы поставить акцент в тренировке?",
    example: "What would you like to focus on in the workout — strength, posture, or fat loss?",
    exampleTranslation: "На что хотелось бы поставить акцент — сила, осанка или жиросжигание?",
  },
  {
    phrase: "Have you worked with a trainer in a gym before?",
    translation: "Был ли опыт занятий с тренером в зале?",
    example: "Have you worked with a trainer in a gym before, or is this your first time?",
    exampleTranslation: "Был ли опыт занятий с тренером в зале, или это в первый раз?",
  },
  {
    phrase: "Have you done any sports before, and for how long?",
    translation: "Занимались ли спортом раньше и сколько по времени?",
    example: "Have you done any sports before, and for how long?",
    exampleTranslation: "Занимались ли спортом раньше и сколько по времени?",
  },
  {
    phrase: "Today we'll do a full-body workout — that's a session for all muscle groups.",
    translation: "Сегодня сделаем тренировку фулбоди — это тренировка на все группы мышц.",
    example: "Today we'll do a full-body workout — that's a session for all muscle groups.",
    exampleTranslation: "Сегодня сделаем фулбоди — тренировку на все группы мышц.",
  },
  {
    phrase: "I need to see your movement skills and what your body can do.",
    translation: "Мне нужно посмотреть на твои двигательные навыки и возможности организма.",
    example: "I need to see your movement skills in the exercises and what your body can do.",
    exampleTranslation: "Мне нужно посмотреть на твои двигательные навыки в упражнениях и возможности организма.",
  },
  {
    phrase: "How are you feeling today?",
    translation: "Как ты себя сегодня чувствуешь?",
    example: "How are you feeling today? Any tiredness or soreness?",
    exampleTranslation: "Как ты себя сегодня чувствуешь? Есть усталость или крепатура?",
  },
  {
    phrase: "If anything hurts, tell me right away.",
    translation: "Если что-то заболит — сразу скажи.",
    example: "If anything hurts, tell me right away and we'll stop or change the exercise.",
    exampleTranslation: "Если что-то заболит — сразу скажи, остановимся или поменяем упражнение.",
  },
  {
    phrase: "We'll keep the weight light for now.",
    translation: "Пока возьмём небольшой вес.",
    example: "We'll keep the weight light for now so I can check your form.",
    exampleTranslation: "Пока возьмём небольшой вес, чтобы я проверил технику.",
  },
  {
    phrase: "Focus on your form, not on the weight.",
    translation: "Смотри на технику, а не на вес.",
    example: "Focus on your form, not on the weight. Slow and controlled.",
    exampleTranslation: "Смотри на технику, а не на вес. Медленно и под контролем.",
  },
  {
    phrase: "Breathe out on the effort.",
    translation: "На усилии выдыхай.",
    example: "Breathe out on the effort, and breathe in on the way down.",
    exampleTranslation: "На усилии выдыхай, а на опускании вдыхай.",
  },
  {
    phrase: "How does that feel?",
    translation: "Как ощущения?",
    example: "How does that feel? Too easy, okay, or too hard?",
    exampleTranslation: "Как ощущения? Слишком легко, нормально или тяжело?",
  },
  {
    phrase: "Can you do two more reps?",
    translation: "Сделаешь ещё два повторения?",
    example: "Can you do two more reps with good form?",
    exampleTranslation: "Сделаешь ещё два повторения с хорошей техникой?",
  },
  {
    phrase: "Take a short rest, about a minute.",
    translation: "Отдохни немного, около минуты.",
    example: "Take a short rest, about a minute, then we'll do the next set.",
    exampleTranslation: "Отдохни около минуты, потом сделаем следующий подход.",
  },
  {
    phrase: "Keep your back straight.",
    translation: "Держи спину ровно.",
    example: "Keep your back straight and your core tight.",
    exampleTranslation: "Держи спину ровно и напряги корпус.",
  },
  {
    phrase: "Don't rush — slow and controlled.",
    translation: "Не торопись — медленно и под контролем.",
    example: "Don't rush — slow and controlled on the way down.",
    exampleTranslation: "Не торопись — медленно и под контролем на опускании.",
  },
  {
    phrase: "Great job today.",
    translation: "Отлично поработал сегодня.",
    example: "Great job today. You moved well for the first session.",
    exampleTranslation: "Отлично поработал сегодня. Для первой тренировки двигался хорошо.",
  },
  {
    phrase: "Next time we'll build on this.",
    translation: "В следующий раз продолжим от этого.",
    example: "Next time we'll build on this and add a bit more load.",
    exampleTranslation: "В следующий раз продолжим от этого и немного добавим нагрузку.",
  },
  {
    phrase: "Drink some water.",
    translation: "Выпей воды.",
    example: "Drink some water before we move on.",
    exampleTranslation: "Выпей воды, прежде чем идём дальше.",
  },
  {
    phrase: "Any questions before we start?",
    translation: "Есть вопросы перед началом?",
    example: "Any questions before we start the warm-up?",
    exampleTranslation: "Есть вопросы перед разминкой?",
  },
  {
    phrase: "You can say «you» with me — that's fine.",
    translation: "Можешь обращаться ко мне на «ты» — всё ок.",
    example: "You can say «you» with me — that's fine, keep it casual.",
    exampleTranslation: "Можешь обращаться на «ты» — всё ок, давай без официоза.",
  },

  // Trainer talking to a student / client
  {
    phrase: "What's your name?",
    translation: "Как тебя зовут?",
    example: "Hi! What's your name?",
    exampleTranslation: "Привет! Как тебя зовут?",
  },
  {
    phrase: "Nice to meet you. What should I call you?",
    translation: "Приятно познакомиться. Как мне к тебе обращаться?",
    example: "Nice to meet you. What should I call you — first name is fine?",
    exampleTranslation: "Приятно познакомиться. Как к тебе обращаться — можно по имени?",
  },
  {
    phrase: "Tell me a bit about yourself.",
    translation: "Расскажи немного о себе.",
    example: "Before we train, tell me a bit about yourself.",
    exampleTranslation: "Перед тренировкой расскажи немного о себе.",
  },
  {
    phrase: "What are your goals?",
    translation: "Какие у тебя цели?",
    example: "What are your goals — strength, weight loss, or just feeling better?",
    exampleTranslation: "Какие у тебя цели — сила, похудение или просто лучше себя чувствовать?",
  },
  {
    phrase: "How often do you want to train?",
    translation: "Как часто хочешь тренироваться?",
    example: "How often do you want to train — two or three times a week?",
    exampleTranslation: "Как часто хочешь тренироваться — два или три раза в неделю?",
  },
  {
    phrase: "We'll go at your pace.",
    translation: "Будем идти в твоём темпе.",
    example: "Don't worry — we'll go at your pace.",
    exampleTranslation: "Не переживай — будем идти в твоём темпе.",
  },
  {
    phrase: "I'm here to help you.",
    translation: "Я здесь, чтобы тебе помочь.",
    example: "If something feels unclear, ask me. I'm here to help you.",
    exampleTranslation: "Если что-то непонятно — спрашивай. Я здесь, чтобы помочь.",
  },
  {
    phrase: "Let me show you first.",
    translation: "Сначала я тебе покажу.",
    example: "Let me show you first, then you try.",
    exampleTranslation: "Сначала я покажу, потом ты попробуешь.",
  },
  {
    phrase: "Copy what I do.",
    translation: "Повторяй за мной.",
    example: "Watch me and copy what I do.",
    exampleTranslation: "Смотри на меня и повторяй за мной.",
  },
  {
    phrase: "Show me how you squat.",
    translation: "Покажи, как ты приседаешь.",
    example: "Show me how you squat — no weight yet.",
    exampleTranslation: "Покажи, как ты приседаешь — пока без веса.",
  },
  {
    phrase: "Let's try this together.",
    translation: "Давай попробуем это вместе.",
    example: "Let's try this together, nice and slow.",
    exampleTranslation: "Давай попробуем вместе, спокойно и медленно.",
  },
  {
    phrase: "Are you okay to continue?",
    translation: "Нормально продолжать?",
    example: "Take a breath — are you okay to continue?",
    exampleTranslation: "Переведи дыхание — нормально продолжать?",
  },
  {
    phrase: "We'll skip this exercise today.",
    translation: "Это упражнение сегодня пропустим.",
    example: "If your knee bothers you, we'll skip this exercise today.",
    exampleTranslation: "Если колено беспокоит — это упражнение сегодня пропустим.",
  },
  {
    phrase: "Tell me if this is too hard.",
    translation: "Скажи, если будет слишком тяжело.",
    example: "Tell me if this is too hard, and we'll make it easier.",
    exampleTranslation: "Скажи, если будет слишком тяжело — упростим.",
  },
  {
    phrase: "Push through your heels.",
    translation: "Дави пятками.",
    example: "When you stand up, push through your heels.",
    exampleTranslation: "Когда встаёшь — дави пятками.",
  },
  {
    phrase: "Squeeze your glutes at the top.",
    translation: "Вверху сожми ягодицы.",
    example: "Stand tall and squeeze your glutes at the top.",
    exampleTranslation: "Выпрямись и вверху сожми ягодицы.",
  },
  {
    phrase: "Relax your shoulders.",
    translation: "Расслабь плечи.",
    example: "Relax your shoulders — don't pull them up to your ears.",
    exampleTranslation: "Расслабь плечи — не поднимай их к ушам.",
  },
  {
    phrase: "Look straight ahead.",
    translation: "Смотри прямо перед собой.",
    example: "Look straight ahead, not down at the floor.",
    exampleTranslation: "Смотри прямо, не в пол.",
  },
  {
    phrase: "One more set.",
    translation: "Ещё один подход.",
    example: "One more set, then we rest.",
    exampleTranslation: "Ещё один подход, потом отдых.",
  },
  {
    phrase: "That's enough for today.",
    translation: "На сегодня достаточно.",
    example: "Good work — that's enough for today.",
    exampleTranslation: "Хорошая работа — на сегодня достаточно.",
  },
  {
    phrase: "How was the workout for you?",
    translation: "Как тебе тренировка?",
    example: "How was the workout for you — hard, okay, or easy?",
    exampleTranslation: "Как тебе тренировка — тяжело, нормально или легко?",
  },
  {
    phrase: "See you at the next session.",
    translation: "Увидимся на следующей тренировке.",
    example: "Great job today. See you at the next session!",
    exampleTranslation: "Отлично поработал. Увидимся на следующей тренировке!",
  },
  {
    phrase: "What bothers you the most right now?",
    translation: "Что тебя сейчас больше всего беспокоит?",
    example: "What bothers you the most right now — back, knees, or energy?",
    exampleTranslation: "Что сейчас больше беспокоит — спина, колени или энергия?",
  },
  {
    phrase: "We'll work around that.",
    translation: "Мы будем это учитывать / обойдём это.",
    example: "You have knee pain? Okay, we'll work around that.",
    exampleTranslation: "Боль в колене? Ок, будем это учитывать.",
  },
  {
    phrase: "I want you to feel safe with every movement.",
    translation: "Хочу, чтобы тебе было безопасно в каждом движении.",
    example: "I want you to feel safe with every movement, so speak up anytime.",
    exampleTranslation: "Хочу, чтобы тебе было безопасно в каждом движении — говори сразу.",
  },
  {
    phrase: "Good — that's better.",
    translation: "Хорошо — так лучше.",
    example: "Yes, keep your chest up. Good — that's better.",
    exampleTranslation: "Да, грудь выше. Хорошо — так лучше.",
  },
  {
    phrase: "Don't hold your breath.",
    translation: "Не задерживай дыхание.",
    example: "Don't hold your breath — keep breathing.",
    exampleTranslation: "Не задерживай дыхание — дыши постоянно.",
  },
  {
    phrase: "Stop if you feel sharp pain.",
    translation: "Остановись, если будет острая боль.",
    example: "Muscle burn is okay. Stop if you feel sharp pain.",
    exampleTranslation: "Жжение в мышцах — нормально. Остановись при острой боли.",
  },
  {
    phrase: "I'll watch your form from the side.",
    translation: "Я посмотрю технику сбоку.",
    example: "Do a few reps — I'll watch your form from the side.",
    exampleTranslation: "Сделай несколько повторений — я посмотрю технику сбоку.",
  },
  {
    phrase: "Your job today is just to move well.",
    translation: "Твоя задача сегодня — просто хорошо двигаться.",
    example: "Don't chase the weight. Your job today is just to move well.",
    exampleTranslation: "Не гонись за весом. Сегодня твоя задача — хорошо двигаться.",
  },

  // Very basic everyday phrases
  {
    phrase: "I got it. Okay.",
    translation: "Я понял. Хорошо.",
    example: "Meet at five. I got it. Okay.",
    exampleTranslation: "Встречаемся в пять. Я понял. Хорошо.",
  },
  {
    phrase: "I'm here.",
    translation: "Я здесь.",
    example: "I'm here. Where are you?",
    exampleTranslation: "Я здесь. Ты где?",
  },
  {
    phrase: "I'm waiting for you.",
    translation: "Я жду тебя.",
    example: "I'm waiting for you near the door.",
    exampleTranslation: "Я жду тебя у двери.",
  },
  {
    phrase: "Do you need this entrance or the apartment?",
    translation: "Тебе нужен этот подъезд или квартира?",
    example: "Do you need this entrance or the apartment? Say the number.",
    exampleTranslation: "Тебе нужен этот подъезд или квартира? Скажи номер.",
  },
  {
    phrase: "Which entrance?",
    translation: "Какой подъезд?",
    example: "Which entrance? Left or right?",
    exampleTranslation: "Какой подъезд? Левый или правый?",
  },
  {
    phrase: "Which apartment?",
    translation: "Какая квартира?",
    example: "Which apartment? 12?",
    exampleTranslation: "Какая квартира? 12?",
  },
  {
    phrase: "I'm outside.",
    translation: "Я снаружи.",
    example: "I'm outside. Can you open the door?",
    exampleTranslation: "Я снаружи. Можешь открыть дверь?",
  },
  {
    phrase: "Come in.",
    translation: "Заходи.",
    example: "The door is open. Come in.",
    exampleTranslation: "Дверь открыта. Заходи.",
  },
  {
    phrase: "Wait here.",
    translation: "Подожди здесь.",
    example: "Wait here. I'll be back.",
    exampleTranslation: "Подожди здесь. Я скоро вернусь.",
  },
  {
    phrase: "I'm coming.",
    translation: "Я иду / сейчас буду.",
    example: "I'm coming. Two minutes.",
    exampleTranslation: "Сейчас буду. Две минуты.",
  },
  {
    phrase: "Where are you?",
    translation: "Ты где?",
    example: "Where are you? I can't see you.",
    exampleTranslation: "Ты где? Я тебя не вижу.",
  },
  {
    phrase: "I'm near the door.",
    translation: "Я у двери.",
    example: "I'm near the door. Come out.",
    exampleTranslation: "Я у двери. Выходи.",
  },
  {
    phrase: "This way.",
    translation: "Сюда / этой дорогой.",
    example: "This way. Follow me.",
    exampleTranslation: "Сюда. Иди за мной.",
  },
  {
    phrase: "That way.",
    translation: "Туда.",
    example: "Not here. That way.",
    exampleTranslation: "Не сюда. Туда.",
  },
  {
    phrase: "Follow me.",
    translation: "Иди за мной.",
    example: "Follow me. It's close.",
    exampleTranslation: "Иди за мной. Это рядом.",
  },
  {
    phrase: "Stay here.",
    translation: "Останься здесь.",
    example: "Stay here. Don't move.",
    exampleTranslation: "Останься здесь. Не двигайся.",
  },
  {
    phrase: "Come with me.",
    translation: "Пойдём со мной.",
    example: "Come with me. It's this way.",
    exampleTranslation: "Пойдём со мной. Вот сюда.",
  },
  {
    phrase: "Okay, I understand.",
    translation: "Ок, я понимаю.",
    example: "Call me later. Okay, I understand.",
    exampleTranslation: "Позвони позже. Ок, я понимаю.",
  },
  {
    phrase: "Yes.",
    translation: "Да.",
    example: "Do you need help? Yes.",
    exampleTranslation: "Нужна помощь? Да.",
  },
  {
    phrase: "No.",
    translation: "Нет.",
    example: "Is this yours? No.",
    exampleTranslation: "Это твоё? Нет.",
  },
  {
    phrase: "Okay.",
    translation: "Хорошо / ок.",
    example: "See you at six. Okay.",
    exampleTranslation: "Увидимся в шесть. Ок.",
  },
  {
    phrase: "Please.",
    translation: "Пожалуйста.",
    example: "Water, please.",
    exampleTranslation: "Воды, пожалуйста.",
  },
  {
    phrase: "Thanks.",
    translation: "Спасибо.",
    example: "Here you go. Thanks.",
    exampleTranslation: "Вот. Спасибо.",
  },
  {
    phrase: "Sorry.",
    translation: "Извини / извините.",
    example: "Sorry. My mistake.",
    exampleTranslation: "Извини. Моя ошибка.",
  },
  {
    phrase: "Help me, please.",
    translation: "Помогите, пожалуйста.",
    example: "Help me, please. This is heavy.",
    exampleTranslation: "Помогите, пожалуйста. Это тяжёлое.",
  },
  {
    phrase: "I need this.",
    translation: "Мне это нужно.",
    example: "I need this bag.",
    exampleTranslation: "Мне нужна эта сумка.",
  },
  {
    phrase: "I don't need this.",
    translation: "Мне это не нужно.",
    example: "I don't need this. Take it back.",
    exampleTranslation: "Мне это не нужно. Заберите.",
  },
  {
    phrase: "Give me this, please.",
    translation: "Дайте мне это, пожалуйста.",
    example: "Give me this, please. The blue one.",
    exampleTranslation: "Дайте мне это, пожалуйста. Синее.",
  },
  {
    phrase: "Take this.",
    translation: "Возьми это.",
    example: "Take this. It's for you.",
    exampleTranslation: "Возьми это. Это тебе.",
  },
  {
    phrase: "Put it here.",
    translation: "Поставь / положи сюда.",
    example: "Put it here, please.",
    exampleTranslation: "Положи сюда, пожалуйста.",
  },
  {
    phrase: "Put it there.",
    translation: "Поставь / положи туда.",
    example: "Put it there, by the wall.",
    exampleTranslation: "Поставь туда, у стены.",
  },
  {
    phrase: "Open the door, please.",
    translation: "Открой дверь, пожалуйста.",
    example: "I'm here. Open the door, please.",
    exampleTranslation: "Я здесь. Открой дверь, пожалуйста.",
  },
  {
    phrase: "Close the door, please.",
    translation: "Закрой дверь, пожалуйста.",
    example: "It's cold. Close the door, please.",
    exampleTranslation: "Холодно. Закрой дверь, пожалуйста.",
  },
  {
    phrase: "What's the code?",
    translation: "Какой код?",
    example: "What's the code for the door?",
    exampleTranslation: "Какой код от двери?",
  },
  {
    phrase: "The code is...",
    translation: "Код...",
    example: "The code is 1234.",
    exampleTranslation: "Код 1234.",
  },
  {
    phrase: "Call me.",
    translation: "Позвони мне.",
    example: "Call me when you're here.",
    exampleTranslation: "Позвони, когда будешь здесь.",
  },
  {
    phrase: "Text me.",
    translation: "Напиши мне.",
    example: "Text me the address.",
    exampleTranslation: "Напиши мне адрес.",
  },
  {
    phrase: "Send me the address.",
    translation: "Пришли адрес.",
    example: "Send me the address, please.",
    exampleTranslation: "Пришли адрес, пожалуйста.",
  },
  {
    phrase: "I'm at the entrance.",
    translation: "Я у подъезда.",
    example: "I'm at the entrance. Come down.",
    exampleTranslation: "Я у подъезда. Спускайся.",
  },
  {
    phrase: "Come down, please.",
    translation: "Спустись, пожалуйста.",
    example: "I'm outside. Come down, please.",
    exampleTranslation: "Я снаружи. Спустись, пожалуйста.",
  },
  {
    phrase: "Go up.",
    translation: "Поднимайся / иди наверх.",
    example: "Go up to the third floor.",
    exampleTranslation: "Поднимайся на третий этаж.",
  },
  {
    phrase: "Go down.",
    translation: "Спускайся / иди вниз.",
    example: "Go down. I'm waiting.",
    exampleTranslation: "Спускайся. Я жду.",
  },
  {
    phrase: "Left.",
    translation: "Налево / слева.",
    example: "Turn left.",
    exampleTranslation: "Поверни налево.",
  },
  {
    phrase: "Right.",
    translation: "Направо / справа.",
    example: "Turn right.",
    exampleTranslation: "Поверни направо.",
  },
  {
    phrase: "Straight.",
    translation: "Прямо.",
    example: "Go straight.",
    exampleTranslation: "Иди прямо.",
  },
  {
    phrase: "Stop.",
    translation: "Стоп / остановись.",
    example: "Stop. Wait.",
    exampleTranslation: "Стоп. Подожди.",
  },
  {
    phrase: "Slow down.",
    translation: "Медленнее.",
    example: "Slow down, please.",
    exampleTranslation: "Медленнее, пожалуйста.",
  },
  {
    phrase: "Faster.",
    translation: "Быстрее.",
    example: "A bit faster, please.",
    exampleTranslation: "Чуть быстрее, пожалуйста.",
  },
  {
    phrase: "One minute.",
    translation: "Минуту.",
    example: "One minute. I'm almost ready.",
    exampleTranslation: "Минуту. Я почти готов.",
  },
  {
    phrase: "Two minutes.",
    translation: "Две минуты.",
    example: "Two minutes. Wait.",
    exampleTranslation: "Две минуты. Подожди.",
  },
  {
    phrase: "Now.",
    translation: "Сейчас.",
    example: "Come now.",
    exampleTranslation: "Иди сейчас.",
  },
  {
    phrase: "Later.",
    translation: "Потом / позже.",
    example: "Not now. Later.",
    exampleTranslation: "Не сейчас. Потом.",
  },
  {
    phrase: "Today.",
    translation: "Сегодня.",
    example: "Can we meet today?",
    exampleTranslation: "Можем встретиться сегодня?",
  },
  {
    phrase: "Tomorrow.",
    translation: "Завтра.",
    example: "See you tomorrow.",
    exampleTranslation: "Увидимся завтра.",
  },
  {
    phrase: "Here.",
    translation: "Здесь / вот.",
    example: "Put it here.",
    exampleTranslation: "Положи здесь.",
  },
  {
    phrase: "There.",
    translation: "Там.",
    example: "It's there.",
    exampleTranslation: "Оно там.",
  },
  {
    phrase: "This.",
    translation: "Это / вот это.",
    example: "I need this.",
    exampleTranslation: "Мне нужно это.",
  },
  {
    phrase: "That.",
    translation: "То / вон то.",
    example: "Not this. That.",
    exampleTranslation: "Не это. То.",
  },
  {
    phrase: "Mine.",
    translation: "Моё.",
    example: "This is mine.",
    exampleTranslation: "Это моё.",
  },
  {
    phrase: "Yours.",
    translation: "Твоё / ваше.",
    example: "Is this yours?",
    exampleTranslation: "Это твоё?",
  },
  {
    phrase: "I don't know.",
    translation: "Я не знаю.",
    example: "Where is it? I don't know.",
    exampleTranslation: "Где это? Я не знаю.",
  },
  {
    phrase: "I know.",
    translation: "Я знаю.",
    example: "I know. It's over there.",
    exampleTranslation: "Я знаю. Оно вон там.",
  },
  {
    phrase: "I see.",
    translation: "Понятно / вижу.",
    example: "Ah, I see.",
    exampleTranslation: "А, понятно.",
  },
  {
    phrase: "Look.",
    translation: "Смотри.",
    example: "Look. It's here.",
    exampleTranslation: "Смотри. Вот оно.",
  },
  {
    phrase: "Listen.",
    translation: "Слушай.",
    example: "Listen. Important.",
    exampleTranslation: "Слушай. Важно.",
  },
  {
    phrase: "Repeat, please.",
    translation: "Повтори, пожалуйста.",
    example: "I didn't hear. Repeat, please.",
    exampleTranslation: "Не услышал. Повтори, пожалуйста.",
  },
  {
    phrase: "Say it again.",
    translation: "Скажи ещё раз.",
    example: "Say it again, slowly.",
    exampleTranslation: "Скажи ещё раз, медленно.",
  },
  {
    phrase: "What?",
    translation: "Что?",
    example: "What? I didn't hear.",
    exampleTranslation: "Что? Не услышал.",
  },
  {
    phrase: "Who?",
    translation: "Кто?",
    example: "Who is this?",
    exampleTranslation: "Кто это?",
  },
  {
    phrase: "Where?",
    translation: "Где?",
    example: "Where? Here or there?",
    exampleTranslation: "Где? Здесь или там?",
  },
  {
    phrase: "When?",
    translation: "Когда?",
    example: "When? Today?",
    exampleTranslation: "Когда? Сегодня?",
  },
  {
    phrase: "Why?",
    translation: "Почему?",
    example: "Why? Tell me.",
    exampleTranslation: "Почему? Скажи.",
  },
  {
    phrase: "How?",
    translation: "Как?",
    example: "How? Show me.",
    exampleTranslation: "Как? Покажи.",
  },
  {
    phrase: "How much?",
    translation: "Сколько?",
    example: "How much? Ten?",
    exampleTranslation: "Сколько? Десять?",
  },
  {
    phrase: "How many?",
    translation: "Сколько (штук)?",
    example: "How many? Two or three?",
    exampleTranslation: "Сколько? Два или три?",
  },
  {
    phrase: "All good.",
    translation: "Всё хорошо.",
    example: "All good. Thanks.",
    exampleTranslation: "Всё хорошо. Спасибо.",
  },
  {
    phrase: "Let's go.",
    translation: "Пойдём.",
    example: "Ready? Let's go.",
    exampleTranslation: "Готов? Пойдём.",
  },
  {
    phrase: "Let's start.",
    translation: "Начнём.",
    example: "Okay. Let's start.",
    exampleTranslation: "Ок. Начнём.",
  },
  {
    phrase: "We're done.",
    translation: "Мы закончили.",
    example: "We're done. Good job.",
    exampleTranslation: "Мы закончили. Молодец.",
  },
  {
    phrase: "Sit down, please.",
    translation: "Садись, пожалуйста.",
    example: "Sit down, please. Rest.",
    exampleTranslation: "Садись, пожалуйста. Отдохни.",
  },
  {
    phrase: "Stand up, please.",
    translation: "Встань, пожалуйста.",
    example: "Stand up, please. Let's go.",
    exampleTranslation: "Встань, пожалуйста. Пойдём.",
  },
  {
    phrase: "Come closer.",
    translation: "Подойди ближе.",
    example: "Come closer. Look here.",
    exampleTranslation: "Подойди ближе. Смотри сюда.",
  },
  {
    phrase: "A bit more.",
    translation: "Ещё чуть-чуть.",
    example: "A bit more. Yes.",
    exampleTranslation: "Ещё чуть-чуть. Да.",
  },
  {
    phrase: "That's it.",
    translation: "Вот так / всё.",
    example: "Yes. That's it.",
    exampleTranslation: "Да. Вот так.",
  },
  {
    phrase: "Like this.",
    translation: "Вот так.",
    example: "Do it like this.",
    exampleTranslation: "Сделай вот так.",
  },
  {
    phrase: "Not like that.",
    translation: "Не так.",
    example: "Not like that. Like this.",
    exampleTranslation: "Не так. Вот так.",
  },
  {
    phrase: "Too much.",
    translation: "Слишком много.",
    example: "Too much. Less, please.",
    exampleTranslation: "Слишком много. Меньше, пожалуйста.",
  },
  {
    phrase: "Too little.",
    translation: "Слишком мало.",
    example: "Too little. More, please.",
    exampleTranslation: "Слишком мало. Больше, пожалуйста.",
  },
  {
    phrase: "More, please.",
    translation: "Ещё, пожалуйста.",
    example: "More, please. One more.",
    exampleTranslation: "Ещё, пожалуйста. Ещё один.",
  },
  {
    phrase: "Less, please.",
    translation: "Меньше, пожалуйста.",
    example: "Less, please. It's too much.",
    exampleTranslation: "Меньше, пожалуйста. Слишком много.",
  },
  {
    phrase: "Same.",
    translation: "То же самое.",
    example: "Same for me.",
    exampleTranslation: "Мне то же самое.",
  },
  {
    phrase: "Different.",
    translation: "Другое.",
    example: "I need a different one.",
    exampleTranslation: "Мне нужно другое.",
  },
  {
    phrase: "Big.",
    translation: "Большой.",
    example: "I need a big bag.",
    exampleTranslation: "Мне нужна большая сумка.",
  },
  {
    phrase: "Small.",
    translation: "Маленький.",
    example: "A small one, please.",
    exampleTranslation: "Маленький, пожалуйста.",
  },
  {
    phrase: "Hot.",
    translation: "Горячо / горячий.",
    example: "Careful. Hot.",
    exampleTranslation: "Осторожно. Горячо.",
  },
  {
    phrase: "Cold.",
    translation: "Холодно / холодный.",
    example: "It's cold here.",
    exampleTranslation: "Здесь холодно.",
  },
  {
    phrase: "I'm ready.",
    translation: "Я готов.",
    example: "I'm ready. Let's go.",
    exampleTranslation: "Я готов. Пойдём.",
  },
  {
    phrase: "I'm not ready.",
    translation: "Я не готов.",
    example: "Wait. I'm not ready.",
    exampleTranslation: "Подожди. Я не готов.",
  },
  {
    phrase: "I'm busy.",
    translation: "Я занят.",
    example: "Sorry, I'm busy now.",
    exampleTranslation: "Извини, я сейчас занят.",
  },
  {
    phrase: "I'm free.",
    translation: "Я свободен.",
    example: "I'm free after six.",
    exampleTranslation: "Я свободен после шести.",
  },
  {
    phrase: "Call me when you're here.",
    translation: "Позвони, когда будешь здесь.",
    example: "Call me when you're here. I'll come out.",
    exampleTranslation: "Позвони, когда будешь здесь. Я выйду.",
  },
  {
    phrase: "I'm on my way.",
    translation: "Я уже еду / иду.",
    example: "I'm on my way. Ten minutes.",
    exampleTranslation: "Я уже еду. Десять минут.",
  },
  {
    phrase: "Almost there.",
    translation: "Почти на месте.",
    example: "Almost there. One minute.",
    exampleTranslation: "Почти на месте. Минута.",
  },
  {
    phrase: "Wrong place.",
    translation: "Не то место.",
    example: "Wrong place. Not here.",
    exampleTranslation: "Не то место. Не здесь.",
  },
  {
    phrase: "Right place.",
    translation: "Верное место.",
    example: "Yes. Right place.",
    exampleTranslation: "Да. Верное место.",
  },
  {
    phrase: "First floor.",
    translation: "Первый этаж.",
    example: "First floor. Door on the left.",
    exampleTranslation: "Первый этаж. Дверь слева.",
  },
  {
    phrase: "Second floor.",
    translation: "Второй этаж.",
    example: "Second floor. Apartment 7.",
    exampleTranslation: "Второй этаж. Квартира 7.",
  },
  {
    phrase: "Third floor.",
    translation: "Третий этаж.",
    example: "Go to the third floor.",
    exampleTranslation: "Иди на третий этаж.",
  },
];
