export type Phrase = {
  phrase: string;
  translation: string;
  example: string;
  exampleTranslation: string;
};

export const phrases: Phrase[] = [
  // Greetings / small talk
  {
    phrase: "Good morning!",
    translation: "Доброе утро!",
    example: "Good morning! How are you?",
    exampleTranslation: "Доброе утро! Как дела?",
  },
  {
    phrase: "Good afternoon!",
    translation: "Добрый день!",
    example: "Good afternoon! Nice to see you.",
    exampleTranslation: "Добрый день! Рад тебя видеть.",
  },
  {
    phrase: "Good evening!",
    translation: "Добрый вечер!",
    example: "Good evening! How was your day?",
    exampleTranslation: "Добрый вечер! Как прошёл день?",
  },
  {
    phrase: "How are you?",
    translation: "Как дела?",
    example: "Hi! How are you today?",
    exampleTranslation: "Привет! Как дела сегодня?",
  },
  {
    phrase: "I'm fine, thanks.",
    translation: "Нормально, спасибо.",
    example: "I'm fine, thanks. And you?",
    exampleTranslation: "Нормально, спасибо. А ты?",
  },
  {
    phrase: "And you?",
    translation: "А ты / а вы?",
    example: "I'm good, thanks. And you?",
    exampleTranslation: "У меня хорошо, спасибо. А у тебя?",
  },
  {
    phrase: "Nice to meet you.",
    translation: "Приятно познакомиться.",
    example: "Hi, nice to meet you.",
    exampleTranslation: "Привет, приятно познакомиться.",
  },
  {
    phrase: "Nice to see you.",
    translation: "Рад тебя видеть.",
    example: "Nice to see you again!",
    exampleTranslation: "Рад снова тебя видеть!",
  },
  {
    phrase: "How did you sleep?",
    translation: "Как ты спал?",
    example: "How did you sleep today?",
    exampleTranslation: "Как ты спал сегодня?",
  },
  {
    phrase: "Have a nice day.",
    translation: "Хорошего дня.",
    example: "Bye! Have a nice day.",
    exampleTranslation: "Пока! Хорошего дня.",
  },
  {
    phrase: "See you later.",
    translation: "Увидимся позже.",
    example: "I have to go. See you later!",
    exampleTranslation: "Мне пора. Увидимся позже!",
  },
  {
    phrase: "See you tomorrow.",
    translation: "Увидимся завтра.",
    example: "Okay, see you tomorrow.",
    exampleTranslation: "Ок, увидимся завтра.",
  },
  {
    phrase: "What's your name?",
    translation: "Как тебя зовут?",
    example: "Hi! What's your name?",
    exampleTranslation: "Привет! Как тебя зовут?",
  },
  {
    phrase: "My name is...",
    translation: "Меня зовут...",
    example: "My name is Den. Nice to meet you.",
    exampleTranslation: "Меня зовут Den. Приятно познакомиться.",
  },
  {
    phrase: "How was your day?",
    translation: "Как прошёл день?",
    example: "Hey! How was your day?",
    exampleTranslation: "Эй! Как прошёл день?",
  },
  {
    phrase: "What are you doing?",
    translation: "Что ты делаешь?",
    example: "Hey, what are you doing now?",
    exampleTranslation: "Эй, что ты сейчас делаешь?",
  },

  // Yes / no / simple replies
  {
    phrase: "Yes.",
    translation: "Да.",
    example: "Do you need help? Yes.",
    exampleTranslation: "Нужна помощь? Да.",
  },
  {
    phrase: "No.",
    translation: "Нет.",
    example: "Is this yours? No.",
    exampleTranslation: "Это твоё? Нет.",
  },
  {
    phrase: "Okay.",
    translation: "Хорошо / ок.",
    example: "See you at six. Okay.",
    exampleTranslation: "Увидимся в шесть. Ок.",
  },
  {
    phrase: "Please.",
    translation: "Пожалуйста.",
    example: "Water, please.",
    exampleTranslation: "Воды, пожалуйста.",
  },
  {
    phrase: "Thanks.",
    translation: "Спасибо.",
    example: "Here you go. Thanks.",
    exampleTranslation: "Вот. Спасибо.",
  },
  {
    phrase: "Thank you so much.",
    translation: "Большое спасибо.",
    example: "Thank you so much for your help.",
    exampleTranslation: "Большое спасибо за помощь.",
  },
  {
    phrase: "You're welcome.",
    translation: "Пожалуйста / не за что.",
    example: "Thank you! You're welcome.",
    exampleTranslation: "Спасибо! Не за что.",
  },
  {
    phrase: "Sorry.",
    translation: "Извини / извините.",
    example: "Sorry. My mistake.",
    exampleTranslation: "Извини. Моя ошибка.",
  },
  {
    phrase: "No problem.",
    translation: "Без проблем.",
    example: "Thanks for waiting. No problem!",
    exampleTranslation: "Спасибо, что подождал. Без проблем!",
  },
  {
    phrase: "No worries.",
    translation: "Не переживай / без проблем.",
    example: "Sorry I'm late. No worries.",
    exampleTranslation: "Извини, что опоздал. Без проблем.",
  },
  {
    phrase: "I got it.",
    translation: "Понял / ясно.",
    example: "Turn left. Okay, I got it.",
    exampleTranslation: "Налево. Ок, понял.",
  },
  {
    phrase: "I understand.",
    translation: "Я понимаю.",
    example: "Okay, I understand.",
    exampleTranslation: "Ок, я понимаю.",
  },
  {
    phrase: "I don't know.",
    translation: "Я не знаю.",
    example: "Where is it? I don't know.",
    exampleTranslation: "Где это? Я не знаю.",
  },
  {
    phrase: "I think so.",
    translation: "Думаю, да.",
    example: "Is this the right street? I think so.",
    exampleTranslation: "Это та улица? Думаю, да.",
  },
  {
    phrase: "I don't think so.",
    translation: "Думаю, нет.",
    example: "Is the store open? I don't think so.",
    exampleTranslation: "Магазин открыт? Думаю, нет.",
  },
  {
    phrase: "Maybe later.",
    translation: "Может, позже.",
    example: "Coffee now? Maybe later.",
    exampleTranslation: "Кофе сейчас? Может, позже.",
  },
  {
    phrase: "Sounds good.",
    translation: "Звучит хорошо.",
    example: "Let's meet at five. Sounds good.",
    exampleTranslation: "Давай встретимся в пять. Звучит хорошо.",
  },
  {
    phrase: "That's it.",
    translation: "Вот так / всё.",
    example: "Yes. That's it.",
    exampleTranslation: "Да. Вот так.",
  },
  {
    phrase: "All good.",
    translation: "Всё хорошо.",
    example: "All good. Thanks.",
    exampleTranslation: "Всё хорошо. Спасибо.",
  },

  // Clarifying / help
  {
    phrase: "Sorry, I don't understand.",
    translation: "Извините, я не понимаю.",
    example: "Sorry, I don't understand. Can you repeat?",
    exampleTranslation: "Извините, я не понимаю. Можете повторить?",
  },
  {
    phrase: "Can you repeat that?",
    translation: "Можете повторить?",
    example: "Can you repeat that, please?",
    exampleTranslation: "Можете повторить, пожалуйста?",
  },
  {
    phrase: "Say it again, please.",
    translation: "Скажи ещё раз, пожалуйста.",
    example: "I didn't hear. Say it again, please.",
    exampleTranslation: "Не услышал. Скажи ещё раз, пожалуйста.",
  },
  {
    phrase: "Please speak slowly.",
    translation: "Говорите, пожалуйста, медленно.",
    example: "Please speak slowly. I'm still learning.",
    exampleTranslation: "Говорите медленно. Я ещё учусь.",
  },
  {
    phrase: "What does that mean?",
    translation: "Что это значит?",
    example: "Sorry, what does that mean?",
    exampleTranslation: "Прости, что это значит?",
  },
  {
    phrase: "I didn't hear you.",
    translation: "Я не расслышал.",
    example: "Sorry, I didn't hear you.",
    exampleTranslation: "Извини, я не расслышал.",
  },
  {
    phrase: "Can you help me?",
    translation: "Можете мне помочь?",
    example: "Excuse me, can you help me?",
    exampleTranslation: "Извините, можете мне помочь?",
  },
  {
    phrase: "I need help.",
    translation: "Мне нужна помощь.",
    example: "Excuse me, I need help.",
    exampleTranslation: "Извините, мне нужна помощь.",
  },
  {
    phrase: "Do you speak English?",
    translation: "Вы говорите по-английски?",
    example: "Excuse me, do you speak English?",
    exampleTranslation: "Извините, вы говорите по-английски?",
  },
  {
    phrase: "I speak a little English.",
    translation: "Я говорю по-английски немного.",
    example: "I speak a little English. Please speak slowly.",
    exampleTranslation: "Я говорю по-английски немного. Говорите медленно.",
  },
  {
    phrase: "I'm learning English.",
    translation: "Я учу английский.",
    example: "I'm learning English, so speak slowly.",
    exampleTranslation: "Я учу английский, так что говорите медленно.",
  },

  // Here / there / this / that
  {
    phrase: "Here.",
    translation: "Здесь / вот.",
    example: "Put it here.",
    exampleTranslation: "Положи здесь.",
  },
  {
    phrase: "There.",
    translation: "Там.",
    example: "It's there.",
    exampleTranslation: "Оно там.",
  },
  {
    phrase: "This way.",
    translation: "Сюда.",
    example: "This way. Follow me.",
    exampleTranslation: "Сюда. Иди за мной.",
  },
  {
    phrase: "That way.",
    translation: "Туда.",
    example: "Not here. That way.",
    exampleTranslation: "Не сюда. Туда.",
  },
  {
    phrase: "It's over there.",
    translation: "Оно вон там.",
    example: "The bathroom? It's over there.",
    exampleTranslation: "Туалет? Вон там.",
  },
  {
    phrase: "It's right here.",
    translation: "Вот оно / прямо здесь.",
    example: "Looking for your keys? They're right here.",
    exampleTranslation: "Ищешь ключи? Они вот здесь.",
  },
  {
    phrase: "This one, please.",
    translation: "Вот этот, пожалуйста.",
    example: "This one, please — the blue one.",
    exampleTranslation: "Вот этот, пожалуйста — синий.",
  },
  {
    phrase: "Not that one.",
    translation: "Не тот.",
    example: "Not that one. The other one.",
    exampleTranslation: "Не тот. Другой.",
  },
  {
    phrase: "Which one?",
    translation: "Какой / который?",
    example: "There are two. Which one?",
    exampleTranslation: "Тут два. Какой?",
  },
  {
    phrase: "Is this yours?",
    translation: "Это ваше / твоё?",
    example: "Excuse me, is this yours?",
    exampleTranslation: "Извините, это ваше?",
  },
  {
    phrase: "That's not mine.",
    translation: "Это не моё.",
    example: "That's not mine. Mine is blue.",
    exampleTranslation: "Это не моё. Моё — синее.",
  },
  {
    phrase: "This is for me.",
    translation: "Это мне.",
    example: "This is for me. Thank you.",
    exampleTranslation: "Это мне. Спасибо.",
  },
  {
    phrase: "I need this.",
    translation: "Мне это нужно.",
    example: "I need this bag.",
    exampleTranslation: "Мне нужна эта сумка.",
  },
  {
    phrase: "I don't need this.",
    translation: "Мне это не нужно.",
    example: "I don't need this. Take it back.",
    exampleTranslation: "Мне это не нужно. Заберите.",
  },

  // Directions / location
  {
    phrase: "Where is the bathroom?",
    translation: "Где туалет?",
    example: "Excuse me, where is the bathroom?",
    exampleTranslation: "Извините, где туалет?",
  },
  {
    phrase: "Where is the metro?",
    translation: "Где метро?",
    example: "Excuse me, where is the metro?",
    exampleTranslation: "Извините, где метро?",
  },
  {
    phrase: "How do I get there?",
    translation: "Как туда добраться?",
    example: "How do I get there from here?",
    exampleTranslation: "Как туда добраться отсюда?",
  },
  {
    phrase: "Is it far?",
    translation: "Это далеко?",
    example: "Is it far from here?",
    exampleTranslation: "Это далеко отсюда?",
  },
  {
    phrase: "I'm a bit lost.",
    translation: "Я немного заблудился.",
    example: "Excuse me, I'm a bit lost.",
    exampleTranslation: "Извините, я немного заблудился.",
  },
  {
    phrase: "Turn left.",
    translation: "Поверните налево.",
    example: "Turn left here.",
    exampleTranslation: "Поверните здесь налево.",
  },
  {
    phrase: "Turn right.",
    translation: "Поверните направо.",
    example: "Turn right at the light.",
    exampleTranslation: "Поверните направо на светофоре.",
  },
  {
    phrase: "Go straight.",
    translation: "Идите прямо.",
    example: "Go straight for two blocks.",
    exampleTranslation: "Идите прямо два квартала.",
  },
  {
    phrase: "I'm almost there.",
    translation: "Я почти на месте.",
    example: "I'm almost there. Five minutes.",
    exampleTranslation: "Я почти на месте. Пять минут.",
  },
  {
    phrase: "I'm on my way.",
    translation: "Я уже еду / иду.",
    example: "I'm on my way. Ten minutes.",
    exampleTranslation: "Я уже еду. Десять минут.",
  },
  {
    phrase: "Where are you?",
    translation: "Ты где?",
    example: "Where are you? I can't see you.",
    exampleTranslation: "Ты где? Я тебя не вижу.",
  },
  {
    phrase: "I'm here.",
    translation: "Я здесь.",
    example: "I'm here. Where are you?",
    exampleTranslation: "Я здесь. Ты где?",
  },
  {
    phrase: "I'm outside.",
    translation: "Я снаружи.",
    example: "I'm outside. Can you open the door?",
    exampleTranslation: "Я снаружи. Можешь открыть дверь?",
  },
  {
    phrase: "I'm near the door.",
    translation: "Я у двери.",
    example: "I'm near the door. Come out.",
    exampleTranslation: "Я у двери. Выходи.",
  },
  {
    phrase: "I'm at the entrance.",
    translation: "Я у подъезда.",
    example: "I'm at the entrance. Come down.",
    exampleTranslation: "Я у подъезда. Спускайся.",
  },
  {
    phrase: "Come in.",
    translation: "Заходи.",
    example: "The door is open. Come in.",
    exampleTranslation: "Дверь открыта. Заходи.",
  },
  {
    phrase: "Come down, please.",
    translation: "Спустись, пожалуйста.",
    example: "I'm outside. Come down, please.",
    exampleTranslation: "Я снаружи. Спустись, пожалуйста.",
  },
  {
    phrase: "Wait here.",
    translation: "Подожди здесь.",
    example: "Wait here. I'll be back.",
    exampleTranslation: "Подожди здесь. Я скоро вернусь.",
  },
  {
    phrase: "Follow me.",
    translation: "Иди за мной.",
    example: "Follow me. It's close.",
    exampleTranslation: "Иди за мной. Это рядом.",
  },
  {
    phrase: "Where should we meet?",
    translation: "Где встретимся?",
    example: "Where should we meet — at the door?",
    exampleTranslation: "Где встретимся — у двери?",
  },
  {
    phrase: "I'll meet you there.",
    translation: "Встретимся там.",
    example: "I can't pick you up. I'll meet you there.",
    exampleTranslation: "Не смогу заехать. Встретимся там.",
  },
  {
    phrase: "I live near here.",
    translation: "Я живу рядом.",
    example: "I live near here, so I walk a lot.",
    exampleTranslation: "Я живу рядом, поэтому часто хожу пешком.",
  },

  // Time / plans
  {
    phrase: "What time is it?",
    translation: "Который час?",
    example: "Excuse me, what time is it?",
    exampleTranslation: "Извините, который час?",
  },
  {
    phrase: "Today.",
    translation: "Сегодня.",
    example: "Can we meet today?",
    exampleTranslation: "Можем встретиться сегодня?",
  },
  {
    phrase: "Tomorrow.",
    translation: "Завтра.",
    example: "See you tomorrow.",
    exampleTranslation: "Увидимся завтра.",
  },
  {
    phrase: "Later.",
    translation: "Потом / позже.",
    example: "Not now. Later.",
    exampleTranslation: "Не сейчас. Потом.",
  },
  {
    phrase: "Now.",
    translation: "Сейчас.",
    example: "Come now.",
    exampleTranslation: "Иди сейчас.",
  },
  {
    phrase: "One minute.",
    translation: "Минуту.",
    example: "One minute. I'm almost ready.",
    exampleTranslation: "Минуту. Я почти готов.",
  },
  {
    phrase: "Just a second.",
    translation: "Секунду.",
    example: "Just a second, let me check.",
    exampleTranslation: "Секунду, сейчас проверю.",
  },
  {
    phrase: "I'm free after six.",
    translation: "Я свободен после шести.",
    example: "I'm free after six if that works.",
    exampleTranslation: "Я свободен после шести, если удобно.",
  },
  {
    phrase: "Does that work for you?",
    translation: "Тебе так удобно?",
    example: "Saturday at noon — does that work for you?",
    exampleTranslation: "Суббота в полдень — тебе так удобно?",
  },
  {
    phrase: "I'll be there in ten.",
    translation: "Буду через десять минут.",
    example: "I'll be there in ten. Wait for me.",
    exampleTranslation: "Буду через десять. Подожди меня.",
  },
  {
    phrase: "It's getting late.",
    translation: "Уже поздно становится.",
    example: "It's getting late. I should go home.",
    exampleTranslation: "Уже поздно. Мне пора домой.",
  },
  {
    phrase: "I should get going.",
    translation: "Мне пора идти.",
    example: "I should get going. See you!",
    exampleTranslation: "Мне пора идти. Увидимся!",
  },
  {
    phrase: "What are you up to?",
    translation: "Какие планы?",
    example: "Hey, what are you up to today?",
    exampleTranslation: "Эй, какие планы на сегодня?",
  },
  {
    phrase: "I'm busy.",
    translation: "Я занят.",
    example: "Sorry, I'm busy now.",
    exampleTranslation: "Извини, я сейчас занят.",
  },
  {
    phrase: "I'm free.",
    translation: "Я свободен.",
    example: "I'm free after lunch.",
    exampleTranslation: "Я свободен после обеда.",
  },
  {
    phrase: "I'm ready.",
    translation: "Я готов.",
    example: "I'm ready. Let's go.",
    exampleTranslation: "Я готов. Пойдём.",
  },
  {
    phrase: "I'm not ready.",
    translation: "Я не готов.",
    example: "Wait. I'm not ready.",
    exampleTranslation: "Подожди. Я не готов.",
  },
  {
    phrase: "Let's go.",
    translation: "Пойдём.",
    example: "Ready? Let's go.",
    exampleTranslation: "Готов? Пойдём.",
  },
  {
    phrase: "Let's start.",
    translation: "Начнём.",
    example: "Okay. Let's start.",
    exampleTranslation: "Ок. Начнём.",
  },

  // Cafe / food / shopping
  {
    phrase: "A table for two, please.",
    translation: "Столик на двоих, пожалуйста.",
    example: "Hi, a table for two, please.",
    exampleTranslation: "Здравствуйте, столик на двоих, пожалуйста.",
  },
  {
    phrase: "Could I get a menu?",
    translation: "Можно меню?",
    example: "Hi, could I get a menu, please?",
    exampleTranslation: "Здравствуйте, можно меню, пожалуйста?",
  },
  {
    phrase: "Water, please.",
    translation: "Воды, пожалуйста.",
    example: "Water, please. No ice.",
    exampleTranslation: "Воды, пожалуйста. Без льда.",
  },
  {
    phrase: "I'll have the same.",
    translation: "Мне то же самое.",
    example: "That looks good — I'll have the same.",
    exampleTranslation: "Выглядит вкусно — мне то же самое.",
  },
  {
    phrase: "The bill, please.",
    translation: "Счёт, пожалуйста.",
    example: "The bill, please. Thank you.",
    exampleTranslation: "Счёт, пожалуйста. Спасибо.",
  },
  {
    phrase: "Can I pay by card?",
    translation: "Можно оплатить картой?",
    example: "Can I pay by card, please?",
    exampleTranslation: "Можно оплатить картой, пожалуйста?",
  },
  {
    phrase: "Do you take card?",
    translation: "Картой можно?",
    example: "Do you take card, or cash only?",
    exampleTranslation: "Картой можно, или только наличные?",
  },
  {
    phrase: "For here or to go?",
    translation: "Здесь или с собой?",
    example: "For here or to go? To go, please.",
    exampleTranslation: "Здесь или с собой? С собой, пожалуйста.",
  },
  {
    phrase: "How much is this?",
    translation: "Сколько это стоит?",
    example: "Excuse me, how much is this?",
    exampleTranslation: "Извините, сколько это стоит?",
  },
  {
    phrase: "I'd like this, please.",
    translation: "Мне вот это, пожалуйста.",
    example: "I'd like this, please. And water.",
    exampleTranslation: "Мне вот это, пожалуйста. И воды.",
  },
  {
    phrase: "I'm just looking, thanks.",
    translation: "Я просто смотрю, спасибо.",
    example: "Need help? I'm just looking, thanks.",
    exampleTranslation: "Помочь? Я просто смотрю, спасибо.",
  },
  {
    phrase: "Can I return this?",
    translation: "Можно это вернуть?",
    example: "Can I return this if it doesn't fit?",
    exampleTranslation: "Можно это вернуть, если не подойдёт?",
  },
  {
    phrase: "I need a bag, please.",
    translation: "Мне нужен пакет, пожалуйста.",
    example: "I need a bag, please. A small one.",
    exampleTranslation: "Мне нужен пакет, пожалуйста. Маленький.",
  },
  {
    phrase: "Where can I buy water?",
    translation: "Где можно купить воду?",
    example: "Excuse me, where can I buy water?",
    exampleTranslation: "Извините, где можно купить воду?",
  },
  {
    phrase: "Is this seat taken?",
    translation: "Это место занято?",
    example: "Excuse me, is this seat taken?",
    exampleTranslation: "Извините, это место занято?",
  },
  {
    phrase: "Can I sit here?",
    translation: "Можно здесь сесть?",
    example: "Excuse me, can I sit here?",
    exampleTranslation: "Извините, можно здесь сесть?",
  },
  {
    phrase: "Open or closed?",
    translation: "Открыто или закрыто?",
    example: "Excuse me — open or closed?",
    exampleTranslation: "Извините — открыто или закрыто?",
  },
  {
    phrase: "What time do you close?",
    translation: "Во сколько вы закрываетесь?",
    example: "What time do you close today?",
    exampleTranslation: "Во сколько вы закрываетесь сегодня?",
  },

  // Delivery / door / home
  {
    phrase: "I have a delivery for you.",
    translation: "У меня для вас доставка.",
    example: "Hi, I have a delivery for you.",
    exampleTranslation: "Здравствуйте, у меня для вас доставка.",
  },
  {
    phrase: "I'll be right down.",
    translation: "Сейчас спущусь.",
    example: "I'm on the third floor. I'll be right down.",
    exampleTranslation: "Я на третьем этаже. Сейчас спущусь.",
  },
  {
    phrase: "Leave it at the door.",
    translation: "Оставьте у двери.",
    example: "I'm busy. Leave it at the door.",
    exampleTranslation: "Я занят. Оставьте у двери.",
  },
  {
    phrase: "Can you ring the doorbell?",
    translation: "Можете позвонить в звонок?",
    example: "I'm home. Can you ring the doorbell?",
    exampleTranslation: "Я дома. Можете позвонить в звонок?",
  },
  {
    phrase: "Is this the right address?",
    translation: "Это правильный адрес?",
    example: "Just checking — is this the right address?",
    exampleTranslation: "Просто уточняю — это правильный адрес?",
  },
  {
    phrase: "Open the door, please.",
    translation: "Открой дверь, пожалуйста.",
    example: "I'm here. Open the door, please.",
    exampleTranslation: "Я здесь. Открой дверь, пожалуйста.",
  },
  {
    phrase: "Close the door, please.",
    translation: "Закрой дверь, пожалуйста.",
    example: "It's cold. Close the door, please.",
    exampleTranslation: "Холодно. Закрой дверь, пожалуйста.",
  },
  {
    phrase: "What's the code?",
    translation: "Какой код?",
    example: "What's the code for the door?",
    exampleTranslation: "Какой код от двери?",
  },
  {
    phrase: "Which floor?",
    translation: "Какой этаж?",
    example: "Which floor? Third floor, please.",
    exampleTranslation: "Какой этаж? Третий, пожалуйста.",
  },
  {
    phrase: "Which apartment?",
    translation: "Какая квартира?",
    example: "Which apartment? 12?",
    exampleTranslation: "Какая квартира? 12?",
  },
  {
    phrase: "Put it here.",
    translation: "Поставь / положи сюда.",
    example: "Put it here, please.",
    exampleTranslation: "Положи сюда, пожалуйста.",
  },
  {
    phrase: "Put it there.",
    translation: "Поставь / положи туда.",
    example: "Put it there, by the wall.",
    exampleTranslation: "Поставь туда, у стены.",
  },
  {
    phrase: "Take this.",
    translation: "Возьми это.",
    example: "Take this. It's for you.",
    exampleTranslation: "Возьми это. Это тебе.",
  },
  {
    phrase: "The Wi-Fi isn't working.",
    translation: "Вайфай не работает.",
    example: "The Wi-Fi isn't working. Can you check?",
    exampleTranslation: "Вайфай не работает. Можешь проверить?",
  },
  {
    phrase: "What's the Wi-Fi password?",
    translation: "Какой пароль от вайфая?",
    example: "What's the Wi-Fi password?",
    exampleTranslation: "Какой пароль от вайфая?",
  },
  {
    phrase: "Is there Wi-Fi here?",
    translation: "Здесь есть вайфай?",
    example: "Is there Wi-Fi here? What's the password?",
    exampleTranslation: "Здесь есть вайфай? Какой пароль?",
  },

  // Phone / messages
  {
    phrase: "Call me.",
    translation: "Позвони мне.",
    example: "Call me when you're here.",
    exampleTranslation: "Позвони, когда будешь здесь.",
  },
  {
    phrase: "Text me.",
    translation: "Напиши мне.",
    example: "Text me the address.",
    exampleTranslation: "Напиши мне адрес.",
  },
  {
    phrase: "Send me the address.",
    translation: "Пришли адрес.",
    example: "Send me the address, please.",
    exampleTranslation: "Пришли адрес, пожалуйста.",
  },
  {
    phrase: "Did you get my message?",
    translation: "Ты получил моё сообщение?",
    example: "Did you get my message about tomorrow?",
    exampleTranslation: "Ты получил сообщение про завтра?",
  },
  {
    phrase: "Sorry, I missed your call.",
    translation: "Извини, пропустил твой звонок.",
    example: "Sorry, I missed your call — what's up?",
    exampleTranslation: "Извини, пропустил звонок — что случилось?",
  },
  {
    phrase: "Can you hear me?",
    translation: "Меня слышно?",
    example: "The connection is bad — can you hear me?",
    exampleTranslation: "Связь плохая — меня слышно?",
  },
  {
    phrase: "Can I get your number?",
    translation: "Можно твой номер?",
    example: "Can I get your number? I'll text you.",
    exampleTranslation: "Можно твой номер? Напишу тебе.",
  },

  // Feelings / soft daily
  {
    phrase: "I'm tired.",
    translation: "Я устал.",
    example: "I'm tired. Let's rest.",
    exampleTranslation: "Я устал. Давай отдохнём.",
  },
  {
    phrase: "I'm hungry.",
    translation: "Я голодный.",
    example: "I'm hungry. Let's eat.",
    exampleTranslation: "Я голодный. Давай поедим.",
  },
  {
    phrase: "I'm thirsty.",
    translation: "Я хочу пить.",
    example: "I'm thirsty. Water, please.",
    exampleTranslation: "Я хочу пить. Воды, пожалуйста.",
  },
  {
    phrase: "I'm cold.",
    translation: "Мне холодно.",
    example: "I'm cold. Close the window.",
    exampleTranslation: "Мне холодно. Закрой окно.",
  },
  {
    phrase: "I'm hot.",
    translation: "Мне жарко.",
    example: "I'm hot. Open the window.",
    exampleTranslation: "Мне жарко. Открой окно.",
  },
  {
    phrase: "I'm not in the mood.",
    translation: "У меня нет настроения.",
    example: "Want to go out? I'm not in the mood.",
    exampleTranslation: "Хочешь пойти? У меня нет настроения.",
  },
  {
    phrase: "Is everything okay?",
    translation: "Всё в порядке?",
    example: "You look worried — is everything okay?",
    exampleTranslation: "Ты выглядишь обеспокоенным — всё в порядке?",
  },
  {
    phrase: "I appreciate it.",
    translation: "Я это ценю.",
    example: "Thanks for waiting. I appreciate it.",
    exampleTranslation: "Спасибо, что подождал. Я это ценю.",
  },
  {
    phrase: "It slipped my mind.",
    translation: "Я забыл.",
    example: "I was supposed to call, but it slipped my mind.",
    exampleTranslation: "Я должен был позвонить, но забыл.",
  },
  {
    phrase: "I'm running late.",
    translation: "Я опаздываю.",
    example: "I'm running late. Ten more minutes.",
    exampleTranslation: "Я опаздываю. Ещё десять минут.",
  },
  {
    phrase: "Sorry I'm late.",
    translation: "Извините, что опоздал.",
    example: "Sorry I'm late. The bus was slow.",
    exampleTranslation: "Извините, что опоздал. Автобус ехал медленно.",
  },
  {
    phrase: "No rush.",
    translation: "Не торопись.",
    example: "Take your time, no rush.",
    exampleTranslation: "Не торопись, времени достаточно.",
  },
  {
    phrase: "Take your time.",
    translation: "Не торопись.",
    example: "Take your time. I'm in no rush.",
    exampleTranslation: "Не торопись. Я никуда не спешу.",
  },
  {
    phrase: "It's up to you.",
    translation: "Решать тебе.",
    example: "We can stay in or go out. It's up to you.",
    exampleTranslation: "Можем остаться дома или пойти. Решать тебе.",
  },
  {
    phrase: "That sounds good to me.",
    translation: "Меня это устраивает.",
    example: "We can meet at six. That sounds good to me.",
    exampleTranslation: "Можем встретиться в шесть. Меня устраивает.",
  },
  {
    phrase: "Let's give it a shot.",
    translation: "Давай попробуем.",
    example: "I've never tried this, but let's give it a shot.",
    exampleTranslation: "Я никогда это не пробовал, но давай попробуем.",
  },
  {
    phrase: "It's worth a try.",
    translation: "Стоит попробовать.",
    example: "I'm not sure, but it's worth a try.",
    exampleTranslation: "Не уверен, но стоит попробовать.",
  },
  {
    phrase: "Let's see how it goes.",
    translation: "Посмотрим, как пойдёт.",
    example: "We'll start small and see how it goes.",
    exampleTranslation: "Начнём с малого и посмотрим, как пойдёт.",
  },
  {
    phrase: "I'll keep that in mind.",
    translation: "Я это учту.",
    example: "You prefer window seats? I'll keep that in mind.",
    exampleTranslation: "Ты предпочитаешь места у окна? Я это учту.",
  },
  {
    phrase: "That makes sense.",
    translation: "Это логично / понятно.",
    example: "Ah, that makes sense.",
    exampleTranslation: "А, понятно.",
  },
  {
    phrase: "I'm on it.",
    translation: "Уже занимаюсь этим.",
    example: "Can you send it today? I'm on it.",
    exampleTranslation: "Сможешь отправить сегодня? Уже занимаюсь.",
  },
  {
    phrase: "I'll figure it out.",
    translation: "Я разберусь.",
    example: "I don't know yet, but I'll figure it out.",
    exampleTranslation: "Пока не знаю, но разберусь.",
  },
  {
    phrase: "It is what it is.",
    translation: "Что есть, то есть.",
    example: "We missed the bus, but it is what it is.",
    exampleTranslation: "Мы опоздали на автобус, но что уж поделаешь.",
  },
  {
    phrase: "I just moved here.",
    translation: "Я недавно сюда переехал.",
    example: "I just moved here last month.",
    exampleTranslation: "Я переехал сюда только в прошлом месяце.",
  },
  {
    phrase: "I'm still getting used to it.",
    translation: "Я ещё привыкаю.",
    example: "The city is big. I'm still getting used to it.",
    exampleTranslation: "Город большой. Я ещё привыкаю.",
  },
  {
    phrase: "I'm originally from Russia.",
    translation: "Я из России.",
    example: "I'm originally from Russia, but I live here now.",
    exampleTranslation: "Я из России, но сейчас живу здесь.",
  },
  {
    phrase: "I work remotely.",
    translation: "Я работаю удалённо.",
    example: "Most days I work remotely from home.",
    exampleTranslation: "В большинстве дней я работаю удалённо из дома.",
  },
  {
    phrase: "I'm here for work.",
    translation: "Я здесь по работе.",
    example: "I'm here for work for a few months.",
    exampleTranslation: "Я здесь по работе на несколько месяцев.",
  },
  {
    phrase: "Let's grab a coffee.",
    translation: "Давай выпьем кофе.",
    example: "Let's grab a coffee sometime.",
    exampleTranslation: "Давай как-нибудь выпьем кофе.",
  },
  {
    phrase: "I'd love to stay in touch.",
    translation: "Давай останемся на связи.",
    example: "It was great talking. I'd love to stay in touch.",
    exampleTranslation: "Было здорово поговорить. Давай останемся на связи.",
  },
  {
    phrase: "What brings you here?",
    translation: "Что тебя сюда привело?",
    example: "So what brings you here tonight?",
    exampleTranslation: "Так что привело тебя сюда сегодня?",
  },
  {
    phrase: "Have we met before?",
    translation: "Мы раньше встречались?",
    example: "Sorry, have we met before?",
    exampleTranslation: "Извини, мы раньше встречались?",
  },
  {
    phrase: "It was great meeting you.",
    translation: "Было здорово познакомиться.",
    example: "I have to run, but it was great meeting you.",
    exampleTranslation: "Мне пора, но было здорово познакомиться.",
  },
  {
    phrase: "After you.",
    translation: "После вас / проходите.",
    example: "After you — go ahead.",
    exampleTranslation: "После вас — проходите.",
  },
  {
    phrase: "Here you go.",
    translation: "Вот, пожалуйста.",
    example: "Here you go. Have a nice day!",
    exampleTranslation: "Вот, пожалуйста. Хорошего дня!",
  },
  {
    phrase: "Look.",
    translation: "Смотри.",
    example: "Look. It's here.",
    exampleTranslation: "Смотри. Вот оно.",
  },
  {
    phrase: "Listen.",
    translation: "Слушай.",
    example: "Listen. This is important.",
    exampleTranslation: "Слушай. Это важно.",
  },
  {
    phrase: "Stop.",
    translation: "Стоп / остановись.",
    example: "Stop. Wait.",
    exampleTranslation: "Стоп. Подожди.",
  },
  {
    phrase: "Slow down.",
    translation: "Медленнее.",
    example: "Slow down, please.",
    exampleTranslation: "Медленнее, пожалуйста.",
  },
  {
    phrase: "Come closer.",
    translation: "Подойди ближе.",
    example: "Come closer. Look here.",
    exampleTranslation: "Подойди ближе. Смотри сюда.",
  },
  {
    phrase: "Sit down, please.",
    translation: "Садись, пожалуйста.",
    example: "Sit down, please. Rest.",
    exampleTranslation: "Садись, пожалуйста. Отдохни.",
  },
  {
    phrase: "Stand up, please.",
    translation: "Встань, пожалуйста.",
    example: "Stand up, please. Let's go.",
    exampleTranslation: "Встань, пожалуйста. Пойдём.",
  },
  {
    phrase: "We're done.",
    translation: "Мы закончили.",
    example: "We're done. Good job.",
    exampleTranslation: "Мы закончили. Молодец.",
  },
  {
    phrase: "It looks like rain.",
    translation: "Похоже, будет дождь.",
    example: "It looks like rain — grab an umbrella.",
    exampleTranslation: "Похоже, будет дождь — возьми зонт.",
  },
  {
    phrase: "Drink some water.",
    translation: "Выпей воды.",
    example: "Drink some water before we go.",
    exampleTranslation: "Выпей воды, прежде чем идём.",
  },

  // Everyday home life
  {
    phrase: "I just woke up.",
    translation: "Я только проснулся.",
    example: "Give me a minute, I just woke up.",
    exampleTranslation: "Дай минуту, я только проснулся.",
  },
  {
    phrase: "I'm still sleepy.",
    translation: "Я ещё сонный.",
    example: "Don't talk so fast, I'm still sleepy.",
    exampleTranslation: "Не говори так быстро, я ещё сонный.",
  },
  {
    phrase: "I need coffee.",
    translation: "Мне нужен кофе.",
    example: "I need coffee before we talk.",
    exampleTranslation: "Мне нужен кофе, прежде чем мы поговорим.",
  },
  {
    phrase: "Did you sleep well?",
    translation: "Ты хорошо спал?",
    example: "Did you sleep well last night?",
    exampleTranslation: "Ты хорошо спал прошлой ночью?",
  },
  {
    phrase: "I slept badly.",
    translation: "Я плохо спал.",
    example: "I slept badly, so I'm slow today.",
    exampleTranslation: "Я плохо спал, поэтому сегодня туплю.",
  },
  {
    phrase: "The alarm went off.",
    translation: "Сработал будильник.",
    example: "The alarm went off at seven.",
    exampleTranslation: "Будильник сработал в семь.",
  },
  {
    phrase: "I hit snooze.",
    translation: "Я отложил будильник.",
    example: "I hit snooze twice this morning.",
    exampleTranslation: "Я дважды отложил будильник сегодня утром.",
  },
  {
    phrase: "What time did you get up?",
    translation: "Во сколько ты встал?",
    example: "What time did you get up today?",
    exampleTranslation: "Во сколько ты сегодня встал?",
  },
  {
    phrase: "I need a shower.",
    translation: "Мне нужно в душ.",
    example: "I need a shower before we leave.",
    exampleTranslation: "Мне нужно в душ, прежде чем мы уйдём.",
  },
  {
    phrase: "The bathroom is free.",
    translation: "Ванная свободна.",
    example: "The bathroom is free if you need it.",
    exampleTranslation: "Ванная свободна, если тебе нужно.",
  },
  {
    phrase: "Don't forget your keys.",
    translation: "Не забудь ключи.",
    example: "Don't forget your keys, I locked the door.",
    exampleTranslation: "Не забудь ключи, я закрыл дверь.",
  },
  {
    phrase: "Where are my glasses?",
    translation: "Где мои очки?",
    example: "Where are my glasses? I can't read this.",
    exampleTranslation: "Где мои очки? Я не могу это прочитать.",
  },
  {
    phrase: "I can't find my phone.",
    translation: "Не могу найти телефон.",
    example: "I can't find my phone. Can you call it?",
    exampleTranslation: "Не могу найти телефон. Можешь позвонить?",
  },
  {
    phrase: "Charge my phone, please.",
    translation: "Поставь телефон на зарядку, пожалуйста.",
    example: "Charge my phone, please, it's almost dead.",
    exampleTranslation: "Поставь телефон на зарядку, он почти сел.",
  },
  {
    phrase: "My battery is low.",
    translation: "Батарея садится.",
    example: "My battery is low, I need a charger.",
    exampleTranslation: "Батарея садится, нужен зарядник.",
  },
  {
    phrase: "I'll make breakfast.",
    translation: "Я приготовлю завтрак.",
    example: "Sit down, I'll make breakfast.",
    exampleTranslation: "Садись, я приготовлю завтрак.",
  },
  {
    phrase: "What's for breakfast?",
    translation: "Что на завтрак?",
    example: "What's for breakfast, eggs or oatmeal?",
    exampleTranslation: "Что на завтрак, яйца или овсянка?",
  },
  {
    phrase: "Just toast for me.",
    translation: "Мне только тост.",
    example: "I'm not hungry. Just toast for me.",
    exampleTranslation: "Я не голодный. Мне только тост.",
  },
  {
    phrase: "I skipped breakfast.",
    translation: "Я пропустил завтрак.",
    example: "I skipped breakfast, so I'm starving now.",
    exampleTranslation: "Я пропустил завтрак, поэтому сейчас очень голодный.",
  },
  {
    phrase: "Brush your teeth.",
    translation: "Почисти зубы.",
    example: "Brush your teeth before bed.",
    exampleTranslation: "Почисти зубы перед сном.",
  },
  {
    phrase: "I need a towel.",
    translation: "Мне нужно полотенце.",
    example: "I need a towel, the one in there is wet.",
    exampleTranslation: "Мне нужно полотенце, то мокрое.",
  },
  {
    phrase: "There's no hot water.",
    translation: "Нет горячей воды.",
    example: "There's no hot water, I'll shower later.",
    exampleTranslation: "Нет горячей воды, примусь позже.",
  },
  {
    phrase: "The water is too cold.",
    translation: "Вода слишком холодная.",
    example: "The water is too cold, wait a second.",
    exampleTranslation: "Вода слишком холодная, подожди секунду.",
  },
  {
    phrase: "Close the curtains.",
    translation: "Закрой шторы.",
    example: "Close the curtains, the sun is bright.",
    exampleTranslation: "Закрой шторы, солнце слепит.",
  },
  {
    phrase: "Open the curtains.",
    translation: "Открой шторы.",
    example: "Open the curtains, it's morning.",
    exampleTranslation: "Открой шторы, уже утро.",
  },
  {
    phrase: "What's for dinner?",
    translation: "Что на ужин?",
    example: "What's for dinner tonight?",
    exampleTranslation: "Что сегодня на ужин?",
  },
  {
    phrase: "I'll cook tonight.",
    translation: "Сегодня готовлю я.",
    example: "You worked late, I'll cook tonight.",
    exampleTranslation: "Ты поздно закончил, сегодня готовлю я.",
  },
  {
    phrase: "Can you set the table?",
    translation: "Накроешь на стол?",
    example: "Dinner's almost ready. Can you set the table?",
    exampleTranslation: "Ужин почти готов. Накроешь на стол?",
  },
  {
    phrase: "Dinner is ready.",
    translation: "Ужин готов.",
    example: "Dinner is ready, come eat.",
    exampleTranslation: "Ужин готов, иди есть.",
  },
  {
    phrase: "Wash the dishes, please.",
    translation: "Помой посуду, пожалуйста.",
    example: "I'll cook if you wash the dishes, please.",
    exampleTranslation: "Я готовлю, если помоешь посуду.",
  },
  {
    phrase: "I'll do the dishes.",
    translation: "Я помою посуду.",
    example: "You cooked, I'll do the dishes.",
    exampleTranslation: "Ты готовил, я помою посуду.",
  },
  {
    phrase: "Leave it in the sink.",
    translation: "Оставь в раковине.",
    example: "Don't worry, leave it in the sink.",
    exampleTranslation: "Не переживай, оставь в раковине.",
  },
  {
    phrase: "The dishwasher is full.",
    translation: "Посудомойка полная.",
    example: "The dishwasher is full, I'll run it.",
    exampleTranslation: "Посудомойка полная, я запущу.",
  },
  {
    phrase: "We're out of milk.",
    translation: "Молоко закончилось.",
    example: "We're out of milk, I'll buy some.",
    exampleTranslation: "Молоко закончилось, я куплю.",
  },
  {
    phrase: "We're out of bread.",
    translation: "Хлеб закончился.",
    example: "We're out of bread for breakfast.",
    exampleTranslation: "Хлеб закончился, нечего есть на завтрак.",
  },
  {
    phrase: "Can you grab some eggs?",
    translation: "Можешь взять яйца?",
    example: "If you go out, can you grab some eggs?",
    exampleTranslation: "Если выйдешь, можешь взять яйца?",
  },
  {
    phrase: "Taste this.",
    translation: "Попробуй это.",
    example: "Taste this, I think it needs salt.",
    exampleTranslation: "Попробуй, кажется, мало соли.",
  },
  {
    phrase: "It's too salty.",
    translation: "Слишком солёно.",
    example: "It's too salty, add some water.",
    exampleTranslation: "Слишком солёно, добавь воды.",
  },
  {
    phrase: "It's too spicy.",
    translation: "Слишком остро.",
    example: "It's too spicy for me.",
    exampleTranslation: "Мне слишком остро.",
  },
  {
    phrase: "It's not cooked yet.",
    translation: "Ещё не готово.",
    example: "Wait, it's not cooked yet.",
    exampleTranslation: "Подожди, ещё не готово.",
  },
  {
    phrase: "Don't burn it.",
    translation: "Не сожги.",
    example: "Stay by the pan, don't burn it.",
    exampleTranslation: "Стой у сковороды, не сожги.",
  },
  {
    phrase: "Turn the stove off.",
    translation: "Выключи плиту.",
    example: "We're leaving, turn the stove off.",
    exampleTranslation: "Мы уходим, выключи плиту.",
  },
  {
    phrase: "The kettle is boiling.",
    translation: "Чайник кипит.",
    example: "The kettle is boiling, I'll make tea.",
    exampleTranslation: "Чайник кипит, заварю чай.",
  },
  {
    phrase: "Put it in the fridge.",
    translation: "Поставь в холодильник.",
    example: "Put it in the fridge or it'll go bad.",
    exampleTranslation: "Поставь в холодильник, а то испортится.",
  },
  {
    phrase: "There's leftovers.",
    translation: "Есть остатки.",
    example: "There's leftovers from yesterday.",
    exampleTranslation: "Есть вчерашние остатки.",
  },
  {
    phrase: "I'll heat it up.",
    translation: "Я разогрею.",
    example: "Sit down, I'll heat it up.",
    exampleTranslation: "Садись, я разогрею.",
  },
  {
    phrase: "Use the microwave.",
    translation: "Используй микроволновку.",
    example: "Use the microwave, it's faster.",
    exampleTranslation: "Используй микроволновку, так быстрее.",
  },
  {
    phrase: "Cut it smaller.",
    translation: "Нарежь помельче.",
    example: "Cut it smaller so it cooks faster.",
    exampleTranslation: "Нарежь помельче, так быстрее приготовится.",
  },
  {
    phrase: "I need a knife.",
    translation: "Мне нужен нож.",
    example: "I need a knife for the tomatoes.",
    exampleTranslation: "Мне нужен нож для помидоров.",
  },
  {
    phrase: "Where's the cutting board?",
    translation: "Где разделочная доска?",
    example: "Where's the cutting board? I need it.",
    exampleTranslation: "Где разделочная доска? Она нужна.",
  },
  {
    phrase: "Pass the salt.",
    translation: "Передай соль.",
    example: "Pass the salt, please.",
    exampleTranslation: "Передай соль, пожалуйста.",
  },
  {
    phrase: "Save some for tomorrow.",
    translation: "Оставь немного на завтра.",
    example: "Don't eat it all, save some for tomorrow.",
    exampleTranslation: "Не съедай всё, оставь немного на завтра.",
  },
  {
    phrase: "I'm making tea.",
    translation: "Я завариваю чай.",
    example: "I'm making tea, want a cup?",
    exampleTranslation: "Я завариваю чай, хочешь чашку?",
  },
  {
    phrase: "Do you want coffee or tea?",
    translation: "Кофе или чай?",
    example: "Do you want coffee or tea this morning?",
    exampleTranslation: "Кофе или чай сегодня утром?",
  },
  {
    phrase: "The food is getting cold.",
    translation: "Еда остывает.",
    example: "Come now, the food is getting cold.",
    exampleTranslation: "Иди, еда остывает.",
  },
  {
    phrase: "Don't waste food.",
    translation: "Не выбрасывай еду.",
    example: "Finish your plate, don't waste food.",
    exampleTranslation: "Доедай, не выбрасывай еду.",
  },
  {
    phrase: "I need to go to the store.",
    translation: "Мне нужно в магазин.",
    example: "I need to go to the store after work.",
    exampleTranslation: "Мне нужно в магазин после работы.",
  },
  {
    phrase: "Need anything from the store?",
    translation: "Нужно что-нибудь из магазина?",
    example: "I'm going out. Need anything from the store?",
    exampleTranslation: "Я выхожу. Нужно что-нибудь из магазина?",
  },
  {
    phrase: "I'll run to the grocery store.",
    translation: "Сбегаю в продуктовый.",
    example: "We're out of milk, I'll run to the grocery store.",
    exampleTranslation: "Молоко кончилось, сбегаю в продуктовый.",
  },
  {
    phrase: "Get some fruit.",
    translation: "Возьми фруктов.",
    example: "Get some fruit, we have none at home.",
    exampleTranslation: "Возьми фруктов, дома нет.",
  },
  {
    phrase: "These bananas are ripe.",
    translation: "Эти бананы спелые.",
    example: "These bananas are ripe, eat them today.",
    exampleTranslation: "Эти бананы спелые, съешь сегодня.",
  },
  {
    phrase: "Is this on sale?",
    translation: "Это по акции?",
    example: "Is this on sale or full price?",
    exampleTranslation: "Это по акции или полная цена?",
  },
  {
    phrase: "Where's the dairy aisle?",
    translation: "Где молочный отдел?",
    example: "Excuse me, where's the dairy aisle?",
    exampleTranslation: "Извините, где молочный отдел?",
  },
  {
    phrase: "That's expired.",
    translation: "Это просрочено.",
    example: "Don't buy that yogurt, that's expired.",
    exampleTranslation: "Не бери тот йогурт, он просрочен.",
  },
  {
    phrase: "Check the date.",
    translation: "Проверь срок.",
    example: "Check the date before you buy it.",
    exampleTranslation: "Проверь срок, прежде чем брать.",
  },
  {
    phrase: "I brought my own bag.",
    translation: "Я принёс свою сумку.",
    example: "I brought my own bag, no plastic please.",
    exampleTranslation: "Я принёс свою сумку, без пакета.",
  },
  {
    phrase: "That's all.",
    translation: "Это всё.",
    example: "That's all, thanks.",
    exampleTranslation: "Это всё, спасибо.",
  },
  {
    phrase: "Can I pay here?",
    translation: "Можно оплатить здесь?",
    example: "Can I pay here or at the other desk?",
    exampleTranslation: "Можно оплатить здесь или на другой кассе?",
  },
  {
    phrase: "Keep the change.",
    translation: "Сдачи не надо.",
    example: "Keep the change, it's fine.",
    exampleTranslation: "Сдачи не надо, всё нормально.",
  },
  {
    phrase: "I need a smaller bill.",
    translation: "Нужна купюра помельче.",
    example: "I need a smaller bill for the bus.",
    exampleTranslation: "Нужна купюра помельче на автобус.",
  },
  {
    phrase: "The line is long.",
    translation: "Очередь длинная.",
    example: "The line is long, let's come back later.",
    exampleTranslation: "Очередь длинная, давай позже.",
  },
  {
    phrase: "I'll wait in line.",
    translation: "Я постою в очереди.",
    example: "I'll wait in line, you grab the milk.",
    exampleTranslation: "Я постою в очереди, ты возьми молоко.",
  },
  {
    phrase: "Is this the self-checkout?",
    translation: "Это касса самообслуживания?",
    example: "Is this the self-checkout or a regular one?",
    exampleTranslation: "Это касса самообслуживания или обычная?",
  },
  {
    phrase: "Do you have a loyalty card?",
    translation: "Есть карта лояльности?",
    example: "Do you have a loyalty card I can scan?",
    exampleTranslation: "Есть карта лояльности, которую пробить?",
  },
  {
    phrase: "It's cheaper there.",
    translation: "Там дешевле.",
    example: "Don't buy it here, it's cheaper there.",
    exampleTranslation: "Не бери здесь, там дешевле.",
  },
  {
    phrase: "We have enough at home.",
    translation: "Дома и так полно.",
    example: "Don't buy more rice, we have enough at home.",
    exampleTranslation: "Не бери ещё рис, дома и так полно.",
  },
  {
    phrase: "Don't buy too much.",
    translation: "Не бери слишком много.",
    example: "Don't buy too much, we can't finish it.",
    exampleTranslation: "Не бери слишком много, не съедим.",
  },
  {
    phrase: "I forgot the list.",
    translation: "Я забыл список.",
    example: "I forgot the list at home.",
    exampleTranslation: "Я забыл список дома.",
  },
  {
    phrase: "Put it in the cart.",
    translation: "Положи в корзину.",
    example: "Put it in the cart, I'll get bread.",
    exampleTranslation: "Положи в корзину, я возьму хлеб.",
  },
  {
    phrase: "This is too expensive.",
    translation: "Это слишком дорого.",
    example: "This is too expensive, let's skip it.",
    exampleTranslation: "Это слишком дорого, давай без этого.",
  },
  {
    phrase: "I'll clean up later.",
    translation: "Потом уберу.",
    example: "Leave it, I'll clean up later.",
    exampleTranslation: "Оставь, потом уберу.",
  },
  {
    phrase: "The floor is dirty.",
    translation: "Пол грязный.",
    example: "The floor is dirty, don't walk in socks.",
    exampleTranslation: "Пол грязный, не ходи в носках.",
  },
  {
    phrase: "Can you vacuum?",
    translation: "Можешь пропылесосить?",
    example: "Can you vacuum the living room?",
    exampleTranslation: "Можешь пропылесосить гостиную?",
  },
  {
    phrase: "I'll mop the floor.",
    translation: "Я помою пол.",
    example: "I'll mop the floor after lunch.",
    exampleTranslation: "Я помою пол после обеда.",
  },
  {
    phrase: "Take your shoes off.",
    translation: "Сними обувь.",
    example: "Take your shoes off, I just cleaned.",
    exampleTranslation: "Сними обувь, я только убрал.",
  },
  {
    phrase: "Wipe the table.",
    translation: "Протри стол.",
    example: "Wipe the table before we eat.",
    exampleTranslation: "Протри стол, прежде чем есть.",
  },
  {
    phrase: "The trash is full.",
    translation: "Мусорка полная.",
    example: "The trash is full, I'll take it out.",
    exampleTranslation: "Мусорка полная, я вынесу.",
  },
  {
    phrase: "We need more trash bags.",
    translation: "Нужны ещё пакеты для мусора.",
    example: "We need more trash bags, add it to the list.",
    exampleTranslation: "Нужны ещё пакеты для мусора, добавь в список.",
  },
  {
    phrase: "The laundry is done.",
    translation: "Стирка закончилась.",
    example: "The laundry is done, can you hang it?",
    exampleTranslation: "Стирка закончилась, развесишь?",
  },
  {
    phrase: "I need to do laundry.",
    translation: "Нужно постирать.",
    example: "I need to do laundry, I have no clean socks.",
    exampleTranslation: "Нужно постирать, чистых носков нет.",
  },
  {
    phrase: "Separate the colors.",
    translation: "Раздели по цветам.",
    example: "Separate the colors or they'll fade.",
    exampleTranslation: "Раздели по цветам, а то полиняет.",
  },
  {
    phrase: "Don't shrink this.",
    translation: "Не сядь это.",
    example: "Wash it cold, don't shrink this.",
    exampleTranslation: "Стирай в холодной, не сядь это.",
  },
  {
    phrase: "Hang it to dry.",
    translation: "Повесь сушиться.",
    example: "Hang it to dry, don't use the dryer.",
    exampleTranslation: "Повесь сушиться, не в сушилку.",
  },
  {
    phrase: "Fold the clothes.",
    translation: "Сложи одежду.",
    example: "Fold the clothes so they don't wrinkle.",
    exampleTranslation: "Сложи одежду, чтобы не мялась.",
  },
  {
    phrase: "I can't find a clean shirt.",
    translation: "Не могу найти чистую рубашку.",
    example: "I can't find a clean shirt for work.",
    exampleTranslation: "Не могу найти чистую рубашку на работу.",
  },
  {
    phrase: "These socks don't match.",
    translation: "Эти носки не пара.",
    example: "These socks don't match, I'll wear them anyway.",
    exampleTranslation: "Эти носки не пара, надену и так.",
  },
  {
    phrase: "Put it in the hamper.",
    translation: "Брось в корзину для белья.",
    example: "Don't leave it on the floor, put it in the hamper.",
    exampleTranslation: "Не кидай на пол, брось в корзину для белья.",
  },
  {
    phrase: "The bathroom needs cleaning.",
    translation: "В ванной нужно убраться.",
    example: "The bathroom needs cleaning this weekend.",
    exampleTranslation: "В ванной нужно убраться в эти выходные.",
  },
  {
    phrase: "Clean the mirror.",
    translation: "Протри зеркало.",
    example: "Clean the mirror, it's all spotted.",
    exampleTranslation: "Протри зеркало, всё в пятнах.",
  },
  {
    phrase: "There's dust everywhere.",
    translation: "Везде пыль.",
    example: "There's dust everywhere, I'll wipe it.",
    exampleTranslation: "Везде пыль, я протру.",
  },
  {
    phrase: "Open a window.",
    translation: "Открой окно.",
    example: "Open a window, it smells like cooking.",
    exampleTranslation: "Открой окно, пахнет готовкой.",
  },
  {
    phrase: "It smells in here.",
    translation: "Здесь чем-то пахнет.",
    example: "It smells in here, did you take the trash out?",
    exampleTranslation: "Здесь чем-то пахнет, ты выносил мусор?",
  },
  {
    phrase: "Spray some freshener.",
    translation: "Пшикни освежителем.",
    example: "Spray some freshener in the hallway.",
    exampleTranslation: "Пшикни освежителем в коридоре.",
  },
  {
    phrase: "Change the sheets.",
    translation: "Поменяй постельное.",
    example: "Change the sheets, it's been a week.",
    exampleTranslation: "Поменяй постельное, уже неделя.",
  },
  {
    phrase: "I'm home.",
    translation: "Я дома.",
    example: "I'm home. Where are you?",
    exampleTranslation: "Я дома. Ты где?",
  },
  {
    phrase: "Are you home yet?",
    translation: "Ты уже дома?",
    example: "Are you home yet or still on the way?",
    exampleTranslation: "Ты уже дома или ещё в пути?",
  },
  {
    phrase: "Don't forget to lock the door.",
    translation: "Не забудь закрыть дверь.",
    example: "Don't forget to lock the door when you leave.",
    exampleTranslation: "Не забудь закрыть дверь, когда уйдёшь.",
  },
  {
    phrase: "I locked the door.",
    translation: "Я закрыл дверь.",
    example: "I locked the door already.",
    exampleTranslation: "Я уже закрыл дверь.",
  },
  {
    phrase: "Who's at the door?",
    translation: "Кто у двери?",
    example: "Who's at the door? I'm not expecting anyone.",
    exampleTranslation: "Кто у двери? Я никого не жду.",
  },
  {
    phrase: "Turn on the lights.",
    translation: "Включи свет.",
    example: "Turn on the lights, I can't see.",
    exampleTranslation: "Включи свет, ничего не видно.",
  },
  {
    phrase: "Turn off the lights.",
    translation: "Выключи свет.",
    example: "Turn off the lights when you leave the room.",
    exampleTranslation: "Выключи свет, когда выходишь из комнаты.",
  },
  {
    phrase: "It's too dark in here.",
    translation: "Здесь слишком темно.",
    example: "It's too dark in here, open the blinds.",
    exampleTranslation: "Здесь слишком темно, открой жалюзи.",
  },
  {
    phrase: "The heating is on.",
    translation: "Отопление включено.",
    example: "The heating is on, that's why it's warm.",
    exampleTranslation: "Отопление включено, поэтому тепло.",
  },
  {
    phrase: "Turn the heat down.",
    translation: "Убавь батарею.",
    example: "Turn the heat down, it's too hot.",
    exampleTranslation: "Убавь батарею, слишком жарко.",
  },
  {
    phrase: "It's stuffy in here.",
    translation: "Здесь душно.",
    example: "It's stuffy in here, let's air it out.",
    exampleTranslation: "Здесь душно, давай проветрим.",
  },
  {
    phrase: "Can you open a window?",
    translation: "Можешь открыть окно?",
    example: "Can you open a window for a minute?",
    exampleTranslation: "Можешь открыть окно на минуту?",
  },
  {
    phrase: "Close the window, it's cold.",
    translation: "Закрой окно, холодно.",
    example: "Close the window, it's cold in here.",
    exampleTranslation: "Закрой окно, здесь холодно.",
  },
  {
    phrase: "The AC is too strong.",
    translation: "Кондиционер слишком сильный.",
    example: "The AC is too strong, I'm freezing.",
    exampleTranslation: "Кондиционер слишком сильный, мне холодно.",
  },
  {
    phrase: "Where's the remote?",
    translation: "Где пульт?",
    example: "Where's the remote? I want to change the channel.",
    exampleTranslation: "Где пульт? Хочу переключить.",
  },
  {
    phrase: "Lower the volume.",
    translation: "Убавь звук.",
    example: "Lower the volume, the neighbors can hear.",
    exampleTranslation: "Убавь звук, соседи слышат.",
  },
  {
    phrase: "That's too loud.",
    translation: "Слишком громко.",
    example: "That's too loud, turn it down.",
    exampleTranslation: "Слишком громко, убавь.",
  },
  {
    phrase: "I'll be in the other room.",
    translation: "Я буду в другой комнате.",
    example: "I'll be in the other room if you need me.",
    exampleTranslation: "Я буду в другой комнате, если что.",
  },
  {
    phrase: "Don't leave a mess.",
    translation: "Не оставляй беспорядок.",
    example: "Don't leave a mess in the kitchen.",
    exampleTranslation: "Не оставляй беспорядок на кухне.",
  },
  {
    phrase: "Put your things away.",
    translation: "Убери свои вещи.",
    example: "Put your things away, guests are coming.",
    exampleTranslation: "Убери свои вещи, гости идут.",
  },
  {
    phrase: "This room is a mess.",
    translation: "В этой комнате бардак.",
    example: "This room is a mess, we should clean.",
    exampleTranslation: "В этой комнате бардак, надо убраться.",
  },
  {
    phrase: "I'll make the bed.",
    translation: "Я застелю кровать.",
    example: "I'll make the bed, you do the dishes.",
    exampleTranslation: "Я застелю кровать, ты помой посуду.",
  },
  {
    phrase: "The bulb burned out.",
    translation: "Лампочка перегорела.",
    example: "The bulb burned out in the hallway.",
    exampleTranslation: "В коридоре перегорела лампочка.",
  },
  {
    phrase: "We need a new bulb.",
    translation: "Нужна новая лампочка.",
    example: "We need a new bulb, this one is dead.",
    exampleTranslation: "Нужна новая лампочка, эта сгорела.",
  },
  {
    phrase: "The power went out.",
    translation: "Свет пропал.",
    example: "The power went out, where's the flashlight?",
    exampleTranslation: "Свет пропал, где фонарик?",
  },
  {
    phrase: "It's raining.",
    translation: "Идёт дождь.",
    example: "It's raining, take a jacket.",
    exampleTranslation: "Идёт дождь, возьми куртку.",
  },
  {
    phrase: "Take an umbrella.",
    translation: "Возьми зонт.",
    example: "Take an umbrella, it looks like rain.",
    exampleTranslation: "Возьми зонт, похоже на дождь.",
  },
  {
    phrase: "I forgot my umbrella.",
    translation: "Я забыл зонт.",
    example: "I forgot my umbrella and got soaked.",
    exampleTranslation: "Я забыл зонт и промок.",
  },
  {
    phrase: "It's snowing.",
    translation: "Идёт снег.",
    example: "It's snowing, wear boots.",
    exampleTranslation: "Идёт снег, надень ботинки.",
  },
  {
    phrase: "Wear a jacket.",
    translation: "Надень куртку.",
    example: "Wear a jacket, it's chilly.",
    exampleTranslation: "Надень куртку, прохладно.",
  },
  {
    phrase: "It's windy today.",
    translation: "Сегодня ветрено.",
    example: "It's windy today, hold onto your hat.",
    exampleTranslation: "Сегодня ветрено, придержи шапку.",
  },
  {
    phrase: "I need warmer clothes.",
    translation: "Мне нужна одежда потеплее.",
    example: "I need warmer clothes for this weather.",
    exampleTranslation: "Мне нужна одежда потеплее в такую погоду.",
  },
  {
    phrase: "These shoes are wet.",
    translation: "Эта обувь мокрая.",
    example: "These shoes are wet, I'll change.",
    exampleTranslation: "Эта обувь мокрая, переобуюсь.",
  },
  {
    phrase: "My coat is still wet.",
    translation: "Пальто ещё мокрое.",
    example: "My coat is still wet from yesterday.",
    exampleTranslation: "Пальто ещё мокрое со вчера.",
  },
  {
    phrase: "Dress warmly.",
    translation: "Оденься теплее.",
    example: "Dress warmly, it's freezing outside.",
    exampleTranslation: "Оденься теплее, на улице мороз.",
  },
  {
    phrase: "It's humid.",
    translation: "Влажно.",
    example: "It's humid, my shirt is sticking.",
    exampleTranslation: "Влажно, рубашка липнет.",
  },
  {
    phrase: "The sun is out.",
    translation: "Выглянуло солнце.",
    example: "The sun is out, let's go for a walk.",
    exampleTranslation: "Выглянуло солнце, давай погуляем.",
  },
  {
    phrase: "I got caught in the rain.",
    translation: "Меня застал дождь.",
    example: "I got caught in the rain without a jacket.",
    exampleTranslation: "Меня застал дождь без куртки.",
  },
  {
    phrase: "Bring a sweater.",
    translation: "Возьми свитер.",
    example: "Bring a sweater, it gets cold later.",
    exampleTranslation: "Возьми свитер, потом похолодает.",
  },
  {
    phrase: "This doesn't fit.",
    translation: "Это не сидит.",
    example: "This doesn't fit, I need another size.",
    exampleTranslation: "Это не сидит, нужен другой размер.",
  },
  {
    phrase: "It's too tight.",
    translation: "Слишком тесно.",
    example: "It's too tight around the waist.",
    exampleTranslation: "В талии слишком тесно.",
  },
  {
    phrase: "It's too loose.",
    translation: "Слишком свободно.",
    example: "It's too loose, I'll wear a belt.",
    exampleTranslation: "Слишком свободно, надену ремень.",
  },
  {
    phrase: "I need to change.",
    translation: "Мне нужно переодеться.",
    example: "I need to change, these clothes are dirty.",
    exampleTranslation: "Мне нужно переодеться, эта одежда грязная.",
  },
  {
    phrase: "These are comfortable.",
    translation: "В этом удобно.",
    example: "These are comfortable, I'll wear them at home.",
    exampleTranslation: "В этом удобно, буду ходить дома.",
  },
  {
    phrase: "Hang your coat.",
    translation: "Повесь пальто.",
    example: "Hang your coat, don't throw it on the chair.",
    exampleTranslation: "Повесь пальто, не кидай на стул.",
  },
  {
    phrase: "I'm hungry.",
    translation: "Я голодный.",
    example: "I'm hungry, let's eat something.",
    exampleTranslation: "Я голодный, давай что-нибудь съедим.",
  },
  {
    phrase: "I'm thirsty.",
    translation: "Я хочу пить.",
    example: "I'm thirsty, is there water?",
    exampleTranslation: "Я хочу пить, есть вода?",
  },
  {
    phrase: "I'm tired.",
    translation: "Я устал.",
    example: "I'm tired, I need to sit down.",
    exampleTranslation: "Я устал, мне надо сесть.",
  },
  {
    phrase: "I'm freezing.",
    translation: "Я замёрз.",
    example: "I'm freezing, close the window.",
    exampleTranslation: "Я замёрз, закрой окно.",
  },
  {
    phrase: "I'm sweating.",
    translation: "Я потею.",
    example: "I'm sweating, can we turn the heat down?",
    exampleTranslation: "Я потею, можно убавить батарею?",
  },
  {
    phrase: "I have a headache.",
    translation: "У меня болит голова.",
    example: "I have a headache, I'll lie down.",
    exampleTranslation: "У меня болит голова, я полежу.",
  },
  {
    phrase: "My throat hurts.",
    translation: "У меня болит горло.",
    example: "My throat hurts, I need tea.",
    exampleTranslation: "У меня болит горло, нужен чай.",
  },
  {
    phrase: "I think I'm getting sick.",
    translation: "Кажется, я заболеваю.",
    example: "I think I'm getting sick, I'll stay home.",
    exampleTranslation: "Кажется, я заболеваю, останусь дома.",
  },
  {
    phrase: "I need some rest.",
    translation: "Мне нужно отдохнуть.",
    example: "I need some rest after today.",
    exampleTranslation: "Мне нужно отдохнуть после сегодняшнего.",
  },
  {
    phrase: "I didn't sleep enough.",
    translation: "Я мало спал.",
    example: "I didn't sleep enough, don't expect much.",
    exampleTranslation: "Я мало спал, многого не жди.",
  },
  {
    phrase: "I'm stuffed.",
    translation: "Я объелся.",
    example: "I'm stuffed, I can't eat more.",
    exampleTranslation: "Я объелся, больше не могу.",
  },
  {
    phrase: "I could use a nap.",
    translation: "Не помешал бы вздремнуть.",
    example: "I could use a nap before dinner.",
    exampleTranslation: "Не помешал бы вздремнуть перед ужином.",
  },
  {
    phrase: "My back hurts.",
    translation: "У меня болит спина.",
    example: "My back hurts from sitting all day.",
    exampleTranslation: "У меня болит спина от сидения весь день.",
  },
  {
    phrase: "I feel better now.",
    translation: "Мне уже лучше.",
    example: "I feel better now after some water.",
    exampleTranslation: "Мне уже лучше после воды.",
  },
  {
    phrase: "Take a painkiller.",
    translation: "Выпей обезболивающее.",
    example: "Take a painkiller if it's still bad.",
    exampleTranslation: "Выпей обезболивающее, если всё ещё плохо.",
  },
  {
    phrase: "Drink more water.",
    translation: "Пей больше воды.",
    example: "Drink more water, you look tired.",
    exampleTranslation: "Пей больше воды, ты какой-то уставший.",
  },
  {
    phrase: "I need fresh air.",
    translation: "Мне нужен свежий воздух.",
    example: "I need fresh air, let's step outside.",
    exampleTranslation: "Мне нужен свежий воздух, давай выйдем.",
  },
  {
    phrase: "I'm exhausted.",
    translation: "Я вымотан.",
    example: "I'm exhausted, I'm going to bed.",
    exampleTranslation: "Я вымотан, пойду спать.",
  },
  {
    phrase: "I'm a bit dizzy.",
    translation: "У меня немного кружится голова.",
    example: "I'm a bit dizzy, I need to sit.",
    exampleTranslation: "У меня немного кружится голова, надо сесть.",
  },
  {
    phrase: "Let's sit down.",
    translation: "Давай сядем.",
    example: "Let's sit down for a minute.",
    exampleTranslation: "Давай сядем на минуту.",
  },
  {
    phrase: "Can you hear me now?",
    translation: "Теперь слышно?",
    example: "Can you hear me now or still not?",
    exampleTranslation: "Теперь слышно или всё ещё нет?",
  },
  {
    phrase: "You're breaking up.",
    translation: "Тебя плохо слышно.",
    example: "You're breaking up, I'll call you back.",
    exampleTranslation: "Тебя плохо слышно, я перезвоню.",
  },
  {
    phrase: "I'll call you back.",
    translation: "Я перезвоню.",
    example: "I'm in a store, I'll call you back.",
    exampleTranslation: "Я в магазине, я перезвоню.",
  },
  {
    phrase: "Send me a photo.",
    translation: "Пришли фото.",
    example: "Send me a photo of the label.",
    exampleTranslation: "Пришли фото этикетки.",
  },
  {
    phrase: "My phone died.",
    translation: "Телефон сел.",
    example: "My phone died, that's why I didn't reply.",
    exampleTranslation: "Телефон сел, поэтому не ответил.",
  },
  {
    phrase: "Where's the charger?",
    translation: "Где зарядка?",
    example: "Where's the charger? Mine is in the bag.",
    exampleTranslation: "Где зарядка? Моя в сумке.",
  },
  {
    phrase: "Plug it in.",
    translation: "Включи в розетку.",
    example: "Plug it in or it'll die.",
    exampleTranslation: "Включи в розетку, а то сядет.",
  },
  {
    phrase: "The internet is slow.",
    translation: "Интернет тормозит.",
    example: "The internet is slow, I can't load it.",
    exampleTranslation: "Интернет тормозит, не грузится.",
  },
  {
    phrase: "Restart the router.",
    translation: "Перезагрузи роутер.",
    example: "Restart the router, that usually helps.",
    exampleTranslation: "Перезагрузи роутер, обычно помогает.",
  },
  {
    phrase: "I lost signal.",
    translation: "Пропал сигнал.",
    example: "I lost signal in the elevator.",
    exampleTranslation: "В лифте пропал сигнал.",
  },
  {
    phrase: "I'll send a voice note.",
    translation: "Я запишу голосовое.",
    example: "It's easier, I'll send a voice note.",
    exampleTranslation: "Так проще, я запишу голосовое.",
  },
  {
    phrase: "Don't call, just text.",
    translation: "Не звони, просто напиши.",
    example: "I'm in a meeting, don't call, just text.",
    exampleTranslation: "Я на встрече, не звони, просто напиши.",
  },
  {
    phrase: "Mute yourself.",
    translation: "Выключи микрофон.",
    example: "Mute yourself, there's background noise.",
    exampleTranslation: "Выключи микрофон, там шум.",
  },
  {
    phrase: "You're on speaker.",
    translation: "Ты на громкой связи.",
    example: "You're on speaker, say hi.",
    exampleTranslation: "Ты на громкой связи, скажи привет.",
  },
  {
    phrase: "I'll put you on hold.",
    translation: "Я поставлю на удержание.",
    example: "One second, I'll put you on hold.",
    exampleTranslation: "Секунду, я поставлю на удержание.",
  },
  {
    phrase: "The screen is cracked.",
    translation: "Экран треснул.",
    example: "The screen is cracked, but it still works.",
    exampleTranslation: "Экран треснул, но ещё работает.",
  },
  {
    phrase: "Update later.",
    translation: "Обнови потом.",
    example: "Don't update now, update later.",
    exampleTranslation: "Не обновляй сейчас, обнови потом.",
  },
  {
    phrase: "I can't log in.",
    translation: "Не могу войти.",
    example: "I can't log in, it says wrong password.",
    exampleTranslation: "Не могу войти, пишет неверный пароль.",
  },
  {
    phrase: "What's the password again?",
    translation: "Какой там пароль?",
    example: "What's the password again for the Wi-Fi?",
    exampleTranslation: "Какой там пароль от вайфая?",
  },
  {
    phrase: "I need to take out cash.",
    translation: "Мне нужно снять наличные.",
    example: "I need to take out cash before we go.",
    exampleTranslation: "Мне нужно снять наличные, прежде чем идти.",
  },
  {
    phrase: "Where's the nearest ATM?",
    translation: "Где ближайший банкомат?",
    example: "Where's the nearest ATM around here?",
    exampleTranslation: "Где здесь ближайший банкомат?",
  },
  {
    phrase: "I only have a card.",
    translation: "У меня только карта.",
    example: "I only have a card, no cash.",
    exampleTranslation: "У меня только карта, наличных нет.",
  },
  {
    phrase: "Do you have change?",
    translation: "Есть сдача?",
    example: "Do you have change for a twenty?",
    exampleTranslation: "Есть сдача с двадцатки?",
  },
  {
    phrase: "I'll pay you back.",
    translation: "Я тебе верну.",
    example: "Buy it, I'll pay you back tonight.",
    exampleTranslation: "Купи, я тебе верну вечером.",
  },
  {
    phrase: "How much do I owe you?",
    translation: "Сколько я тебе должен?",
    example: "How much do I owe you for lunch?",
    exampleTranslation: "Сколько я тебе должен за обед?",
  },
  {
    phrase: "Keep the receipt.",
    translation: "Сохрани чек.",
    example: "Keep the receipt in case we return it.",
    exampleTranslation: "Сохрани чек, вдруг вернём.",
  },
  {
    phrase: "I got a parking ticket.",
    translation: "Мне пришёл штраф за парковку.",
    example: "I got a parking ticket this morning.",
    exampleTranslation: "Мне пришёл штраф за парковку сегодня утром.",
  },
  {
    phrase: "I need to mail this.",
    translation: "Мне нужно это отправить.",
    example: "I need to mail this before Friday.",
    exampleTranslation: "Мне нужно это отправить до пятницы.",
  },
  {
    phrase: "Where's the post office?",
    translation: "Где почта?",
    example: "Where's the post office from here?",
    exampleTranslation: "Где отсюда почта?",
  },
  {
    phrase: "I need stamps.",
    translation: "Мне нужны марки.",
    example: "I need stamps for these letters.",
    exampleTranslation: "Мне нужны марки на эти письма.",
  },
  {
    phrase: "The bank is closed.",
    translation: "Банк закрыт.",
    example: "The bank is closed on Sundays.",
    exampleTranslation: "Банк закрыт по воскресеньям.",
  },
  {
    phrase: "I'll transfer it.",
    translation: "Я переведу.",
    example: "I'll transfer it now.",
    exampleTranslation: "Я сейчас переведу.",
  },
  {
    phrase: "That's my treat.",
    translation: "Я угощаю.",
    example: "That's my treat, put your wallet away.",
    exampleTranslation: "Я угощаю, убери кошелёк.",
  },
  {
    phrase: "You got this one last time.",
    translation: "Ты в прошлый раз платил.",
    example: "You got this one last time, it's my turn.",
    exampleTranslation: "Ты в прошлый раз платил, сейчас моя очередь.",
  },
  {
    phrase: "Let's split it.",
    translation: "Давай пополам.",
    example: "Let's split it, that's fair.",
    exampleTranslation: "Давай пополам, так честно.",
  },
  {
    phrase: "I left my wallet at home.",
    translation: "Я оставил кошелёк дома.",
    example: "I left my wallet at home, can you cover me?",
    exampleTranslation: "Я оставил кошелёк дома, прикроешь?",
  },
  {
    phrase: "I need to pay a bill.",
    translation: "Мне нужно оплатить счёт.",
    example: "I need to pay a bill tonight.",
    exampleTranslation: "Мне нужно оплатить счёт сегодня вечером.",
  },
  {
    phrase: "It's due tomorrow.",
    translation: "Срок завтра.",
    example: "It's due tomorrow, don't forget.",
    exampleTranslation: "Срок завтра, не забудь.",
  },
  {
    phrase: "I'll handle the payment.",
    translation: "Я разберусь с оплатой.",
    example: "I'll handle the payment, you relax.",
    exampleTranslation: "Я разберусь с оплатой, отдыхай.",
  },
  {
    phrase: "I'll take the bus.",
    translation: "Я поеду на автобусе.",
    example: "I'll take the bus, it's cheaper.",
    exampleTranslation: "Я поеду на автобусе, так дешевле.",
  },
  {
    phrase: "Which bus goes there?",
    translation: "Какой автобус туда идёт?",
    example: "Which bus goes there from this stop?",
    exampleTranslation: "Какой автобус туда идёт с этой остановки?",
  },
  {
    phrase: "Is this bus going downtown?",
    translation: "Этот автобус в центр?",
    example: "Is this bus going downtown or the other way?",
    exampleTranslation: "Этот автобус в центр или в другую сторону?",
  },
  {
    phrase: "I missed my bus.",
    translation: "Я пропустил автобус.",
    example: "I missed my bus, I'll wait for the next one.",
    exampleTranslation: "Я пропустил автобус, подожду следующий.",
  },
  {
    phrase: "Let's take a taxi.",
    translation: "Давай возьмём такси.",
    example: "It's late, let's take a taxi.",
    exampleTranslation: "Поздно, давай возьмём такси.",
  },
  {
    phrase: "Can you call a cab?",
    translation: "Можешь вызвать такси?",
    example: "Can you call a cab while I lock up?",
    exampleTranslation: "Можешь вызвать такси, пока я закрываю?",
  },
  {
    phrase: "I'll walk.",
    translation: "Я пешком.",
    example: "It's close, I'll walk.",
    exampleTranslation: "Это близко, я пешком.",
  },
  {
    phrase: "It's faster by metro.",
    translation: "На метро быстрее.",
    example: "It's faster by metro than by taxi right now.",
    exampleTranslation: "На метро сейчас быстрее, чем на такси.",
  },
  {
    phrase: "Where do I tap my card?",
    translation: "Куда приложить карту?",
    example: "Where do I tap my card at the gate?",
    exampleTranslation: "Куда приложить карту на турникете?",
  },
  {
    phrase: "My card won't scan.",
    translation: "Карта не считывается.",
    example: "My card won't scan, can I go through?",
    exampleTranslation: "Карта не считывается, можно пройти?",
  },
  {
    phrase: "Next stop, please.",
    translation: "Следующая остановка, пожалуйста.",
    example: "Next stop, please, I need to get off.",
    exampleTranslation: "Следующая, пожалуйста, мне выходить.",
  },
  {
    phrase: "Can I get off here?",
    translation: "Можно здесь выйти?",
    example: "Can I get off here or is it the next one?",
    exampleTranslation: "Можно здесь выйти или следующая?",
  },
  {
    phrase: "There's traffic.",
    translation: "Пробка.",
    example: "There's traffic, we'll be late.",
    exampleTranslation: "Пробка, мы опоздаем.",
  },
  {
    phrase: "I'll drive.",
    translation: "Я за рулём.",
    example: "I'll drive, you navigate.",
    exampleTranslation: "Я за рулём, ты навигируй.",
  },
  {
    phrase: "Can you pick me up?",
    translation: "Можешь заехать за мной?",
    example: "Can you pick me up after work?",
    exampleTranslation: "Можешь заехать за мной после работы?",
  },
  {
    phrase: "Drop me off here.",
    translation: "Высади меня здесь.",
    example: "Drop me off here, I can walk the rest.",
    exampleTranslation: "Высади меня здесь, дальше пешком.",
  },
  {
    phrase: "Is there parking?",
    translation: "Есть парковка?",
    example: "Is there parking near the building?",
    exampleTranslation: "Есть парковка около здания?",
  },
  {
    phrase: "The train is delayed.",
    translation: "Поезд задерживается.",
    example: "The train is delayed by ten minutes.",
    exampleTranslation: "Поезд задерживается на десять минут.",
  },
  {
    phrase: "I need a ticket.",
    translation: "Мне нужен билет.",
    example: "I need a ticket to the center.",
    exampleTranslation: "Мне нужен билет до центра.",
  },
  {
    phrase: "One way, please.",
    translation: "В одну сторону, пожалуйста.",
    example: "One way, please, not a return.",
    exampleTranslation: "В одну сторону, пожалуйста, не туда-обратно.",
  },
  {
    phrase: "Our neighbor is noisy.",
    translation: "Наш сосед шумит.",
    example: "Our neighbor is noisy again.",
    exampleTranslation: "Наш сосед опять шумит.",
  },
  {
    phrase: "Can you keep it down?",
    translation: "Можете потише?",
    example: "It's late, can you keep it down?",
    exampleTranslation: "Уже поздно, можете потише?",
  },
  {
    phrase: "Sorry for the noise.",
    translation: "Извините за шум.",
    example: "Sorry for the noise, we're moving furniture.",
    exampleTranslation: "Извините за шум, мы двигаем мебель.",
  },
  {
    phrase: "I'll be quiet after ten.",
    translation: "После десяти буду тихо.",
    example: "I'll be quiet after ten, I promise.",
    exampleTranslation: "После десяти буду тихо, обещаю.",
  },
  {
    phrase: "Did you hear that?",
    translation: "Ты это слышал?",
    example: "Did you hear that bang?",
    exampleTranslation: "Ты слышал этот удар?",
  },
  {
    phrase: "Someone's at the intercom.",
    translation: "Кто-то в домофоне.",
    example: "Someone's at the intercom, can you get it?",
    exampleTranslation: "Кто-то в домофоне, возьмёшь?",
  },
  {
    phrase: "Buzz me in.",
    translation: "Открой дверь.",
    example: "I'm downstairs, buzz me in.",
    exampleTranslation: "Я внизу, открой дверь.",
  },
  {
    phrase: "I'll buzz you in.",
    translation: "Я тебе открою.",
    example: "I'll buzz you in, one second.",
    exampleTranslation: "Я тебе открою, секунду.",
  },
  {
    phrase: "The hallway light is out.",
    translation: "В подъезде не горит свет.",
    example: "The hallway light is out again.",
    exampleTranslation: "В подъезде опять не горит свет.",
  },
  {
    phrase: "That's the building manager.",
    translation: "Это управдом.",
    example: "That's the building manager at the door.",
    exampleTranslation: "Это управдом у двери.",
  },
  {
    phrase: "I have a package downstairs.",
    translation: "У меня посылка внизу.",
    example: "I have a package downstairs, I'll grab it.",
    exampleTranslation: "У меня посылка внизу, схожу.",
  },
  {
    phrase: "The mailbox is full.",
    translation: "Почтовый ящик полный.",
    example: "The mailbox is full, I should empty it.",
    exampleTranslation: "Почтовый ящик полный, надо вынуть.",
  },
  {
    phrase: "Don't block the stairs.",
    translation: "Не перекрывай лестницу.",
    example: "Don't block the stairs with the bike.",
    exampleTranslation: "Не перекрывай лестницу великом.",
  },
  {
    phrase: "The bike is in the way.",
    translation: "Велик мешается.",
    example: "The bike is in the way, move it.",
    exampleTranslation: "Велик мешается, подвинь.",
  },
  {
    phrase: "I'm going to bed.",
    translation: "Я иду спать.",
    example: "I'm going to bed, don't wait up.",
    exampleTranslation: "Я иду спать, не жди.",
  },
  {
    phrase: "Don't stay up too late.",
    translation: "Не сиди допоздна.",
    example: "Don't stay up too late, you have work.",
    exampleTranslation: "Не сиди допоздна, тебе на работу.",
  },
  {
    phrase: "Set the alarm.",
    translation: "Поставь будильник.",
    example: "Set the alarm for seven.",
    exampleTranslation: "Поставь будильник на семь.",
  },
  {
    phrase: "What time should we wake up?",
    translation: "Во сколько встаём?",
    example: "What time should we wake up tomorrow?",
    exampleTranslation: "Во сколько завтра встаём?",
  },
  {
    phrase: "Turn off the TV.",
    translation: "Выключи телевизор.",
    example: "Turn off the TV, I'm going to sleep.",
    exampleTranslation: "Выключи телевизор, я спать.",
  },
  {
    phrase: "I'm watching this.",
    translation: "Я это смотрю.",
    example: "I'm watching this, don't change it.",
    exampleTranslation: "Я это смотрю, не переключай.",
  },
  {
    phrase: "Let's watch something.",
    translation: "Давай что-нибудь посмотрим.",
    example: "Let's watch something before bed.",
    exampleTranslation: "Давай что-нибудь посмотрим перед сном.",
  },
  {
    phrase: "I'm not watching that.",
    translation: "Я это не буду смотреть.",
    example: "I'm not watching that, pick something else.",
    exampleTranslation: "Я это не буду смотреть, выбери другое.",
  },
  {
    phrase: "Dim the lights.",
    translation: "Приглуши свет.",
    example: "Dim the lights, it's nicer.",
    exampleTranslation: "Приглуши свет, так приятнее.",
  },
  {
    phrase: "Good night.",
    translation: "Спокойной ночи.",
    example: "Good night, see you tomorrow.",
    exampleTranslation: "Спокойной ночи, увидимся завтра.",
  },
  {
    phrase: "Sleep well.",
    translation: "Спи хорошо.",
    example: "Sleep well, you look tired.",
    exampleTranslation: "Спи хорошо, ты выглядишь уставшим.",
  },
  {
    phrase: "See you in the morning.",
    translation: "Увидимся утром.",
    example: "See you in the morning, I'm off.",
    exampleTranslation: "Увидимся утром, я спать.",
  },
  {
    phrase: "I can't sleep.",
    translation: "Не могу уснуть.",
    example: "I can't sleep, it's too hot.",
    exampleTranslation: "Не могу уснуть, слишком жарко.",
  },
  {
    phrase: "It's too bright.",
    translation: "Слишком ярко.",
    example: "It's too bright, close the blinds.",
    exampleTranslation: "Слишком ярко, закрой жалюзи.",
  },
  {
    phrase: "Close the laptop.",
    translation: "Закрой ноутбук.",
    example: "Close the laptop, that's enough for today.",
    exampleTranslation: "Закрой ноутбук, на сегодня хватит.",
  },
  {
    phrase: "I'm done for the night.",
    translation: "На сегодня всё.",
    example: "I'm done for the night, no more screens.",
    exampleTranslation: "На сегодня всё, больше без экранов.",
  },
  {
    phrase: "Leave a light on.",
    translation: "Оставь свет.",
    example: "Leave a light on in the hallway.",
    exampleTranslation: "Оставь свет в коридоре.",
  },
  {
    phrase: "I'll lock up.",
    translation: "Я закрою всё.",
    example: "I'll lock up, you go to bed.",
    exampleTranslation: "Я закрою всё, иди спать.",
  },
  {
    phrase: "Did you brush your teeth?",
    translation: "Ты почистил зубы?",
    example: "Did you brush your teeth yet?",
    exampleTranslation: "Ты уже почистил зубы?",
  },
  {
    phrase: "Charge it overnight.",
    translation: "Поставь на зарядку на ночь.",
    example: "Charge it overnight or you'll have no battery.",
    exampleTranslation: "Поставь на зарядку на ночь, иначе сядет.",
  },
  {
    phrase: "Can you grab that for me?",
    translation: "Можешь мне это подать?",
    example: "Can you grab that for me? My hands are full.",
    exampleTranslation: "Можешь мне это подать? Руки заняты.",
  },
  {
    phrase: "I dropped it.",
    translation: "Я уронил.",
    example: "I dropped it, can you pick it up?",
    exampleTranslation: "Я уронил, поднимешь?",
  },
  {
    phrase: "Watch your step.",
    translation: "Смотри под ноги.",
    example: "Watch your step, the floor is wet.",
    exampleTranslation: "Смотри под ноги, пол мокрый.",
  },
  {
    phrase: "It's slippery.",
    translation: "Скользко.",
    example: "It's slippery by the door.",
    exampleTranslation: "У двери скользко.",
  },
  {
    phrase: "Careful, it's hot.",
    translation: "Осторожно, горячо.",
    example: "Careful, it's hot, I just took it out.",
    exampleTranslation: "Осторожно, горячо, я только достал.",
  },
  {
    phrase: "Let it cool down.",
    translation: "Дай остыть.",
    example: "Let it cool down before you eat.",
    exampleTranslation: "Дай остыть, прежде чем есть.",
  },
  {
    phrase: "Don't touch that.",
    translation: "Не трогай это.",
    example: "Don't touch that, it just came out of the oven.",
    exampleTranslation: "Не трогай, только из духовки.",
  },
  {
    phrase: "I'll be right there.",
    translation: "Я сейчас буду.",
    example: "I'll be right there, one second.",
    exampleTranslation: "Я сейчас буду, секунду.",
  },
  {
    phrase: "Give me five minutes.",
    translation: "Дай пять минут.",
    example: "Give me five minutes to finish this.",
    exampleTranslation: "Дай пять минут закончить.",
  },
  {
    phrase: "I'm in the shower.",
    translation: "Я в душе.",
    example: "I'm in the shower, call back later.",
    exampleTranslation: "Я в душе, перезвони позже.",
  },
  {
    phrase: "Knock first.",
    translation: "Сначала постучи.",
    example: "Knock first, don't just walk in.",
    exampleTranslation: "Сначала постучи, не входи сразу.",
  },
  {
    phrase: "Come in, it's open.",
    translation: "Входи, открыто.",
    example: "Come in, it's open.",
    exampleTranslation: "Входи, открыто.",
  },
  {
    phrase: "I'll get it.",
    translation: "Я открою / я возьму.",
    example: "I'll get it, I'm closer to the door.",
    exampleTranslation: "Я открою, я ближе к двери.",
  },
  {
    phrase: "Who is it?",
    translation: "Кто это?",
    example: "Who is it? I'm not expecting anyone.",
    exampleTranslation: "Кто это? Я никого не жду.",
  },
  {
    phrase: "It's for you.",
    translation: "Это тебе.",
    example: "It's for you, someone at the door.",
    exampleTranslation: "Это тебе, кто-то у двери.",
  },
  {
    phrase: "Tell them I'm busy.",
    translation: "Скажи, что я занят.",
    example: "Tell them I'm busy, I'll call later.",
    exampleTranslation: "Скажи, что я занят, перезвоню.",
  },
  {
    phrase: "I'll call them later.",
    translation: "Я им перезвоню позже.",
    example: "I'll call them later, I'm eating.",
    exampleTranslation: "Я им перезвоню позже, я ем.",
  },
  {
    phrase: "Let's eat.",
    translation: "Давай есть.",
    example: "Let's eat before it gets cold.",
    exampleTranslation: "Давай есть, пока не остыло.",
  },
  {
    phrase: "Help yourself.",
    translation: "Угощайся.",
    example: "Help yourself, there's plenty.",
    exampleTranslation: "Угощайся, всего полно.",
  },
  {
    phrase: "There's more in the pot.",
    translation: "В кастрюле ещё есть.",
    example: "There's more in the pot if you want seconds.",
    exampleTranslation: "В кастрюле ещё есть, если хочешь добавки.",
  },
  {
    phrase: "I already ate.",
    translation: "Я уже ел.",
    example: "I already ate at work.",
    exampleTranslation: "Я уже ел на работе.",
  },
  {
    phrase: "I haven't eaten yet.",
    translation: "Я ещё не ел.",
    example: "I haven't eaten yet, I'm starving.",
    exampleTranslation: "Я ещё не ел, умираю с голоду.",
  },
  {
    phrase: "Let's order in.",
    translation: "Давай закажем еду.",
    example: "I'm too tired to cook, let's order in.",
    exampleTranslation: "Сил готовить нет, давай закажем еду.",
  },
  {
    phrase: "I'll cook pasta.",
    translation: "Я сварю пасту.",
    example: "I'll cook pasta, it's quick.",
    exampleTranslation: "Я сварю пасту, это быстро.",
  },
  {
    phrase: "Make a salad.",
    translation: "Сделай салат.",
    example: "Make a salad, I'll do the main.",
    exampleTranslation: "Сделай салат, я сделаю основное.",
  },
  {
    phrase: "The rice is ready.",
    translation: "Рис готов.",
    example: "The rice is ready, turn it off.",
    exampleTranslation: "Рис готов, выключи.",
  },
  {
    phrase: "Don't overcook it.",
    translation: "Не перевари.",
    example: "Don't overcook it, two more minutes.",
    exampleTranslation: "Не перевари, ещё две минуты.",
  },
  {
    phrase: "I spilled it.",
    translation: "Я пролил.",
    example: "I spilled it, where's a rag?",
    exampleTranslation: "Я пролил, где тряпка?",
  },
  {
    phrase: "I'll wipe it up.",
    translation: "Я вытру.",
    example: "Don't worry, I'll wipe it up.",
    exampleTranslation: "Не переживай, я вытру.",
  },
  {
    phrase: "Use a napkin.",
    translation: "Возьми салфетку.",
    example: "Use a napkin, you have sauce on you.",
    exampleTranslation: "Возьми салфетку, у тебя соус.",
  },
  {
    phrase: "This is delicious.",
    translation: "Очень вкусно.",
    example: "This is delicious, what did you put in it?",
    exampleTranslation: "Очень вкусно, что ты туда положил?",
  },
  {
    phrase: "It's a bit bland.",
    translation: "Немного пресно.",
    example: "It's a bit bland, add salt.",
    exampleTranslation: "Немного пресно, добавь соли.",
  },
  {
    phrase: "Add some pepper.",
    translation: "Добавь перца.",
    example: "Add some pepper, it needs it.",
    exampleTranslation: "Добавь перца, не хватает.",
  },
  {
    phrase: "I saved you a plate.",
    translation: "Я тебе тарелку оставил.",
    example: "I saved you a plate in the fridge.",
    exampleTranslation: "Я тебе тарелку оставил в холодильнике.",
  },
  {
    phrase: "Eat before it gets cold.",
    translation: "Ешь, пока не остыло.",
    example: "Eat before it gets cold, I just made it.",
    exampleTranslation: "Ешь, пока не остыло, я только приготовил.",
  },
  {
    phrase: "I'm still cooking.",
    translation: "Я ещё готовлю.",
    example: "Don't set the table yet, I'm still cooking.",
    exampleTranslation: "Стол пока не накрывай, я ещё готовлю.",
  },
  {
    phrase: "Can you water the plants?",
    translation: "Можешь полить цветы?",
    example: "Can you water the plants, they look dry.",
    exampleTranslation: "Можешь полить цветы, они сухие.",
  },
  {
    phrase: "The plants need water.",
    translation: "Цветам нужна вода.",
    example: "The plants need water, I forgot yesterday.",
    exampleTranslation: "Цветам нужна вода, вчера забыл.",
  },
];
